// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/web_socket_sub_diapason.proto

package protoModels;

public interface ActionCreateSubDiapasonProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ActionCreateSubDiapasonProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.TypeSubDiapasonProto type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.TypeSubDiapasonProto type = 1;</code>
   * @return The type.
   */
  protoModels.TypeSubDiapasonProto getType();

  /**
   * <code>float startFrequency = 2;</code>
   * @return The startFrequency.
   */
  float getStartFrequency();

  /**
   * <code>float endFrequency = 3;</code>
   * @return The endFrequency.
   */
  float getEndFrequency();
}
