// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/web_socket_sub_diapason.proto

package protoModels;

/**
 * Protobuf type {@code ActionCreateSubDiapasonProto}
 */
public final class ActionCreateSubDiapasonProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ActionCreateSubDiapasonProto)
    ActionCreateSubDiapasonProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ActionCreateSubDiapasonProto.newBuilder() to construct.
  private ActionCreateSubDiapasonProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ActionCreateSubDiapasonProto() {
    type_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ActionCreateSubDiapasonProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protoModels.WebSocketSubDiapason.internal_static_ActionCreateSubDiapasonProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protoModels.WebSocketSubDiapason.internal_static_ActionCreateSubDiapasonProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protoModels.ActionCreateSubDiapasonProto.class, protoModels.ActionCreateSubDiapasonProto.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_ = 0;
  /**
   * <code>.TypeSubDiapasonProto type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.TypeSubDiapasonProto type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public protoModels.TypeSubDiapasonProto getType() {
    protoModels.TypeSubDiapasonProto result = protoModels.TypeSubDiapasonProto.forNumber(type_);
    return result == null ? protoModels.TypeSubDiapasonProto.UNRECOGNIZED : result;
  }

  public static final int STARTFREQUENCY_FIELD_NUMBER = 2;
  private float startFrequency_ = 0F;
  /**
   * <code>float startFrequency = 2;</code>
   * @return The startFrequency.
   */
  @java.lang.Override
  public float getStartFrequency() {
    return startFrequency_;
  }

  public static final int ENDFREQUENCY_FIELD_NUMBER = 3;
  private float endFrequency_ = 0F;
  /**
   * <code>float endFrequency = 3;</code>
   * @return The endFrequency.
   */
  @java.lang.Override
  public float getEndFrequency() {
    return endFrequency_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != protoModels.TypeSubDiapasonProto.FIND.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (java.lang.Float.floatToRawIntBits(startFrequency_) != 0) {
      output.writeFloat(2, startFrequency_);
    }
    if (java.lang.Float.floatToRawIntBits(endFrequency_) != 0) {
      output.writeFloat(3, endFrequency_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != protoModels.TypeSubDiapasonProto.FIND.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (java.lang.Float.floatToRawIntBits(startFrequency_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, startFrequency_);
    }
    if (java.lang.Float.floatToRawIntBits(endFrequency_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, endFrequency_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protoModels.ActionCreateSubDiapasonProto)) {
      return super.equals(obj);
    }
    protoModels.ActionCreateSubDiapasonProto other = (protoModels.ActionCreateSubDiapasonProto) obj;

    if (type_ != other.type_) return false;
    if (java.lang.Float.floatToIntBits(getStartFrequency())
        != java.lang.Float.floatToIntBits(
            other.getStartFrequency())) return false;
    if (java.lang.Float.floatToIntBits(getEndFrequency())
        != java.lang.Float.floatToIntBits(
            other.getEndFrequency())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + STARTFREQUENCY_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getStartFrequency());
    hash = (37 * hash) + ENDFREQUENCY_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getEndFrequency());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protoModels.ActionCreateSubDiapasonProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.ActionCreateSubDiapasonProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.ActionCreateSubDiapasonProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.ActionCreateSubDiapasonProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.ActionCreateSubDiapasonProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.ActionCreateSubDiapasonProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.ActionCreateSubDiapasonProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protoModels.ActionCreateSubDiapasonProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protoModels.ActionCreateSubDiapasonProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protoModels.ActionCreateSubDiapasonProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protoModels.ActionCreateSubDiapasonProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protoModels.ActionCreateSubDiapasonProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protoModels.ActionCreateSubDiapasonProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ActionCreateSubDiapasonProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ActionCreateSubDiapasonProto)
      protoModels.ActionCreateSubDiapasonProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoModels.WebSocketSubDiapason.internal_static_ActionCreateSubDiapasonProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoModels.WebSocketSubDiapason.internal_static_ActionCreateSubDiapasonProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoModels.ActionCreateSubDiapasonProto.class, protoModels.ActionCreateSubDiapasonProto.Builder.class);
    }

    // Construct using protoModels.ActionCreateSubDiapasonProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = 0;
      startFrequency_ = 0F;
      endFrequency_ = 0F;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protoModels.WebSocketSubDiapason.internal_static_ActionCreateSubDiapasonProto_descriptor;
    }

    @java.lang.Override
    public protoModels.ActionCreateSubDiapasonProto getDefaultInstanceForType() {
      return protoModels.ActionCreateSubDiapasonProto.getDefaultInstance();
    }

    @java.lang.Override
    public protoModels.ActionCreateSubDiapasonProto build() {
      protoModels.ActionCreateSubDiapasonProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protoModels.ActionCreateSubDiapasonProto buildPartial() {
      protoModels.ActionCreateSubDiapasonProto result = new protoModels.ActionCreateSubDiapasonProto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(protoModels.ActionCreateSubDiapasonProto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.startFrequency_ = startFrequency_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.endFrequency_ = endFrequency_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protoModels.ActionCreateSubDiapasonProto) {
        return mergeFrom((protoModels.ActionCreateSubDiapasonProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protoModels.ActionCreateSubDiapasonProto other) {
      if (other == protoModels.ActionCreateSubDiapasonProto.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.getStartFrequency() != 0F) {
        setStartFrequency(other.getStartFrequency());
      }
      if (other.getEndFrequency() != 0F) {
        setEndFrequency(other.getEndFrequency());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 21: {
              startFrequency_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            case 29: {
              endFrequency_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <code>.TypeSubDiapasonProto type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.TypeSubDiapasonProto type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.TypeSubDiapasonProto type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public protoModels.TypeSubDiapasonProto getType() {
      protoModels.TypeSubDiapasonProto result = protoModels.TypeSubDiapasonProto.forNumber(type_);
      return result == null ? protoModels.TypeSubDiapasonProto.UNRECOGNIZED : result;
    }
    /**
     * <code>.TypeSubDiapasonProto type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(protoModels.TypeSubDiapasonProto value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.TypeSubDiapasonProto type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      onChanged();
      return this;
    }

    private float startFrequency_ ;
    /**
     * <code>float startFrequency = 2;</code>
     * @return The startFrequency.
     */
    @java.lang.Override
    public float getStartFrequency() {
      return startFrequency_;
    }
    /**
     * <code>float startFrequency = 2;</code>
     * @param value The startFrequency to set.
     * @return This builder for chaining.
     */
    public Builder setStartFrequency(float value) {
      
      startFrequency_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>float startFrequency = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartFrequency() {
      bitField0_ = (bitField0_ & ~0x00000002);
      startFrequency_ = 0F;
      onChanged();
      return this;
    }

    private float endFrequency_ ;
    /**
     * <code>float endFrequency = 3;</code>
     * @return The endFrequency.
     */
    @java.lang.Override
    public float getEndFrequency() {
      return endFrequency_;
    }
    /**
     * <code>float endFrequency = 3;</code>
     * @param value The endFrequency to set.
     * @return This builder for chaining.
     */
    public Builder setEndFrequency(float value) {
      
      endFrequency_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>float endFrequency = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndFrequency() {
      bitField0_ = (bitField0_ & ~0x00000004);
      endFrequency_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ActionCreateSubDiapasonProto)
  }

  // @@protoc_insertion_point(class_scope:ActionCreateSubDiapasonProto)
  private static final protoModels.ActionCreateSubDiapasonProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protoModels.ActionCreateSubDiapasonProto();
  }

  public static protoModels.ActionCreateSubDiapasonProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ActionCreateSubDiapasonProto>
      PARSER = new com.google.protobuf.AbstractParser<ActionCreateSubDiapasonProto>() {
    @java.lang.Override
    public ActionCreateSubDiapasonProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ActionCreateSubDiapasonProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ActionCreateSubDiapasonProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protoModels.ActionCreateSubDiapasonProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

