// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/web_socket_sub_diapason.proto

package protoModels;

public interface ActionDeleteSubDiapasonProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ActionDeleteSubDiapasonProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float frequency = 1;</code>
   * @return The frequency.
   */
  float getFrequency();
}
