// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/web_socket_sub_diapason.proto

package protoModels;

public interface ActionDeleteAllSubDiapasonProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ActionDeleteAllSubDiapasonProto)
    com.google.protobuf.MessageOrBuilder {
}
