// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/analizator_api.proto

package protoModels;

public final class AnalizatorApi {
  private AnalizatorApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnalizatorApiProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnalizatorApiProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WebSocketSpectrumProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WebSocketSpectrumProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WebSocketGetAllInfoProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WebSocketGetAllInfoProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WebSocketResponseProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WebSocketResponseProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WebSocketTaskProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WebSocketTaskProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#src-java/proto/analizator_api.proto\032\'s" +
      "rc-java/proto/web_socket_message.proto\"\321" +
      "\001\n\022AnalizatorApiProto\022/\n\014spectrumData\030\001 " +
      "\001(\0132\027.WebSocketSpectrumProtoH\000\022-\n\010fullIn" +
      "fo\030\002 \001(\0132\031.WebSocketGetAllInfoProtoH\000\022#\n" +
      "\004task\030\003 \001(\0132\023.WebSocketTaskProtoH\000\022+\n\010re" +
      "sponse\030\004 \001(\0132\027.WebSocketResponseProtoH\000B" +
      "\t\n\007taskApi\"7\n\026WebSocketSpectrumProto\022\014\n\004" +
      "data\030\001 \001(\014\022\017\n\007azimuth\030\002 \001(\005\",\n\030WebSocket" +
      "GetAllInfoProto\022\020\n\010uuidTask\030\001 \001(\t\"X\n\026Web" +
      "SocketResponseProto\022\020\n\010uuidTask\030\001 \001(\t\022,\n" +
      "\006status\030\002 \001(\0162\034.WebSocketStatusMessagePr" +
      "oto\"S\n\022WebSocketTaskProto\022\020\n\010uuidTask\030\001 " +
      "\001(\t\022+\n\007message\030\002 \001(\0132\032.WebSocketMessageT" +
      "askProto*=\n\033WebSocketStatusMessageProto\022" +
      "\014\n\010ACCEPTED\020\000\022\020\n\014NOT_ACCEPTED\020\001B\017\n\013proto" +
      "ModelsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protoModels.WebSocketMessage.getDescriptor(),
        });
    internal_static_AnalizatorApiProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AnalizatorApiProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnalizatorApiProto_descriptor,
        new java.lang.String[] { "SpectrumData", "FullInfo", "Task", "Response", "TaskApi", });
    internal_static_WebSocketSpectrumProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_WebSocketSpectrumProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WebSocketSpectrumProto_descriptor,
        new java.lang.String[] { "Data", "Azimuth", });
    internal_static_WebSocketGetAllInfoProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_WebSocketGetAllInfoProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WebSocketGetAllInfoProto_descriptor,
        new java.lang.String[] { "UuidTask", });
    internal_static_WebSocketResponseProto_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_WebSocketResponseProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WebSocketResponseProto_descriptor,
        new java.lang.String[] { "UuidTask", "Status", });
    internal_static_WebSocketTaskProto_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_WebSocketTaskProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WebSocketTaskProto_descriptor,
        new java.lang.String[] { "UuidTask", "Message", });
    protoModels.WebSocketMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
