// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/analizator_api.proto

package protoModels;

public interface AnalizatorApiProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AnalizatorApiProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.WebSocketSpectrumProto spectrumData = 1;</code>
   * @return Whether the spectrumData field is set.
   */
  boolean hasSpectrumData();
  /**
   * <code>.WebSocketSpectrumProto spectrumData = 1;</code>
   * @return The spectrumData.
   */
  protoModels.WebSocketSpectrumProto getSpectrumData();
  /**
   * <code>.WebSocketSpectrumProto spectrumData = 1;</code>
   */
  protoModels.WebSocketSpectrumProtoOrBuilder getSpectrumDataOrBuilder();

  /**
   * <code>.WebSocketGetAllInfoProto fullInfo = 2;</code>
   * @return Whether the fullInfo field is set.
   */
  boolean hasFullInfo();
  /**
   * <code>.WebSocketGetAllInfoProto fullInfo = 2;</code>
   * @return The fullInfo.
   */
  protoModels.WebSocketGetAllInfoProto getFullInfo();
  /**
   * <code>.WebSocketGetAllInfoProto fullInfo = 2;</code>
   */
  protoModels.WebSocketGetAllInfoProtoOrBuilder getFullInfoOrBuilder();

  /**
   * <code>.WebSocketTaskProto task = 3;</code>
   * @return Whether the task field is set.
   */
  boolean hasTask();
  /**
   * <code>.WebSocketTaskProto task = 3;</code>
   * @return The task.
   */
  protoModels.WebSocketTaskProto getTask();
  /**
   * <code>.WebSocketTaskProto task = 3;</code>
   */
  protoModels.WebSocketTaskProtoOrBuilder getTaskOrBuilder();

  /**
   * <code>.WebSocketResponseProto response = 4;</code>
   * @return Whether the response field is set.
   */
  boolean hasResponse();
  /**
   * <code>.WebSocketResponseProto response = 4;</code>
   * @return The response.
   */
  protoModels.WebSocketResponseProto getResponse();
  /**
   * <code>.WebSocketResponseProto response = 4;</code>
   */
  protoModels.WebSocketResponseProtoOrBuilder getResponseOrBuilder();

  public protoModels.AnalizatorApiProto.TaskApiCase getTaskApiCase();
}
