// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/frequency_range.proto

package protoModels;

public final class FrequencyRange {
  private FrequencyRange() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FrequencyRangeProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FrequencyRangeProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$src-java/proto/frequency_range.proto\"A" +
      "\n\023FrequencyRangeProto\022\024\n\014minFrequency\030\001 " +
      "\001(\005\022\024\n\014maxFrequency\030\002 \001(\005B\017\n\013protoModels" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FrequencyRangeProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FrequencyRangeProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FrequencyRangeProto_descriptor,
        new java.lang.String[] { "MinFrequency", "MaxFrequency", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
