// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/frequency_range.proto

package protoModels;

public interface FrequencyRangeProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FrequencyRangeProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Минимальная частота
   * </pre>
   *
   * <code>int32 minFrequency = 1;</code>
   * @return The minFrequency.
   */
  int getMinFrequency();

  /**
   * <pre>
   * Максимальная частота
   * </pre>
   *
   * <code>int32 maxFrequency = 2;</code>
   * @return The maxFrequency.
   */
  int getMaxFrequency();
}
