// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/web_socket_message.proto

package protoModels;

public interface FullInfoApiMessageProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FullInfoApiMessageProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.InfoGadalkaProto infoGadalka = 1;</code>
   * @return Whether the infoGadalka field is set.
   */
  boolean hasInfoGadalka();
  /**
   * <code>.InfoGadalkaProto infoGadalka = 1;</code>
   * @return The infoGadalka.
   */
  protoModels.InfoGadalkaProto getInfoGadalka();
  /**
   * <code>.InfoGadalkaProto infoGadalka = 1;</code>
   */
  protoModels.InfoGadalkaProtoOrBuilder getInfoGadalkaOrBuilder();

  /**
   * <code>.SerifTypeProto serifTypeAlgorithm = 2;</code>
   * @return The enum numeric value on the wire for serifTypeAlgorithm.
   */
  int getSerifTypeAlgorithmValue();
  /**
   * <code>.SerifTypeProto serifTypeAlgorithm = 2;</code>
   * @return The serifTypeAlgorithm.
   */
  protoModels.SerifTypeProto getSerifTypeAlgorithm();

  /**
   * <code>optional bytes minimalSerifLine = 3;</code>
   * @return Whether the minimalSerifLine field is set.
   */
  boolean hasMinimalSerifLine();
  /**
   * <code>optional bytes minimalSerifLine = 3;</code>
   * @return The minimalSerifLine.
   */
  com.google.protobuf.ByteString getMinimalSerifLine();

  /**
   * <code>optional bytes listSelectionSubDiapason = 4;</code>
   * @return Whether the listSelectionSubDiapason field is set.
   */
  boolean hasListSelectionSubDiapason();
  /**
   * <code>optional bytes listSelectionSubDiapason = 4;</code>
   * @return The listSelectionSubDiapason.
   */
  com.google.protobuf.ByteString getListSelectionSubDiapason();
}
