// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/web_socket_message.proto

package protoModels;

/**
 * Protobuf type {@code FullInfoApiMessageProto}
 */
public final class FullInfoApiMessageProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FullInfoApiMessageProto)
    FullInfoApiMessageProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FullInfoApiMessageProto.newBuilder() to construct.
  private FullInfoApiMessageProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FullInfoApiMessageProto() {
    serifTypeAlgorithm_ = 0;
    minimalSerifLine_ = com.google.protobuf.ByteString.EMPTY;
    listSelectionSubDiapason_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FullInfoApiMessageProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protoModels.WebSocketMessage.internal_static_FullInfoApiMessageProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protoModels.WebSocketMessage.internal_static_FullInfoApiMessageProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protoModels.FullInfoApiMessageProto.class, protoModels.FullInfoApiMessageProto.Builder.class);
  }

  private int bitField0_;
  public static final int INFOGADALKA_FIELD_NUMBER = 1;
  private protoModels.InfoGadalkaProto infoGadalka_;
  /**
   * <code>.InfoGadalkaProto infoGadalka = 1;</code>
   * @return Whether the infoGadalka field is set.
   */
  @java.lang.Override
  public boolean hasInfoGadalka() {
    return infoGadalka_ != null;
  }
  /**
   * <code>.InfoGadalkaProto infoGadalka = 1;</code>
   * @return The infoGadalka.
   */
  @java.lang.Override
  public protoModels.InfoGadalkaProto getInfoGadalka() {
    return infoGadalka_ == null ? protoModels.InfoGadalkaProto.getDefaultInstance() : infoGadalka_;
  }
  /**
   * <code>.InfoGadalkaProto infoGadalka = 1;</code>
   */
  @java.lang.Override
  public protoModels.InfoGadalkaProtoOrBuilder getInfoGadalkaOrBuilder() {
    return infoGadalka_ == null ? protoModels.InfoGadalkaProto.getDefaultInstance() : infoGadalka_;
  }

  public static final int SERIFTYPEALGORITHM_FIELD_NUMBER = 2;
  private int serifTypeAlgorithm_ = 0;
  /**
   * <code>.SerifTypeProto serifTypeAlgorithm = 2;</code>
   * @return The enum numeric value on the wire for serifTypeAlgorithm.
   */
  @java.lang.Override public int getSerifTypeAlgorithmValue() {
    return serifTypeAlgorithm_;
  }
  /**
   * <code>.SerifTypeProto serifTypeAlgorithm = 2;</code>
   * @return The serifTypeAlgorithm.
   */
  @java.lang.Override public protoModels.SerifTypeProto getSerifTypeAlgorithm() {
    protoModels.SerifTypeProto result = protoModels.SerifTypeProto.forNumber(serifTypeAlgorithm_);
    return result == null ? protoModels.SerifTypeProto.UNRECOGNIZED : result;
  }

  public static final int MINIMALSERIFLINE_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString minimalSerifLine_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>optional bytes minimalSerifLine = 3;</code>
   * @return Whether the minimalSerifLine field is set.
   */
  @java.lang.Override
  public boolean hasMinimalSerifLine() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional bytes minimalSerifLine = 3;</code>
   * @return The minimalSerifLine.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getMinimalSerifLine() {
    return minimalSerifLine_;
  }

  public static final int LISTSELECTIONSUBDIAPASON_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString listSelectionSubDiapason_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>optional bytes listSelectionSubDiapason = 4;</code>
   * @return Whether the listSelectionSubDiapason field is set.
   */
  @java.lang.Override
  public boolean hasListSelectionSubDiapason() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional bytes listSelectionSubDiapason = 4;</code>
   * @return The listSelectionSubDiapason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getListSelectionSubDiapason() {
    return listSelectionSubDiapason_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (infoGadalka_ != null) {
      output.writeMessage(1, getInfoGadalka());
    }
    if (serifTypeAlgorithm_ != protoModels.SerifTypeProto.MANUAL.getNumber()) {
      output.writeEnum(2, serifTypeAlgorithm_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBytes(3, minimalSerifLine_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBytes(4, listSelectionSubDiapason_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (infoGadalka_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getInfoGadalka());
    }
    if (serifTypeAlgorithm_ != protoModels.SerifTypeProto.MANUAL.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, serifTypeAlgorithm_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, minimalSerifLine_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, listSelectionSubDiapason_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protoModels.FullInfoApiMessageProto)) {
      return super.equals(obj);
    }
    protoModels.FullInfoApiMessageProto other = (protoModels.FullInfoApiMessageProto) obj;

    if (hasInfoGadalka() != other.hasInfoGadalka()) return false;
    if (hasInfoGadalka()) {
      if (!getInfoGadalka()
          .equals(other.getInfoGadalka())) return false;
    }
    if (serifTypeAlgorithm_ != other.serifTypeAlgorithm_) return false;
    if (hasMinimalSerifLine() != other.hasMinimalSerifLine()) return false;
    if (hasMinimalSerifLine()) {
      if (!getMinimalSerifLine()
          .equals(other.getMinimalSerifLine())) return false;
    }
    if (hasListSelectionSubDiapason() != other.hasListSelectionSubDiapason()) return false;
    if (hasListSelectionSubDiapason()) {
      if (!getListSelectionSubDiapason()
          .equals(other.getListSelectionSubDiapason())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasInfoGadalka()) {
      hash = (37 * hash) + INFOGADALKA_FIELD_NUMBER;
      hash = (53 * hash) + getInfoGadalka().hashCode();
    }
    hash = (37 * hash) + SERIFTYPEALGORITHM_FIELD_NUMBER;
    hash = (53 * hash) + serifTypeAlgorithm_;
    if (hasMinimalSerifLine()) {
      hash = (37 * hash) + MINIMALSERIFLINE_FIELD_NUMBER;
      hash = (53 * hash) + getMinimalSerifLine().hashCode();
    }
    if (hasListSelectionSubDiapason()) {
      hash = (37 * hash) + LISTSELECTIONSUBDIAPASON_FIELD_NUMBER;
      hash = (53 * hash) + getListSelectionSubDiapason().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protoModels.FullInfoApiMessageProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.FullInfoApiMessageProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.FullInfoApiMessageProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.FullInfoApiMessageProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.FullInfoApiMessageProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.FullInfoApiMessageProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.FullInfoApiMessageProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protoModels.FullInfoApiMessageProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protoModels.FullInfoApiMessageProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protoModels.FullInfoApiMessageProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protoModels.FullInfoApiMessageProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protoModels.FullInfoApiMessageProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protoModels.FullInfoApiMessageProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code FullInfoApiMessageProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FullInfoApiMessageProto)
      protoModels.FullInfoApiMessageProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoModels.WebSocketMessage.internal_static_FullInfoApiMessageProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoModels.WebSocketMessage.internal_static_FullInfoApiMessageProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoModels.FullInfoApiMessageProto.class, protoModels.FullInfoApiMessageProto.Builder.class);
    }

    // Construct using protoModels.FullInfoApiMessageProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      infoGadalka_ = null;
      if (infoGadalkaBuilder_ != null) {
        infoGadalkaBuilder_.dispose();
        infoGadalkaBuilder_ = null;
      }
      serifTypeAlgorithm_ = 0;
      minimalSerifLine_ = com.google.protobuf.ByteString.EMPTY;
      listSelectionSubDiapason_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protoModels.WebSocketMessage.internal_static_FullInfoApiMessageProto_descriptor;
    }

    @java.lang.Override
    public protoModels.FullInfoApiMessageProto getDefaultInstanceForType() {
      return protoModels.FullInfoApiMessageProto.getDefaultInstance();
    }

    @java.lang.Override
    public protoModels.FullInfoApiMessageProto build() {
      protoModels.FullInfoApiMessageProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protoModels.FullInfoApiMessageProto buildPartial() {
      protoModels.FullInfoApiMessageProto result = new protoModels.FullInfoApiMessageProto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(protoModels.FullInfoApiMessageProto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.infoGadalka_ = infoGadalkaBuilder_ == null
            ? infoGadalka_
            : infoGadalkaBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.serifTypeAlgorithm_ = serifTypeAlgorithm_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.minimalSerifLine_ = minimalSerifLine_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.listSelectionSubDiapason_ = listSelectionSubDiapason_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protoModels.FullInfoApiMessageProto) {
        return mergeFrom((protoModels.FullInfoApiMessageProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protoModels.FullInfoApiMessageProto other) {
      if (other == protoModels.FullInfoApiMessageProto.getDefaultInstance()) return this;
      if (other.hasInfoGadalka()) {
        mergeInfoGadalka(other.getInfoGadalka());
      }
      if (other.serifTypeAlgorithm_ != 0) {
        setSerifTypeAlgorithmValue(other.getSerifTypeAlgorithmValue());
      }
      if (other.hasMinimalSerifLine()) {
        setMinimalSerifLine(other.getMinimalSerifLine());
      }
      if (other.hasListSelectionSubDiapason()) {
        setListSelectionSubDiapason(other.getListSelectionSubDiapason());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getInfoGadalkaFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              serifTypeAlgorithm_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              minimalSerifLine_ = input.readBytes();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              listSelectionSubDiapason_ = input.readBytes();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private protoModels.InfoGadalkaProto infoGadalka_;
    private com.google.protobuf.SingleFieldBuilderV3<
        protoModels.InfoGadalkaProto, protoModels.InfoGadalkaProto.Builder, protoModels.InfoGadalkaProtoOrBuilder> infoGadalkaBuilder_;
    /**
     * <code>.InfoGadalkaProto infoGadalka = 1;</code>
     * @return Whether the infoGadalka field is set.
     */
    public boolean hasInfoGadalka() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.InfoGadalkaProto infoGadalka = 1;</code>
     * @return The infoGadalka.
     */
    public protoModels.InfoGadalkaProto getInfoGadalka() {
      if (infoGadalkaBuilder_ == null) {
        return infoGadalka_ == null ? protoModels.InfoGadalkaProto.getDefaultInstance() : infoGadalka_;
      } else {
        return infoGadalkaBuilder_.getMessage();
      }
    }
    /**
     * <code>.InfoGadalkaProto infoGadalka = 1;</code>
     */
    public Builder setInfoGadalka(protoModels.InfoGadalkaProto value) {
      if (infoGadalkaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        infoGadalka_ = value;
      } else {
        infoGadalkaBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.InfoGadalkaProto infoGadalka = 1;</code>
     */
    public Builder setInfoGadalka(
        protoModels.InfoGadalkaProto.Builder builderForValue) {
      if (infoGadalkaBuilder_ == null) {
        infoGadalka_ = builderForValue.build();
      } else {
        infoGadalkaBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.InfoGadalkaProto infoGadalka = 1;</code>
     */
    public Builder mergeInfoGadalka(protoModels.InfoGadalkaProto value) {
      if (infoGadalkaBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          infoGadalka_ != null &&
          infoGadalka_ != protoModels.InfoGadalkaProto.getDefaultInstance()) {
          getInfoGadalkaBuilder().mergeFrom(value);
        } else {
          infoGadalka_ = value;
        }
      } else {
        infoGadalkaBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.InfoGadalkaProto infoGadalka = 1;</code>
     */
    public Builder clearInfoGadalka() {
      bitField0_ = (bitField0_ & ~0x00000001);
      infoGadalka_ = null;
      if (infoGadalkaBuilder_ != null) {
        infoGadalkaBuilder_.dispose();
        infoGadalkaBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.InfoGadalkaProto infoGadalka = 1;</code>
     */
    public protoModels.InfoGadalkaProto.Builder getInfoGadalkaBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getInfoGadalkaFieldBuilder().getBuilder();
    }
    /**
     * <code>.InfoGadalkaProto infoGadalka = 1;</code>
     */
    public protoModels.InfoGadalkaProtoOrBuilder getInfoGadalkaOrBuilder() {
      if (infoGadalkaBuilder_ != null) {
        return infoGadalkaBuilder_.getMessageOrBuilder();
      } else {
        return infoGadalka_ == null ?
            protoModels.InfoGadalkaProto.getDefaultInstance() : infoGadalka_;
      }
    }
    /**
     * <code>.InfoGadalkaProto infoGadalka = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        protoModels.InfoGadalkaProto, protoModels.InfoGadalkaProto.Builder, protoModels.InfoGadalkaProtoOrBuilder> 
        getInfoGadalkaFieldBuilder() {
      if (infoGadalkaBuilder_ == null) {
        infoGadalkaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            protoModels.InfoGadalkaProto, protoModels.InfoGadalkaProto.Builder, protoModels.InfoGadalkaProtoOrBuilder>(
                getInfoGadalka(),
                getParentForChildren(),
                isClean());
        infoGadalka_ = null;
      }
      return infoGadalkaBuilder_;
    }

    private int serifTypeAlgorithm_ = 0;
    /**
     * <code>.SerifTypeProto serifTypeAlgorithm = 2;</code>
     * @return The enum numeric value on the wire for serifTypeAlgorithm.
     */
    @java.lang.Override public int getSerifTypeAlgorithmValue() {
      return serifTypeAlgorithm_;
    }
    /**
     * <code>.SerifTypeProto serifTypeAlgorithm = 2;</code>
     * @param value The enum numeric value on the wire for serifTypeAlgorithm to set.
     * @return This builder for chaining.
     */
    public Builder setSerifTypeAlgorithmValue(int value) {
      serifTypeAlgorithm_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.SerifTypeProto serifTypeAlgorithm = 2;</code>
     * @return The serifTypeAlgorithm.
     */
    @java.lang.Override
    public protoModels.SerifTypeProto getSerifTypeAlgorithm() {
      protoModels.SerifTypeProto result = protoModels.SerifTypeProto.forNumber(serifTypeAlgorithm_);
      return result == null ? protoModels.SerifTypeProto.UNRECOGNIZED : result;
    }
    /**
     * <code>.SerifTypeProto serifTypeAlgorithm = 2;</code>
     * @param value The serifTypeAlgorithm to set.
     * @return This builder for chaining.
     */
    public Builder setSerifTypeAlgorithm(protoModels.SerifTypeProto value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      serifTypeAlgorithm_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.SerifTypeProto serifTypeAlgorithm = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSerifTypeAlgorithm() {
      bitField0_ = (bitField0_ & ~0x00000002);
      serifTypeAlgorithm_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString minimalSerifLine_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes minimalSerifLine = 3;</code>
     * @return Whether the minimalSerifLine field is set.
     */
    @java.lang.Override
    public boolean hasMinimalSerifLine() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bytes minimalSerifLine = 3;</code>
     * @return The minimalSerifLine.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMinimalSerifLine() {
      return minimalSerifLine_;
    }
    /**
     * <code>optional bytes minimalSerifLine = 3;</code>
     * @param value The minimalSerifLine to set.
     * @return This builder for chaining.
     */
    public Builder setMinimalSerifLine(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      minimalSerifLine_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes minimalSerifLine = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinimalSerifLine() {
      bitField0_ = (bitField0_ & ~0x00000004);
      minimalSerifLine_ = getDefaultInstance().getMinimalSerifLine();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString listSelectionSubDiapason_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes listSelectionSubDiapason = 4;</code>
     * @return Whether the listSelectionSubDiapason field is set.
     */
    @java.lang.Override
    public boolean hasListSelectionSubDiapason() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bytes listSelectionSubDiapason = 4;</code>
     * @return The listSelectionSubDiapason.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getListSelectionSubDiapason() {
      return listSelectionSubDiapason_;
    }
    /**
     * <code>optional bytes listSelectionSubDiapason = 4;</code>
     * @param value The listSelectionSubDiapason to set.
     * @return This builder for chaining.
     */
    public Builder setListSelectionSubDiapason(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      listSelectionSubDiapason_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes listSelectionSubDiapason = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearListSelectionSubDiapason() {
      bitField0_ = (bitField0_ & ~0x00000008);
      listSelectionSubDiapason_ = getDefaultInstance().getListSelectionSubDiapason();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:FullInfoApiMessageProto)
  }

  // @@protoc_insertion_point(class_scope:FullInfoApiMessageProto)
  private static final protoModels.FullInfoApiMessageProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protoModels.FullInfoApiMessageProto();
  }

  public static protoModels.FullInfoApiMessageProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FullInfoApiMessageProto>
      PARSER = new com.google.protobuf.AbstractParser<FullInfoApiMessageProto>() {
    @java.lang.Override
    public FullInfoApiMessageProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FullInfoApiMessageProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FullInfoApiMessageProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protoModels.FullInfoApiMessageProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

