// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/web_socket_message.proto

package protoModels;

public interface HideWaterfallMessageProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HideWaterfallMessageProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool visible = 1;</code>
   * @return The visible.
   */
  boolean getVisible();
}
