// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/info_chart_connect.proto

package protoModels;

public interface InfoChartConnectProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InfoChartConnectProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string host_name = 1;</code>
   * @return The hostName.
   */
  java.lang.String getHostName();
  /**
   * <code>string host_name = 1;</code>
   * @return The bytes for hostName.
   */
  com.google.protobuf.ByteString
      getHostNameBytes();

  /**
   * <code>int32 port_ws = 2;</code>
   * @return The portWs.
   */
  int getPortWs();

  /**
   * <code>string serverGadalkaID = 3;</code>
   * @return The serverGadalkaID.
   */
  java.lang.String getServerGadalkaID();
  /**
   * <code>string serverGadalkaID = 3;</code>
   * @return The bytes for serverGadalkaID.
   */
  com.google.protobuf.ByteString
      getServerGadalkaIDBytes();
}
