// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/info_chart_connect.proto

package protoModels;

public final class InfoChartConnect {
  private InfoChartConnect() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InfoChartConnectProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InfoChartConnectProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'src-java/proto/info_chart_connect.prot" +
      "o\"T\n\025InfoChartConnectProto\022\021\n\thost_name\030" +
      "\001 \001(\t\022\017\n\007port_ws\030\002 \001(\005\022\027\n\017serverGadalkaI" +
      "D\030\003 \001(\tB\017\n\013protoModelsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_InfoChartConnectProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_InfoChartConnectProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InfoChartConnectProto_descriptor,
        new java.lang.String[] { "HostName", "PortWs", "ServerGadalkaID", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
