// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/web_socket_message.proto

package protoModels;

public interface InfoGadalkaProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InfoGadalkaProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Диапазон частот выставленные на Гадалке
   * </pre>
   *
   * <code>.FrequencyRangeProto frequencySpectrum = 1;</code>
   * @return Whether the frequencySpectrum field is set.
   */
  boolean hasFrequencySpectrum();
  /**
   * <pre>
   * Диапазон частот выставленные на Гадалке
   * </pre>
   *
   * <code>.FrequencyRangeProto frequencySpectrum = 1;</code>
   * @return The frequencySpectrum.
   */
  protoModels.FrequencyRangeProto getFrequencySpectrum();
  /**
   * <pre>
   * Диапазон частот выставленные на Гадалке
   * </pre>
   *
   * <code>.FrequencyRangeProto frequencySpectrum = 1;</code>
   */
  protoModels.FrequencyRangeProtoOrBuilder getFrequencySpectrumOrBuilder();

  /**
   * <code>int32 gainLNA = 2;</code>
   * @return The gainLNA.
   */
  int getGainLNA();

  /**
   * <code>int32 gainVGA = 3;</code>
   * @return The gainVGA.
   */
  int getGainVGA();

  /**
   * <code>bool antennaLNA = 4;</code>
   * @return The antennaLNA.
   */
  boolean getAntennaLNA();

  /**
   * <code>int32 spectrumPaletteStart = 5;</code>
   * @return The spectrumPaletteStart.
   */
  int getSpectrumPaletteStart();

  /**
   * <code>int32 spectrumPaletteSize = 6;</code>
   * @return The spectrumPaletteSize.
   */
  int getSpectrumPaletteSize();

  /**
   * <code>int32 ffTBinHz = 7;</code>
   * @return The ffTBinHz.
   */
  int getFfTBinHz();

  /**
   * <code>int32 samples = 8;</code>
   * @return The samples.
   */
  int getSamples();

  /**
   * <code>int32 counterSignal = 9;</code>
   * @return The counterSignal.
   */
  int getCounterSignal();

  /**
   * <code>int32 counterLose = 10;</code>
   * @return The counterLose.
   */
  int getCounterLose();

  /**
   * <code>int32 subRangeRemote = 11;</code>
   * @return The subRangeRemote.
   */
  int getSubRangeRemote();
}
