// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/web_socket_message.proto

package protoModels;

/**
 * Protobuf type {@code InfoGadalkaProto}
 */
public final class InfoGadalkaProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:InfoGadalkaProto)
    InfoGadalkaProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InfoGadalkaProto.newBuilder() to construct.
  private InfoGadalkaProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InfoGadalkaProto() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InfoGadalkaProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protoModels.WebSocketMessage.internal_static_InfoGadalkaProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protoModels.WebSocketMessage.internal_static_InfoGadalkaProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protoModels.InfoGadalkaProto.class, protoModels.InfoGadalkaProto.Builder.class);
  }

  public static final int FREQUENCYSPECTRUM_FIELD_NUMBER = 1;
  private protoModels.FrequencyRangeProto frequencySpectrum_;
  /**
   * <pre>
   * Диапазон частот выставленные на Гадалке
   * </pre>
   *
   * <code>.FrequencyRangeProto frequencySpectrum = 1;</code>
   * @return Whether the frequencySpectrum field is set.
   */
  @java.lang.Override
  public boolean hasFrequencySpectrum() {
    return frequencySpectrum_ != null;
  }
  /**
   * <pre>
   * Диапазон частот выставленные на Гадалке
   * </pre>
   *
   * <code>.FrequencyRangeProto frequencySpectrum = 1;</code>
   * @return The frequencySpectrum.
   */
  @java.lang.Override
  public protoModels.FrequencyRangeProto getFrequencySpectrum() {
    return frequencySpectrum_ == null ? protoModels.FrequencyRangeProto.getDefaultInstance() : frequencySpectrum_;
  }
  /**
   * <pre>
   * Диапазон частот выставленные на Гадалке
   * </pre>
   *
   * <code>.FrequencyRangeProto frequencySpectrum = 1;</code>
   */
  @java.lang.Override
  public protoModels.FrequencyRangeProtoOrBuilder getFrequencySpectrumOrBuilder() {
    return frequencySpectrum_ == null ? protoModels.FrequencyRangeProto.getDefaultInstance() : frequencySpectrum_;
  }

  public static final int GAINLNA_FIELD_NUMBER = 2;
  private int gainLNA_ = 0;
  /**
   * <code>int32 gainLNA = 2;</code>
   * @return The gainLNA.
   */
  @java.lang.Override
  public int getGainLNA() {
    return gainLNA_;
  }

  public static final int GAINVGA_FIELD_NUMBER = 3;
  private int gainVGA_ = 0;
  /**
   * <code>int32 gainVGA = 3;</code>
   * @return The gainVGA.
   */
  @java.lang.Override
  public int getGainVGA() {
    return gainVGA_;
  }

  public static final int ANTENNALNA_FIELD_NUMBER = 4;
  private boolean antennaLNA_ = false;
  /**
   * <code>bool antennaLNA = 4;</code>
   * @return The antennaLNA.
   */
  @java.lang.Override
  public boolean getAntennaLNA() {
    return antennaLNA_;
  }

  public static final int SPECTRUMPALETTESTART_FIELD_NUMBER = 5;
  private int spectrumPaletteStart_ = 0;
  /**
   * <code>int32 spectrumPaletteStart = 5;</code>
   * @return The spectrumPaletteStart.
   */
  @java.lang.Override
  public int getSpectrumPaletteStart() {
    return spectrumPaletteStart_;
  }

  public static final int SPECTRUMPALETTESIZE_FIELD_NUMBER = 6;
  private int spectrumPaletteSize_ = 0;
  /**
   * <code>int32 spectrumPaletteSize = 6;</code>
   * @return The spectrumPaletteSize.
   */
  @java.lang.Override
  public int getSpectrumPaletteSize() {
    return spectrumPaletteSize_;
  }

  public static final int FFTBINHZ_FIELD_NUMBER = 7;
  private int ffTBinHz_ = 0;
  /**
   * <code>int32 ffTBinHz = 7;</code>
   * @return The ffTBinHz.
   */
  @java.lang.Override
  public int getFfTBinHz() {
    return ffTBinHz_;
  }

  public static final int SAMPLES_FIELD_NUMBER = 8;
  private int samples_ = 0;
  /**
   * <code>int32 samples = 8;</code>
   * @return The samples.
   */
  @java.lang.Override
  public int getSamples() {
    return samples_;
  }

  public static final int COUNTERSIGNAL_FIELD_NUMBER = 9;
  private int counterSignal_ = 0;
  /**
   * <code>int32 counterSignal = 9;</code>
   * @return The counterSignal.
   */
  @java.lang.Override
  public int getCounterSignal() {
    return counterSignal_;
  }

  public static final int COUNTERLOSE_FIELD_NUMBER = 10;
  private int counterLose_ = 0;
  /**
   * <code>int32 counterLose = 10;</code>
   * @return The counterLose.
   */
  @java.lang.Override
  public int getCounterLose() {
    return counterLose_;
  }

  public static final int SUBRANGEREMOTE_FIELD_NUMBER = 11;
  private int subRangeRemote_ = 0;
  /**
   * <code>int32 subRangeRemote = 11;</code>
   * @return The subRangeRemote.
   */
  @java.lang.Override
  public int getSubRangeRemote() {
    return subRangeRemote_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (frequencySpectrum_ != null) {
      output.writeMessage(1, getFrequencySpectrum());
    }
    if (gainLNA_ != 0) {
      output.writeInt32(2, gainLNA_);
    }
    if (gainVGA_ != 0) {
      output.writeInt32(3, gainVGA_);
    }
    if (antennaLNA_ != false) {
      output.writeBool(4, antennaLNA_);
    }
    if (spectrumPaletteStart_ != 0) {
      output.writeInt32(5, spectrumPaletteStart_);
    }
    if (spectrumPaletteSize_ != 0) {
      output.writeInt32(6, spectrumPaletteSize_);
    }
    if (ffTBinHz_ != 0) {
      output.writeInt32(7, ffTBinHz_);
    }
    if (samples_ != 0) {
      output.writeInt32(8, samples_);
    }
    if (counterSignal_ != 0) {
      output.writeInt32(9, counterSignal_);
    }
    if (counterLose_ != 0) {
      output.writeInt32(10, counterLose_);
    }
    if (subRangeRemote_ != 0) {
      output.writeInt32(11, subRangeRemote_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (frequencySpectrum_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getFrequencySpectrum());
    }
    if (gainLNA_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, gainLNA_);
    }
    if (gainVGA_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, gainVGA_);
    }
    if (antennaLNA_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, antennaLNA_);
    }
    if (spectrumPaletteStart_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, spectrumPaletteStart_);
    }
    if (spectrumPaletteSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, spectrumPaletteSize_);
    }
    if (ffTBinHz_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, ffTBinHz_);
    }
    if (samples_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, samples_);
    }
    if (counterSignal_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, counterSignal_);
    }
    if (counterLose_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, counterLose_);
    }
    if (subRangeRemote_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, subRangeRemote_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protoModels.InfoGadalkaProto)) {
      return super.equals(obj);
    }
    protoModels.InfoGadalkaProto other = (protoModels.InfoGadalkaProto) obj;

    if (hasFrequencySpectrum() != other.hasFrequencySpectrum()) return false;
    if (hasFrequencySpectrum()) {
      if (!getFrequencySpectrum()
          .equals(other.getFrequencySpectrum())) return false;
    }
    if (getGainLNA()
        != other.getGainLNA()) return false;
    if (getGainVGA()
        != other.getGainVGA()) return false;
    if (getAntennaLNA()
        != other.getAntennaLNA()) return false;
    if (getSpectrumPaletteStart()
        != other.getSpectrumPaletteStart()) return false;
    if (getSpectrumPaletteSize()
        != other.getSpectrumPaletteSize()) return false;
    if (getFfTBinHz()
        != other.getFfTBinHz()) return false;
    if (getSamples()
        != other.getSamples()) return false;
    if (getCounterSignal()
        != other.getCounterSignal()) return false;
    if (getCounterLose()
        != other.getCounterLose()) return false;
    if (getSubRangeRemote()
        != other.getSubRangeRemote()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasFrequencySpectrum()) {
      hash = (37 * hash) + FREQUENCYSPECTRUM_FIELD_NUMBER;
      hash = (53 * hash) + getFrequencySpectrum().hashCode();
    }
    hash = (37 * hash) + GAINLNA_FIELD_NUMBER;
    hash = (53 * hash) + getGainLNA();
    hash = (37 * hash) + GAINVGA_FIELD_NUMBER;
    hash = (53 * hash) + getGainVGA();
    hash = (37 * hash) + ANTENNALNA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAntennaLNA());
    hash = (37 * hash) + SPECTRUMPALETTESTART_FIELD_NUMBER;
    hash = (53 * hash) + getSpectrumPaletteStart();
    hash = (37 * hash) + SPECTRUMPALETTESIZE_FIELD_NUMBER;
    hash = (53 * hash) + getSpectrumPaletteSize();
    hash = (37 * hash) + FFTBINHZ_FIELD_NUMBER;
    hash = (53 * hash) + getFfTBinHz();
    hash = (37 * hash) + SAMPLES_FIELD_NUMBER;
    hash = (53 * hash) + getSamples();
    hash = (37 * hash) + COUNTERSIGNAL_FIELD_NUMBER;
    hash = (53 * hash) + getCounterSignal();
    hash = (37 * hash) + COUNTERLOSE_FIELD_NUMBER;
    hash = (53 * hash) + getCounterLose();
    hash = (37 * hash) + SUBRANGEREMOTE_FIELD_NUMBER;
    hash = (53 * hash) + getSubRangeRemote();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protoModels.InfoGadalkaProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.InfoGadalkaProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.InfoGadalkaProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.InfoGadalkaProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.InfoGadalkaProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.InfoGadalkaProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.InfoGadalkaProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protoModels.InfoGadalkaProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protoModels.InfoGadalkaProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protoModels.InfoGadalkaProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protoModels.InfoGadalkaProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protoModels.InfoGadalkaProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protoModels.InfoGadalkaProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code InfoGadalkaProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:InfoGadalkaProto)
      protoModels.InfoGadalkaProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoModels.WebSocketMessage.internal_static_InfoGadalkaProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoModels.WebSocketMessage.internal_static_InfoGadalkaProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoModels.InfoGadalkaProto.class, protoModels.InfoGadalkaProto.Builder.class);
    }

    // Construct using protoModels.InfoGadalkaProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      frequencySpectrum_ = null;
      if (frequencySpectrumBuilder_ != null) {
        frequencySpectrumBuilder_.dispose();
        frequencySpectrumBuilder_ = null;
      }
      gainLNA_ = 0;
      gainVGA_ = 0;
      antennaLNA_ = false;
      spectrumPaletteStart_ = 0;
      spectrumPaletteSize_ = 0;
      ffTBinHz_ = 0;
      samples_ = 0;
      counterSignal_ = 0;
      counterLose_ = 0;
      subRangeRemote_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protoModels.WebSocketMessage.internal_static_InfoGadalkaProto_descriptor;
    }

    @java.lang.Override
    public protoModels.InfoGadalkaProto getDefaultInstanceForType() {
      return protoModels.InfoGadalkaProto.getDefaultInstance();
    }

    @java.lang.Override
    public protoModels.InfoGadalkaProto build() {
      protoModels.InfoGadalkaProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protoModels.InfoGadalkaProto buildPartial() {
      protoModels.InfoGadalkaProto result = new protoModels.InfoGadalkaProto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(protoModels.InfoGadalkaProto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.frequencySpectrum_ = frequencySpectrumBuilder_ == null
            ? frequencySpectrum_
            : frequencySpectrumBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.gainLNA_ = gainLNA_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.gainVGA_ = gainVGA_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.antennaLNA_ = antennaLNA_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.spectrumPaletteStart_ = spectrumPaletteStart_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.spectrumPaletteSize_ = spectrumPaletteSize_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.ffTBinHz_ = ffTBinHz_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.samples_ = samples_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.counterSignal_ = counterSignal_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.counterLose_ = counterLose_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.subRangeRemote_ = subRangeRemote_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protoModels.InfoGadalkaProto) {
        return mergeFrom((protoModels.InfoGadalkaProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protoModels.InfoGadalkaProto other) {
      if (other == protoModels.InfoGadalkaProto.getDefaultInstance()) return this;
      if (other.hasFrequencySpectrum()) {
        mergeFrequencySpectrum(other.getFrequencySpectrum());
      }
      if (other.getGainLNA() != 0) {
        setGainLNA(other.getGainLNA());
      }
      if (other.getGainVGA() != 0) {
        setGainVGA(other.getGainVGA());
      }
      if (other.getAntennaLNA() != false) {
        setAntennaLNA(other.getAntennaLNA());
      }
      if (other.getSpectrumPaletteStart() != 0) {
        setSpectrumPaletteStart(other.getSpectrumPaletteStart());
      }
      if (other.getSpectrumPaletteSize() != 0) {
        setSpectrumPaletteSize(other.getSpectrumPaletteSize());
      }
      if (other.getFfTBinHz() != 0) {
        setFfTBinHz(other.getFfTBinHz());
      }
      if (other.getSamples() != 0) {
        setSamples(other.getSamples());
      }
      if (other.getCounterSignal() != 0) {
        setCounterSignal(other.getCounterSignal());
      }
      if (other.getCounterLose() != 0) {
        setCounterLose(other.getCounterLose());
      }
      if (other.getSubRangeRemote() != 0) {
        setSubRangeRemote(other.getSubRangeRemote());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getFrequencySpectrumFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              gainLNA_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              gainVGA_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              antennaLNA_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              spectrumPaletteStart_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              spectrumPaletteSize_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              ffTBinHz_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              samples_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              counterSignal_ = input.readInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              counterLose_ = input.readInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 88: {
              subRangeRemote_ = input.readInt32();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private protoModels.FrequencyRangeProto frequencySpectrum_;
    private com.google.protobuf.SingleFieldBuilderV3<
        protoModels.FrequencyRangeProto, protoModels.FrequencyRangeProto.Builder, protoModels.FrequencyRangeProtoOrBuilder> frequencySpectrumBuilder_;
    /**
     * <pre>
     * Диапазон частот выставленные на Гадалке
     * </pre>
     *
     * <code>.FrequencyRangeProto frequencySpectrum = 1;</code>
     * @return Whether the frequencySpectrum field is set.
     */
    public boolean hasFrequencySpectrum() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Диапазон частот выставленные на Гадалке
     * </pre>
     *
     * <code>.FrequencyRangeProto frequencySpectrum = 1;</code>
     * @return The frequencySpectrum.
     */
    public protoModels.FrequencyRangeProto getFrequencySpectrum() {
      if (frequencySpectrumBuilder_ == null) {
        return frequencySpectrum_ == null ? protoModels.FrequencyRangeProto.getDefaultInstance() : frequencySpectrum_;
      } else {
        return frequencySpectrumBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Диапазон частот выставленные на Гадалке
     * </pre>
     *
     * <code>.FrequencyRangeProto frequencySpectrum = 1;</code>
     */
    public Builder setFrequencySpectrum(protoModels.FrequencyRangeProto value) {
      if (frequencySpectrumBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        frequencySpectrum_ = value;
      } else {
        frequencySpectrumBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Диапазон частот выставленные на Гадалке
     * </pre>
     *
     * <code>.FrequencyRangeProto frequencySpectrum = 1;</code>
     */
    public Builder setFrequencySpectrum(
        protoModels.FrequencyRangeProto.Builder builderForValue) {
      if (frequencySpectrumBuilder_ == null) {
        frequencySpectrum_ = builderForValue.build();
      } else {
        frequencySpectrumBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Диапазон частот выставленные на Гадалке
     * </pre>
     *
     * <code>.FrequencyRangeProto frequencySpectrum = 1;</code>
     */
    public Builder mergeFrequencySpectrum(protoModels.FrequencyRangeProto value) {
      if (frequencySpectrumBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          frequencySpectrum_ != null &&
          frequencySpectrum_ != protoModels.FrequencyRangeProto.getDefaultInstance()) {
          getFrequencySpectrumBuilder().mergeFrom(value);
        } else {
          frequencySpectrum_ = value;
        }
      } else {
        frequencySpectrumBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Диапазон частот выставленные на Гадалке
     * </pre>
     *
     * <code>.FrequencyRangeProto frequencySpectrum = 1;</code>
     */
    public Builder clearFrequencySpectrum() {
      bitField0_ = (bitField0_ & ~0x00000001);
      frequencySpectrum_ = null;
      if (frequencySpectrumBuilder_ != null) {
        frequencySpectrumBuilder_.dispose();
        frequencySpectrumBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Диапазон частот выставленные на Гадалке
     * </pre>
     *
     * <code>.FrequencyRangeProto frequencySpectrum = 1;</code>
     */
    public protoModels.FrequencyRangeProto.Builder getFrequencySpectrumBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getFrequencySpectrumFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Диапазон частот выставленные на Гадалке
     * </pre>
     *
     * <code>.FrequencyRangeProto frequencySpectrum = 1;</code>
     */
    public protoModels.FrequencyRangeProtoOrBuilder getFrequencySpectrumOrBuilder() {
      if (frequencySpectrumBuilder_ != null) {
        return frequencySpectrumBuilder_.getMessageOrBuilder();
      } else {
        return frequencySpectrum_ == null ?
            protoModels.FrequencyRangeProto.getDefaultInstance() : frequencySpectrum_;
      }
    }
    /**
     * <pre>
     * Диапазон частот выставленные на Гадалке
     * </pre>
     *
     * <code>.FrequencyRangeProto frequencySpectrum = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        protoModels.FrequencyRangeProto, protoModels.FrequencyRangeProto.Builder, protoModels.FrequencyRangeProtoOrBuilder> 
        getFrequencySpectrumFieldBuilder() {
      if (frequencySpectrumBuilder_ == null) {
        frequencySpectrumBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            protoModels.FrequencyRangeProto, protoModels.FrequencyRangeProto.Builder, protoModels.FrequencyRangeProtoOrBuilder>(
                getFrequencySpectrum(),
                getParentForChildren(),
                isClean());
        frequencySpectrum_ = null;
      }
      return frequencySpectrumBuilder_;
    }

    private int gainLNA_ ;
    /**
     * <code>int32 gainLNA = 2;</code>
     * @return The gainLNA.
     */
    @java.lang.Override
    public int getGainLNA() {
      return gainLNA_;
    }
    /**
     * <code>int32 gainLNA = 2;</code>
     * @param value The gainLNA to set.
     * @return This builder for chaining.
     */
    public Builder setGainLNA(int value) {
      
      gainLNA_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 gainLNA = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearGainLNA() {
      bitField0_ = (bitField0_ & ~0x00000002);
      gainLNA_ = 0;
      onChanged();
      return this;
    }

    private int gainVGA_ ;
    /**
     * <code>int32 gainVGA = 3;</code>
     * @return The gainVGA.
     */
    @java.lang.Override
    public int getGainVGA() {
      return gainVGA_;
    }
    /**
     * <code>int32 gainVGA = 3;</code>
     * @param value The gainVGA to set.
     * @return This builder for chaining.
     */
    public Builder setGainVGA(int value) {
      
      gainVGA_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 gainVGA = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearGainVGA() {
      bitField0_ = (bitField0_ & ~0x00000004);
      gainVGA_ = 0;
      onChanged();
      return this;
    }

    private boolean antennaLNA_ ;
    /**
     * <code>bool antennaLNA = 4;</code>
     * @return The antennaLNA.
     */
    @java.lang.Override
    public boolean getAntennaLNA() {
      return antennaLNA_;
    }
    /**
     * <code>bool antennaLNA = 4;</code>
     * @param value The antennaLNA to set.
     * @return This builder for chaining.
     */
    public Builder setAntennaLNA(boolean value) {
      
      antennaLNA_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bool antennaLNA = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAntennaLNA() {
      bitField0_ = (bitField0_ & ~0x00000008);
      antennaLNA_ = false;
      onChanged();
      return this;
    }

    private int spectrumPaletteStart_ ;
    /**
     * <code>int32 spectrumPaletteStart = 5;</code>
     * @return The spectrumPaletteStart.
     */
    @java.lang.Override
    public int getSpectrumPaletteStart() {
      return spectrumPaletteStart_;
    }
    /**
     * <code>int32 spectrumPaletteStart = 5;</code>
     * @param value The spectrumPaletteStart to set.
     * @return This builder for chaining.
     */
    public Builder setSpectrumPaletteStart(int value) {
      
      spectrumPaletteStart_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 spectrumPaletteStart = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpectrumPaletteStart() {
      bitField0_ = (bitField0_ & ~0x00000010);
      spectrumPaletteStart_ = 0;
      onChanged();
      return this;
    }

    private int spectrumPaletteSize_ ;
    /**
     * <code>int32 spectrumPaletteSize = 6;</code>
     * @return The spectrumPaletteSize.
     */
    @java.lang.Override
    public int getSpectrumPaletteSize() {
      return spectrumPaletteSize_;
    }
    /**
     * <code>int32 spectrumPaletteSize = 6;</code>
     * @param value The spectrumPaletteSize to set.
     * @return This builder for chaining.
     */
    public Builder setSpectrumPaletteSize(int value) {
      
      spectrumPaletteSize_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 spectrumPaletteSize = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpectrumPaletteSize() {
      bitField0_ = (bitField0_ & ~0x00000020);
      spectrumPaletteSize_ = 0;
      onChanged();
      return this;
    }

    private int ffTBinHz_ ;
    /**
     * <code>int32 ffTBinHz = 7;</code>
     * @return The ffTBinHz.
     */
    @java.lang.Override
    public int getFfTBinHz() {
      return ffTBinHz_;
    }
    /**
     * <code>int32 ffTBinHz = 7;</code>
     * @param value The ffTBinHz to set.
     * @return This builder for chaining.
     */
    public Builder setFfTBinHz(int value) {
      
      ffTBinHz_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ffTBinHz = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearFfTBinHz() {
      bitField0_ = (bitField0_ & ~0x00000040);
      ffTBinHz_ = 0;
      onChanged();
      return this;
    }

    private int samples_ ;
    /**
     * <code>int32 samples = 8;</code>
     * @return The samples.
     */
    @java.lang.Override
    public int getSamples() {
      return samples_;
    }
    /**
     * <code>int32 samples = 8;</code>
     * @param value The samples to set.
     * @return This builder for chaining.
     */
    public Builder setSamples(int value) {
      
      samples_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int32 samples = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearSamples() {
      bitField0_ = (bitField0_ & ~0x00000080);
      samples_ = 0;
      onChanged();
      return this;
    }

    private int counterSignal_ ;
    /**
     * <code>int32 counterSignal = 9;</code>
     * @return The counterSignal.
     */
    @java.lang.Override
    public int getCounterSignal() {
      return counterSignal_;
    }
    /**
     * <code>int32 counterSignal = 9;</code>
     * @param value The counterSignal to set.
     * @return This builder for chaining.
     */
    public Builder setCounterSignal(int value) {
      
      counterSignal_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int32 counterSignal = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearCounterSignal() {
      bitField0_ = (bitField0_ & ~0x00000100);
      counterSignal_ = 0;
      onChanged();
      return this;
    }

    private int counterLose_ ;
    /**
     * <code>int32 counterLose = 10;</code>
     * @return The counterLose.
     */
    @java.lang.Override
    public int getCounterLose() {
      return counterLose_;
    }
    /**
     * <code>int32 counterLose = 10;</code>
     * @param value The counterLose to set.
     * @return This builder for chaining.
     */
    public Builder setCounterLose(int value) {
      
      counterLose_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>int32 counterLose = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearCounterLose() {
      bitField0_ = (bitField0_ & ~0x00000200);
      counterLose_ = 0;
      onChanged();
      return this;
    }

    private int subRangeRemote_ ;
    /**
     * <code>int32 subRangeRemote = 11;</code>
     * @return The subRangeRemote.
     */
    @java.lang.Override
    public int getSubRangeRemote() {
      return subRangeRemote_;
    }
    /**
     * <code>int32 subRangeRemote = 11;</code>
     * @param value The subRangeRemote to set.
     * @return This builder for chaining.
     */
    public Builder setSubRangeRemote(int value) {
      
      subRangeRemote_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>int32 subRangeRemote = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearSubRangeRemote() {
      bitField0_ = (bitField0_ & ~0x00000400);
      subRangeRemote_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:InfoGadalkaProto)
  }

  // @@protoc_insertion_point(class_scope:InfoGadalkaProto)
  private static final protoModels.InfoGadalkaProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protoModels.InfoGadalkaProto();
  }

  public static protoModels.InfoGadalkaProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InfoGadalkaProto>
      PARSER = new com.google.protobuf.AbstractParser<InfoGadalkaProto>() {
    @java.lang.Override
    public InfoGadalkaProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<InfoGadalkaProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InfoGadalkaProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protoModels.InfoGadalkaProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

