// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/info_chart_connect.proto

package protoModels;

/**
 * Protobuf type {@code InfoChartConnectProto}
 */
public final class InfoChartConnectProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:InfoChartConnectProto)
    InfoChartConnectProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InfoChartConnectProto.newBuilder() to construct.
  private InfoChartConnectProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InfoChartConnectProto() {
    hostName_ = "";
    serverGadalkaID_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InfoChartConnectProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protoModels.InfoChartConnect.internal_static_InfoChartConnectProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protoModels.InfoChartConnect.internal_static_InfoChartConnectProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protoModels.InfoChartConnectProto.class, protoModels.InfoChartConnectProto.Builder.class);
  }

  public static final int HOST_NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object hostName_ = "";
  /**
   * <code>string host_name = 1;</code>
   * @return The hostName.
   */
  @java.lang.Override
  public java.lang.String getHostName() {
    java.lang.Object ref = hostName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hostName_ = s;
      return s;
    }
  }
  /**
   * <code>string host_name = 1;</code>
   * @return The bytes for hostName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHostNameBytes() {
    java.lang.Object ref = hostName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hostName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PORT_WS_FIELD_NUMBER = 2;
  private int portWs_ = 0;
  /**
   * <code>int32 port_ws = 2;</code>
   * @return The portWs.
   */
  @java.lang.Override
  public int getPortWs() {
    return portWs_;
  }

  public static final int SERVERGADALKAID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object serverGadalkaID_ = "";
  /**
   * <code>string serverGadalkaID = 3;</code>
   * @return The serverGadalkaID.
   */
  @java.lang.Override
  public java.lang.String getServerGadalkaID() {
    java.lang.Object ref = serverGadalkaID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serverGadalkaID_ = s;
      return s;
    }
  }
  /**
   * <code>string serverGadalkaID = 3;</code>
   * @return The bytes for serverGadalkaID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServerGadalkaIDBytes() {
    java.lang.Object ref = serverGadalkaID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serverGadalkaID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hostName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hostName_);
    }
    if (portWs_ != 0) {
      output.writeInt32(2, portWs_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serverGadalkaID_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, serverGadalkaID_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hostName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hostName_);
    }
    if (portWs_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, portWs_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serverGadalkaID_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, serverGadalkaID_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protoModels.InfoChartConnectProto)) {
      return super.equals(obj);
    }
    protoModels.InfoChartConnectProto other = (protoModels.InfoChartConnectProto) obj;

    if (!getHostName()
        .equals(other.getHostName())) return false;
    if (getPortWs()
        != other.getPortWs()) return false;
    if (!getServerGadalkaID()
        .equals(other.getServerGadalkaID())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HOST_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getHostName().hashCode();
    hash = (37 * hash) + PORT_WS_FIELD_NUMBER;
    hash = (53 * hash) + getPortWs();
    hash = (37 * hash) + SERVERGADALKAID_FIELD_NUMBER;
    hash = (53 * hash) + getServerGadalkaID().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protoModels.InfoChartConnectProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.InfoChartConnectProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.InfoChartConnectProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.InfoChartConnectProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.InfoChartConnectProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.InfoChartConnectProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.InfoChartConnectProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protoModels.InfoChartConnectProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protoModels.InfoChartConnectProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protoModels.InfoChartConnectProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protoModels.InfoChartConnectProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protoModels.InfoChartConnectProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protoModels.InfoChartConnectProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code InfoChartConnectProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:InfoChartConnectProto)
      protoModels.InfoChartConnectProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoModels.InfoChartConnect.internal_static_InfoChartConnectProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoModels.InfoChartConnect.internal_static_InfoChartConnectProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoModels.InfoChartConnectProto.class, protoModels.InfoChartConnectProto.Builder.class);
    }

    // Construct using protoModels.InfoChartConnectProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      hostName_ = "";
      portWs_ = 0;
      serverGadalkaID_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protoModels.InfoChartConnect.internal_static_InfoChartConnectProto_descriptor;
    }

    @java.lang.Override
    public protoModels.InfoChartConnectProto getDefaultInstanceForType() {
      return protoModels.InfoChartConnectProto.getDefaultInstance();
    }

    @java.lang.Override
    public protoModels.InfoChartConnectProto build() {
      protoModels.InfoChartConnectProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protoModels.InfoChartConnectProto buildPartial() {
      protoModels.InfoChartConnectProto result = new protoModels.InfoChartConnectProto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(protoModels.InfoChartConnectProto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.hostName_ = hostName_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.portWs_ = portWs_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.serverGadalkaID_ = serverGadalkaID_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protoModels.InfoChartConnectProto) {
        return mergeFrom((protoModels.InfoChartConnectProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protoModels.InfoChartConnectProto other) {
      if (other == protoModels.InfoChartConnectProto.getDefaultInstance()) return this;
      if (!other.getHostName().isEmpty()) {
        hostName_ = other.hostName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getPortWs() != 0) {
        setPortWs(other.getPortWs());
      }
      if (!other.getServerGadalkaID().isEmpty()) {
        serverGadalkaID_ = other.serverGadalkaID_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              hostName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              portWs_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              serverGadalkaID_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object hostName_ = "";
    /**
     * <code>string host_name = 1;</code>
     * @return The hostName.
     */
    public java.lang.String getHostName() {
      java.lang.Object ref = hostName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string host_name = 1;</code>
     * @return The bytes for hostName.
     */
    public com.google.protobuf.ByteString
        getHostNameBytes() {
      java.lang.Object ref = hostName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string host_name = 1;</code>
     * @param value The hostName to set.
     * @return This builder for chaining.
     */
    public Builder setHostName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      hostName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string host_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHostName() {
      hostName_ = getDefaultInstance().getHostName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string host_name = 1;</code>
     * @param value The bytes for hostName to set.
     * @return This builder for chaining.
     */
    public Builder setHostNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      hostName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int portWs_ ;
    /**
     * <code>int32 port_ws = 2;</code>
     * @return The portWs.
     */
    @java.lang.Override
    public int getPortWs() {
      return portWs_;
    }
    /**
     * <code>int32 port_ws = 2;</code>
     * @param value The portWs to set.
     * @return This builder for chaining.
     */
    public Builder setPortWs(int value) {
      
      portWs_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 port_ws = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPortWs() {
      bitField0_ = (bitField0_ & ~0x00000002);
      portWs_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object serverGadalkaID_ = "";
    /**
     * <code>string serverGadalkaID = 3;</code>
     * @return The serverGadalkaID.
     */
    public java.lang.String getServerGadalkaID() {
      java.lang.Object ref = serverGadalkaID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverGadalkaID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string serverGadalkaID = 3;</code>
     * @return The bytes for serverGadalkaID.
     */
    public com.google.protobuf.ByteString
        getServerGadalkaIDBytes() {
      java.lang.Object ref = serverGadalkaID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverGadalkaID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string serverGadalkaID = 3;</code>
     * @param value The serverGadalkaID to set.
     * @return This builder for chaining.
     */
    public Builder setServerGadalkaID(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      serverGadalkaID_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string serverGadalkaID = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerGadalkaID() {
      serverGadalkaID_ = getDefaultInstance().getServerGadalkaID();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string serverGadalkaID = 3;</code>
     * @param value The bytes for serverGadalkaID to set.
     * @return This builder for chaining.
     */
    public Builder setServerGadalkaIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      serverGadalkaID_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:InfoChartConnectProto)
  }

  // @@protoc_insertion_point(class_scope:InfoChartConnectProto)
  private static final protoModels.InfoChartConnectProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protoModels.InfoChartConnectProto();
  }

  public static protoModels.InfoChartConnectProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InfoChartConnectProto>
      PARSER = new com.google.protobuf.AbstractParser<InfoChartConnectProto>() {
    @java.lang.Override
    public InfoChartConnectProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<InfoChartConnectProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InfoChartConnectProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protoModels.InfoChartConnectProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

