// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/web_socket_serif_line.proto

package protoModels;

public interface ListMinimalSerifLineProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListMinimalSerifLineProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
   */
  java.util.List<protoModels.MinimalSerifLineProto> 
      getMinimalSerifListList();
  /**
   * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
   */
  protoModels.MinimalSerifLineProto getMinimalSerifList(int index);
  /**
   * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
   */
  int getMinimalSerifListCount();
  /**
   * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
   */
  java.util.List<? extends protoModels.MinimalSerifLineProtoOrBuilder> 
      getMinimalSerifListOrBuilderList();
  /**
   * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
   */
  protoModels.MinimalSerifLineProtoOrBuilder getMinimalSerifListOrBuilder(
      int index);
}
