// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/web_socket_sub_diapason.proto

package protoModels;

public interface ListSelectionSubDiapasonProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListSelectionSubDiapasonProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
   */
  java.util.List<protoModels.ActionCreateSubDiapasonProto> 
      getListSelectionDiapasonList();
  /**
   * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
   */
  protoModels.ActionCreateSubDiapasonProto getListSelectionDiapason(int index);
  /**
   * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
   */
  int getListSelectionDiapasonCount();
  /**
   * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
   */
  java.util.List<? extends protoModels.ActionCreateSubDiapasonProtoOrBuilder> 
      getListSelectionDiapasonOrBuilderList();
  /**
   * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
   */
  protoModels.ActionCreateSubDiapasonProtoOrBuilder getListSelectionDiapasonOrBuilder(
      int index);
}
