// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/web_socket_serif_line.proto

package protoModels;

/**
 * Protobuf type {@code ListMinimalSerifLineProto}
 */
public final class ListMinimalSerifLineProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ListMinimalSerifLineProto)
    ListMinimalSerifLineProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListMinimalSerifLineProto.newBuilder() to construct.
  private ListMinimalSerifLineProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListMinimalSerifLineProto() {
    minimalSerifList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListMinimalSerifLineProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protoModels.WebSocketSerifLine.internal_static_ListMinimalSerifLineProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protoModels.WebSocketSerifLine.internal_static_ListMinimalSerifLineProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protoModels.ListMinimalSerifLineProto.class, protoModels.ListMinimalSerifLineProto.Builder.class);
  }

  public static final int MINIMALSERIFLIST_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<protoModels.MinimalSerifLineProto> minimalSerifList_;
  /**
   * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
   */
  @java.lang.Override
  public java.util.List<protoModels.MinimalSerifLineProto> getMinimalSerifListList() {
    return minimalSerifList_;
  }
  /**
   * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends protoModels.MinimalSerifLineProtoOrBuilder> 
      getMinimalSerifListOrBuilderList() {
    return minimalSerifList_;
  }
  /**
   * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
   */
  @java.lang.Override
  public int getMinimalSerifListCount() {
    return minimalSerifList_.size();
  }
  /**
   * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
   */
  @java.lang.Override
  public protoModels.MinimalSerifLineProto getMinimalSerifList(int index) {
    return minimalSerifList_.get(index);
  }
  /**
   * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
   */
  @java.lang.Override
  public protoModels.MinimalSerifLineProtoOrBuilder getMinimalSerifListOrBuilder(
      int index) {
    return minimalSerifList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < minimalSerifList_.size(); i++) {
      output.writeMessage(1, minimalSerifList_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < minimalSerifList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, minimalSerifList_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protoModels.ListMinimalSerifLineProto)) {
      return super.equals(obj);
    }
    protoModels.ListMinimalSerifLineProto other = (protoModels.ListMinimalSerifLineProto) obj;

    if (!getMinimalSerifListList()
        .equals(other.getMinimalSerifListList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMinimalSerifListCount() > 0) {
      hash = (37 * hash) + MINIMALSERIFLIST_FIELD_NUMBER;
      hash = (53 * hash) + getMinimalSerifListList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protoModels.ListMinimalSerifLineProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.ListMinimalSerifLineProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.ListMinimalSerifLineProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.ListMinimalSerifLineProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.ListMinimalSerifLineProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.ListMinimalSerifLineProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.ListMinimalSerifLineProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protoModels.ListMinimalSerifLineProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protoModels.ListMinimalSerifLineProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protoModels.ListMinimalSerifLineProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protoModels.ListMinimalSerifLineProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protoModels.ListMinimalSerifLineProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protoModels.ListMinimalSerifLineProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ListMinimalSerifLineProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ListMinimalSerifLineProto)
      protoModels.ListMinimalSerifLineProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoModels.WebSocketSerifLine.internal_static_ListMinimalSerifLineProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoModels.WebSocketSerifLine.internal_static_ListMinimalSerifLineProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoModels.ListMinimalSerifLineProto.class, protoModels.ListMinimalSerifLineProto.Builder.class);
    }

    // Construct using protoModels.ListMinimalSerifLineProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (minimalSerifListBuilder_ == null) {
        minimalSerifList_ = java.util.Collections.emptyList();
      } else {
        minimalSerifList_ = null;
        minimalSerifListBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protoModels.WebSocketSerifLine.internal_static_ListMinimalSerifLineProto_descriptor;
    }

    @java.lang.Override
    public protoModels.ListMinimalSerifLineProto getDefaultInstanceForType() {
      return protoModels.ListMinimalSerifLineProto.getDefaultInstance();
    }

    @java.lang.Override
    public protoModels.ListMinimalSerifLineProto build() {
      protoModels.ListMinimalSerifLineProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protoModels.ListMinimalSerifLineProto buildPartial() {
      protoModels.ListMinimalSerifLineProto result = new protoModels.ListMinimalSerifLineProto(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(protoModels.ListMinimalSerifLineProto result) {
      if (minimalSerifListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          minimalSerifList_ = java.util.Collections.unmodifiableList(minimalSerifList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.minimalSerifList_ = minimalSerifList_;
      } else {
        result.minimalSerifList_ = minimalSerifListBuilder_.build();
      }
    }

    private void buildPartial0(protoModels.ListMinimalSerifLineProto result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protoModels.ListMinimalSerifLineProto) {
        return mergeFrom((protoModels.ListMinimalSerifLineProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protoModels.ListMinimalSerifLineProto other) {
      if (other == protoModels.ListMinimalSerifLineProto.getDefaultInstance()) return this;
      if (minimalSerifListBuilder_ == null) {
        if (!other.minimalSerifList_.isEmpty()) {
          if (minimalSerifList_.isEmpty()) {
            minimalSerifList_ = other.minimalSerifList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMinimalSerifListIsMutable();
            minimalSerifList_.addAll(other.minimalSerifList_);
          }
          onChanged();
        }
      } else {
        if (!other.minimalSerifList_.isEmpty()) {
          if (minimalSerifListBuilder_.isEmpty()) {
            minimalSerifListBuilder_.dispose();
            minimalSerifListBuilder_ = null;
            minimalSerifList_ = other.minimalSerifList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            minimalSerifListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMinimalSerifListFieldBuilder() : null;
          } else {
            minimalSerifListBuilder_.addAllMessages(other.minimalSerifList_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              protoModels.MinimalSerifLineProto m =
                  input.readMessage(
                      protoModels.MinimalSerifLineProto.parser(),
                      extensionRegistry);
              if (minimalSerifListBuilder_ == null) {
                ensureMinimalSerifListIsMutable();
                minimalSerifList_.add(m);
              } else {
                minimalSerifListBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<protoModels.MinimalSerifLineProto> minimalSerifList_ =
      java.util.Collections.emptyList();
    private void ensureMinimalSerifListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        minimalSerifList_ = new java.util.ArrayList<protoModels.MinimalSerifLineProto>(minimalSerifList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protoModels.MinimalSerifLineProto, protoModels.MinimalSerifLineProto.Builder, protoModels.MinimalSerifLineProtoOrBuilder> minimalSerifListBuilder_;

    /**
     * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
     */
    public java.util.List<protoModels.MinimalSerifLineProto> getMinimalSerifListList() {
      if (minimalSerifListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(minimalSerifList_);
      } else {
        return minimalSerifListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
     */
    public int getMinimalSerifListCount() {
      if (minimalSerifListBuilder_ == null) {
        return minimalSerifList_.size();
      } else {
        return minimalSerifListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
     */
    public protoModels.MinimalSerifLineProto getMinimalSerifList(int index) {
      if (minimalSerifListBuilder_ == null) {
        return minimalSerifList_.get(index);
      } else {
        return minimalSerifListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
     */
    public Builder setMinimalSerifList(
        int index, protoModels.MinimalSerifLineProto value) {
      if (minimalSerifListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMinimalSerifListIsMutable();
        minimalSerifList_.set(index, value);
        onChanged();
      } else {
        minimalSerifListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
     */
    public Builder setMinimalSerifList(
        int index, protoModels.MinimalSerifLineProto.Builder builderForValue) {
      if (minimalSerifListBuilder_ == null) {
        ensureMinimalSerifListIsMutable();
        minimalSerifList_.set(index, builderForValue.build());
        onChanged();
      } else {
        minimalSerifListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
     */
    public Builder addMinimalSerifList(protoModels.MinimalSerifLineProto value) {
      if (minimalSerifListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMinimalSerifListIsMutable();
        minimalSerifList_.add(value);
        onChanged();
      } else {
        minimalSerifListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
     */
    public Builder addMinimalSerifList(
        int index, protoModels.MinimalSerifLineProto value) {
      if (minimalSerifListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMinimalSerifListIsMutable();
        minimalSerifList_.add(index, value);
        onChanged();
      } else {
        minimalSerifListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
     */
    public Builder addMinimalSerifList(
        protoModels.MinimalSerifLineProto.Builder builderForValue) {
      if (minimalSerifListBuilder_ == null) {
        ensureMinimalSerifListIsMutable();
        minimalSerifList_.add(builderForValue.build());
        onChanged();
      } else {
        minimalSerifListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
     */
    public Builder addMinimalSerifList(
        int index, protoModels.MinimalSerifLineProto.Builder builderForValue) {
      if (minimalSerifListBuilder_ == null) {
        ensureMinimalSerifListIsMutable();
        minimalSerifList_.add(index, builderForValue.build());
        onChanged();
      } else {
        minimalSerifListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
     */
    public Builder addAllMinimalSerifList(
        java.lang.Iterable<? extends protoModels.MinimalSerifLineProto> values) {
      if (minimalSerifListBuilder_ == null) {
        ensureMinimalSerifListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, minimalSerifList_);
        onChanged();
      } else {
        minimalSerifListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
     */
    public Builder clearMinimalSerifList() {
      if (minimalSerifListBuilder_ == null) {
        minimalSerifList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        minimalSerifListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
     */
    public Builder removeMinimalSerifList(int index) {
      if (minimalSerifListBuilder_ == null) {
        ensureMinimalSerifListIsMutable();
        minimalSerifList_.remove(index);
        onChanged();
      } else {
        minimalSerifListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
     */
    public protoModels.MinimalSerifLineProto.Builder getMinimalSerifListBuilder(
        int index) {
      return getMinimalSerifListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
     */
    public protoModels.MinimalSerifLineProtoOrBuilder getMinimalSerifListOrBuilder(
        int index) {
      if (minimalSerifListBuilder_ == null) {
        return minimalSerifList_.get(index);  } else {
        return minimalSerifListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
     */
    public java.util.List<? extends protoModels.MinimalSerifLineProtoOrBuilder> 
         getMinimalSerifListOrBuilderList() {
      if (minimalSerifListBuilder_ != null) {
        return minimalSerifListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(minimalSerifList_);
      }
    }
    /**
     * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
     */
    public protoModels.MinimalSerifLineProto.Builder addMinimalSerifListBuilder() {
      return getMinimalSerifListFieldBuilder().addBuilder(
          protoModels.MinimalSerifLineProto.getDefaultInstance());
    }
    /**
     * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
     */
    public protoModels.MinimalSerifLineProto.Builder addMinimalSerifListBuilder(
        int index) {
      return getMinimalSerifListFieldBuilder().addBuilder(
          index, protoModels.MinimalSerifLineProto.getDefaultInstance());
    }
    /**
     * <code>repeated .MinimalSerifLineProto minimalSerifList = 1;</code>
     */
    public java.util.List<protoModels.MinimalSerifLineProto.Builder> 
         getMinimalSerifListBuilderList() {
      return getMinimalSerifListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protoModels.MinimalSerifLineProto, protoModels.MinimalSerifLineProto.Builder, protoModels.MinimalSerifLineProtoOrBuilder> 
        getMinimalSerifListFieldBuilder() {
      if (minimalSerifListBuilder_ == null) {
        minimalSerifListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protoModels.MinimalSerifLineProto, protoModels.MinimalSerifLineProto.Builder, protoModels.MinimalSerifLineProtoOrBuilder>(
                minimalSerifList_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        minimalSerifList_ = null;
      }
      return minimalSerifListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ListMinimalSerifLineProto)
  }

  // @@protoc_insertion_point(class_scope:ListMinimalSerifLineProto)
  private static final protoModels.ListMinimalSerifLineProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protoModels.ListMinimalSerifLineProto();
  }

  public static protoModels.ListMinimalSerifLineProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListMinimalSerifLineProto>
      PARSER = new com.google.protobuf.AbstractParser<ListMinimalSerifLineProto>() {
    @java.lang.Override
    public ListMinimalSerifLineProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListMinimalSerifLineProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListMinimalSerifLineProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protoModels.ListMinimalSerifLineProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

