// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/web_socket_sub_diapason.proto

package protoModels;

/**
 * Protobuf type {@code ListSelectionSubDiapasonProto}
 */
public final class ListSelectionSubDiapasonProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ListSelectionSubDiapasonProto)
    ListSelectionSubDiapasonProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListSelectionSubDiapasonProto.newBuilder() to construct.
  private ListSelectionSubDiapasonProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListSelectionSubDiapasonProto() {
    listSelectionDiapason_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListSelectionSubDiapasonProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protoModels.WebSocketSubDiapason.internal_static_ListSelectionSubDiapasonProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protoModels.WebSocketSubDiapason.internal_static_ListSelectionSubDiapasonProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protoModels.ListSelectionSubDiapasonProto.class, protoModels.ListSelectionSubDiapasonProto.Builder.class);
  }

  public static final int LISTSELECTIONDIAPASON_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<protoModels.ActionCreateSubDiapasonProto> listSelectionDiapason_;
  /**
   * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
   */
  @java.lang.Override
  public java.util.List<protoModels.ActionCreateSubDiapasonProto> getListSelectionDiapasonList() {
    return listSelectionDiapason_;
  }
  /**
   * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends protoModels.ActionCreateSubDiapasonProtoOrBuilder> 
      getListSelectionDiapasonOrBuilderList() {
    return listSelectionDiapason_;
  }
  /**
   * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
   */
  @java.lang.Override
  public int getListSelectionDiapasonCount() {
    return listSelectionDiapason_.size();
  }
  /**
   * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
   */
  @java.lang.Override
  public protoModels.ActionCreateSubDiapasonProto getListSelectionDiapason(int index) {
    return listSelectionDiapason_.get(index);
  }
  /**
   * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
   */
  @java.lang.Override
  public protoModels.ActionCreateSubDiapasonProtoOrBuilder getListSelectionDiapasonOrBuilder(
      int index) {
    return listSelectionDiapason_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < listSelectionDiapason_.size(); i++) {
      output.writeMessage(1, listSelectionDiapason_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < listSelectionDiapason_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, listSelectionDiapason_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protoModels.ListSelectionSubDiapasonProto)) {
      return super.equals(obj);
    }
    protoModels.ListSelectionSubDiapasonProto other = (protoModels.ListSelectionSubDiapasonProto) obj;

    if (!getListSelectionDiapasonList()
        .equals(other.getListSelectionDiapasonList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getListSelectionDiapasonCount() > 0) {
      hash = (37 * hash) + LISTSELECTIONDIAPASON_FIELD_NUMBER;
      hash = (53 * hash) + getListSelectionDiapasonList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protoModels.ListSelectionSubDiapasonProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.ListSelectionSubDiapasonProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.ListSelectionSubDiapasonProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.ListSelectionSubDiapasonProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.ListSelectionSubDiapasonProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.ListSelectionSubDiapasonProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.ListSelectionSubDiapasonProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protoModels.ListSelectionSubDiapasonProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protoModels.ListSelectionSubDiapasonProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protoModels.ListSelectionSubDiapasonProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protoModels.ListSelectionSubDiapasonProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protoModels.ListSelectionSubDiapasonProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protoModels.ListSelectionSubDiapasonProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ListSelectionSubDiapasonProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ListSelectionSubDiapasonProto)
      protoModels.ListSelectionSubDiapasonProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoModels.WebSocketSubDiapason.internal_static_ListSelectionSubDiapasonProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoModels.WebSocketSubDiapason.internal_static_ListSelectionSubDiapasonProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoModels.ListSelectionSubDiapasonProto.class, protoModels.ListSelectionSubDiapasonProto.Builder.class);
    }

    // Construct using protoModels.ListSelectionSubDiapasonProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (listSelectionDiapasonBuilder_ == null) {
        listSelectionDiapason_ = java.util.Collections.emptyList();
      } else {
        listSelectionDiapason_ = null;
        listSelectionDiapasonBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protoModels.WebSocketSubDiapason.internal_static_ListSelectionSubDiapasonProto_descriptor;
    }

    @java.lang.Override
    public protoModels.ListSelectionSubDiapasonProto getDefaultInstanceForType() {
      return protoModels.ListSelectionSubDiapasonProto.getDefaultInstance();
    }

    @java.lang.Override
    public protoModels.ListSelectionSubDiapasonProto build() {
      protoModels.ListSelectionSubDiapasonProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protoModels.ListSelectionSubDiapasonProto buildPartial() {
      protoModels.ListSelectionSubDiapasonProto result = new protoModels.ListSelectionSubDiapasonProto(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(protoModels.ListSelectionSubDiapasonProto result) {
      if (listSelectionDiapasonBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          listSelectionDiapason_ = java.util.Collections.unmodifiableList(listSelectionDiapason_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.listSelectionDiapason_ = listSelectionDiapason_;
      } else {
        result.listSelectionDiapason_ = listSelectionDiapasonBuilder_.build();
      }
    }

    private void buildPartial0(protoModels.ListSelectionSubDiapasonProto result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protoModels.ListSelectionSubDiapasonProto) {
        return mergeFrom((protoModels.ListSelectionSubDiapasonProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protoModels.ListSelectionSubDiapasonProto other) {
      if (other == protoModels.ListSelectionSubDiapasonProto.getDefaultInstance()) return this;
      if (listSelectionDiapasonBuilder_ == null) {
        if (!other.listSelectionDiapason_.isEmpty()) {
          if (listSelectionDiapason_.isEmpty()) {
            listSelectionDiapason_ = other.listSelectionDiapason_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureListSelectionDiapasonIsMutable();
            listSelectionDiapason_.addAll(other.listSelectionDiapason_);
          }
          onChanged();
        }
      } else {
        if (!other.listSelectionDiapason_.isEmpty()) {
          if (listSelectionDiapasonBuilder_.isEmpty()) {
            listSelectionDiapasonBuilder_.dispose();
            listSelectionDiapasonBuilder_ = null;
            listSelectionDiapason_ = other.listSelectionDiapason_;
            bitField0_ = (bitField0_ & ~0x00000001);
            listSelectionDiapasonBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getListSelectionDiapasonFieldBuilder() : null;
          } else {
            listSelectionDiapasonBuilder_.addAllMessages(other.listSelectionDiapason_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              protoModels.ActionCreateSubDiapasonProto m =
                  input.readMessage(
                      protoModels.ActionCreateSubDiapasonProto.parser(),
                      extensionRegistry);
              if (listSelectionDiapasonBuilder_ == null) {
                ensureListSelectionDiapasonIsMutable();
                listSelectionDiapason_.add(m);
              } else {
                listSelectionDiapasonBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<protoModels.ActionCreateSubDiapasonProto> listSelectionDiapason_ =
      java.util.Collections.emptyList();
    private void ensureListSelectionDiapasonIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        listSelectionDiapason_ = new java.util.ArrayList<protoModels.ActionCreateSubDiapasonProto>(listSelectionDiapason_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        protoModels.ActionCreateSubDiapasonProto, protoModels.ActionCreateSubDiapasonProto.Builder, protoModels.ActionCreateSubDiapasonProtoOrBuilder> listSelectionDiapasonBuilder_;

    /**
     * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
     */
    public java.util.List<protoModels.ActionCreateSubDiapasonProto> getListSelectionDiapasonList() {
      if (listSelectionDiapasonBuilder_ == null) {
        return java.util.Collections.unmodifiableList(listSelectionDiapason_);
      } else {
        return listSelectionDiapasonBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
     */
    public int getListSelectionDiapasonCount() {
      if (listSelectionDiapasonBuilder_ == null) {
        return listSelectionDiapason_.size();
      } else {
        return listSelectionDiapasonBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
     */
    public protoModels.ActionCreateSubDiapasonProto getListSelectionDiapason(int index) {
      if (listSelectionDiapasonBuilder_ == null) {
        return listSelectionDiapason_.get(index);
      } else {
        return listSelectionDiapasonBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
     */
    public Builder setListSelectionDiapason(
        int index, protoModels.ActionCreateSubDiapasonProto value) {
      if (listSelectionDiapasonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListSelectionDiapasonIsMutable();
        listSelectionDiapason_.set(index, value);
        onChanged();
      } else {
        listSelectionDiapasonBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
     */
    public Builder setListSelectionDiapason(
        int index, protoModels.ActionCreateSubDiapasonProto.Builder builderForValue) {
      if (listSelectionDiapasonBuilder_ == null) {
        ensureListSelectionDiapasonIsMutable();
        listSelectionDiapason_.set(index, builderForValue.build());
        onChanged();
      } else {
        listSelectionDiapasonBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
     */
    public Builder addListSelectionDiapason(protoModels.ActionCreateSubDiapasonProto value) {
      if (listSelectionDiapasonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListSelectionDiapasonIsMutable();
        listSelectionDiapason_.add(value);
        onChanged();
      } else {
        listSelectionDiapasonBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
     */
    public Builder addListSelectionDiapason(
        int index, protoModels.ActionCreateSubDiapasonProto value) {
      if (listSelectionDiapasonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureListSelectionDiapasonIsMutable();
        listSelectionDiapason_.add(index, value);
        onChanged();
      } else {
        listSelectionDiapasonBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
     */
    public Builder addListSelectionDiapason(
        protoModels.ActionCreateSubDiapasonProto.Builder builderForValue) {
      if (listSelectionDiapasonBuilder_ == null) {
        ensureListSelectionDiapasonIsMutable();
        listSelectionDiapason_.add(builderForValue.build());
        onChanged();
      } else {
        listSelectionDiapasonBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
     */
    public Builder addListSelectionDiapason(
        int index, protoModels.ActionCreateSubDiapasonProto.Builder builderForValue) {
      if (listSelectionDiapasonBuilder_ == null) {
        ensureListSelectionDiapasonIsMutable();
        listSelectionDiapason_.add(index, builderForValue.build());
        onChanged();
      } else {
        listSelectionDiapasonBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
     */
    public Builder addAllListSelectionDiapason(
        java.lang.Iterable<? extends protoModels.ActionCreateSubDiapasonProto> values) {
      if (listSelectionDiapasonBuilder_ == null) {
        ensureListSelectionDiapasonIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, listSelectionDiapason_);
        onChanged();
      } else {
        listSelectionDiapasonBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
     */
    public Builder clearListSelectionDiapason() {
      if (listSelectionDiapasonBuilder_ == null) {
        listSelectionDiapason_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        listSelectionDiapasonBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
     */
    public Builder removeListSelectionDiapason(int index) {
      if (listSelectionDiapasonBuilder_ == null) {
        ensureListSelectionDiapasonIsMutable();
        listSelectionDiapason_.remove(index);
        onChanged();
      } else {
        listSelectionDiapasonBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
     */
    public protoModels.ActionCreateSubDiapasonProto.Builder getListSelectionDiapasonBuilder(
        int index) {
      return getListSelectionDiapasonFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
     */
    public protoModels.ActionCreateSubDiapasonProtoOrBuilder getListSelectionDiapasonOrBuilder(
        int index) {
      if (listSelectionDiapasonBuilder_ == null) {
        return listSelectionDiapason_.get(index);  } else {
        return listSelectionDiapasonBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
     */
    public java.util.List<? extends protoModels.ActionCreateSubDiapasonProtoOrBuilder> 
         getListSelectionDiapasonOrBuilderList() {
      if (listSelectionDiapasonBuilder_ != null) {
        return listSelectionDiapasonBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(listSelectionDiapason_);
      }
    }
    /**
     * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
     */
    public protoModels.ActionCreateSubDiapasonProto.Builder addListSelectionDiapasonBuilder() {
      return getListSelectionDiapasonFieldBuilder().addBuilder(
          protoModels.ActionCreateSubDiapasonProto.getDefaultInstance());
    }
    /**
     * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
     */
    public protoModels.ActionCreateSubDiapasonProto.Builder addListSelectionDiapasonBuilder(
        int index) {
      return getListSelectionDiapasonFieldBuilder().addBuilder(
          index, protoModels.ActionCreateSubDiapasonProto.getDefaultInstance());
    }
    /**
     * <code>repeated .ActionCreateSubDiapasonProto listSelectionDiapason = 1;</code>
     */
    public java.util.List<protoModels.ActionCreateSubDiapasonProto.Builder> 
         getListSelectionDiapasonBuilderList() {
      return getListSelectionDiapasonFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        protoModels.ActionCreateSubDiapasonProto, protoModels.ActionCreateSubDiapasonProto.Builder, protoModels.ActionCreateSubDiapasonProtoOrBuilder> 
        getListSelectionDiapasonFieldBuilder() {
      if (listSelectionDiapasonBuilder_ == null) {
        listSelectionDiapasonBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            protoModels.ActionCreateSubDiapasonProto, protoModels.ActionCreateSubDiapasonProto.Builder, protoModels.ActionCreateSubDiapasonProtoOrBuilder>(
                listSelectionDiapason_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        listSelectionDiapason_ = null;
      }
      return listSelectionDiapasonBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ListSelectionSubDiapasonProto)
  }

  // @@protoc_insertion_point(class_scope:ListSelectionSubDiapasonProto)
  private static final protoModels.ListSelectionSubDiapasonProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protoModels.ListSelectionSubDiapasonProto();
  }

  public static protoModels.ListSelectionSubDiapasonProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListSelectionSubDiapasonProto>
      PARSER = new com.google.protobuf.AbstractParser<ListSelectionSubDiapasonProto>() {
    @java.lang.Override
    public ListSelectionSubDiapasonProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListSelectionSubDiapasonProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListSelectionSubDiapasonProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protoModels.ListSelectionSubDiapasonProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

