// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/web_socket_serif_line.proto

package protoModels;

/**
 * Protobuf type {@code MinimalSerifLineProto}
 */
public final class MinimalSerifLineProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MinimalSerifLineProto)
    MinimalSerifLineProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MinimalSerifLineProto.newBuilder() to construct.
  private MinimalSerifLineProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MinimalSerifLineProto() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MinimalSerifLineProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protoModels.WebSocketSerifLine.internal_static_MinimalSerifLineProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protoModels.WebSocketSerifLine.internal_static_MinimalSerifLineProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protoModels.MinimalSerifLineProto.class, protoModels.MinimalSerifLineProto.Builder.class);
  }

  public static final int FREQUENCYSTART_FIELD_NUMBER = 1;
  private float frequencyStart_ = 0F;
  /**
   * <code>float frequencyStart = 1;</code>
   * @return The frequencyStart.
   */
  @java.lang.Override
  public float getFrequencyStart() {
    return frequencyStart_;
  }

  public static final int FREQUENCYEND_FIELD_NUMBER = 2;
  private float frequencyEnd_ = 0F;
  /**
   * <code>float frequencyEnd = 2;</code>
   * @return The frequencyEnd.
   */
  @java.lang.Override
  public float getFrequencyEnd() {
    return frequencyEnd_;
  }

  public static final int SERIFLINE_FIELD_NUMBER = 3;
  private float serifLine_ = 0F;
  /**
   * <code>float serifLine = 3;</code>
   * @return The serifLine.
   */
  @java.lang.Override
  public float getSerifLine() {
    return serifLine_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Float.floatToRawIntBits(frequencyStart_) != 0) {
      output.writeFloat(1, frequencyStart_);
    }
    if (java.lang.Float.floatToRawIntBits(frequencyEnd_) != 0) {
      output.writeFloat(2, frequencyEnd_);
    }
    if (java.lang.Float.floatToRawIntBits(serifLine_) != 0) {
      output.writeFloat(3, serifLine_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Float.floatToRawIntBits(frequencyStart_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, frequencyStart_);
    }
    if (java.lang.Float.floatToRawIntBits(frequencyEnd_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, frequencyEnd_);
    }
    if (java.lang.Float.floatToRawIntBits(serifLine_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, serifLine_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protoModels.MinimalSerifLineProto)) {
      return super.equals(obj);
    }
    protoModels.MinimalSerifLineProto other = (protoModels.MinimalSerifLineProto) obj;

    if (java.lang.Float.floatToIntBits(getFrequencyStart())
        != java.lang.Float.floatToIntBits(
            other.getFrequencyStart())) return false;
    if (java.lang.Float.floatToIntBits(getFrequencyEnd())
        != java.lang.Float.floatToIntBits(
            other.getFrequencyEnd())) return false;
    if (java.lang.Float.floatToIntBits(getSerifLine())
        != java.lang.Float.floatToIntBits(
            other.getSerifLine())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FREQUENCYSTART_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getFrequencyStart());
    hash = (37 * hash) + FREQUENCYEND_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getFrequencyEnd());
    hash = (37 * hash) + SERIFLINE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getSerifLine());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protoModels.MinimalSerifLineProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.MinimalSerifLineProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.MinimalSerifLineProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.MinimalSerifLineProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.MinimalSerifLineProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.MinimalSerifLineProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.MinimalSerifLineProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protoModels.MinimalSerifLineProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protoModels.MinimalSerifLineProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protoModels.MinimalSerifLineProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protoModels.MinimalSerifLineProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protoModels.MinimalSerifLineProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protoModels.MinimalSerifLineProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MinimalSerifLineProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MinimalSerifLineProto)
      protoModels.MinimalSerifLineProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoModels.WebSocketSerifLine.internal_static_MinimalSerifLineProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoModels.WebSocketSerifLine.internal_static_MinimalSerifLineProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoModels.MinimalSerifLineProto.class, protoModels.MinimalSerifLineProto.Builder.class);
    }

    // Construct using protoModels.MinimalSerifLineProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      frequencyStart_ = 0F;
      frequencyEnd_ = 0F;
      serifLine_ = 0F;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protoModels.WebSocketSerifLine.internal_static_MinimalSerifLineProto_descriptor;
    }

    @java.lang.Override
    public protoModels.MinimalSerifLineProto getDefaultInstanceForType() {
      return protoModels.MinimalSerifLineProto.getDefaultInstance();
    }

    @java.lang.Override
    public protoModels.MinimalSerifLineProto build() {
      protoModels.MinimalSerifLineProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protoModels.MinimalSerifLineProto buildPartial() {
      protoModels.MinimalSerifLineProto result = new protoModels.MinimalSerifLineProto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(protoModels.MinimalSerifLineProto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.frequencyStart_ = frequencyStart_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.frequencyEnd_ = frequencyEnd_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.serifLine_ = serifLine_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protoModels.MinimalSerifLineProto) {
        return mergeFrom((protoModels.MinimalSerifLineProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protoModels.MinimalSerifLineProto other) {
      if (other == protoModels.MinimalSerifLineProto.getDefaultInstance()) return this;
      if (other.getFrequencyStart() != 0F) {
        setFrequencyStart(other.getFrequencyStart());
      }
      if (other.getFrequencyEnd() != 0F) {
        setFrequencyEnd(other.getFrequencyEnd());
      }
      if (other.getSerifLine() != 0F) {
        setSerifLine(other.getSerifLine());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              frequencyStart_ = input.readFloat();
              bitField0_ |= 0x00000001;
              break;
            } // case 13
            case 21: {
              frequencyEnd_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            case 29: {
              serifLine_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private float frequencyStart_ ;
    /**
     * <code>float frequencyStart = 1;</code>
     * @return The frequencyStart.
     */
    @java.lang.Override
    public float getFrequencyStart() {
      return frequencyStart_;
    }
    /**
     * <code>float frequencyStart = 1;</code>
     * @param value The frequencyStart to set.
     * @return This builder for chaining.
     */
    public Builder setFrequencyStart(float value) {
      
      frequencyStart_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>float frequencyStart = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrequencyStart() {
      bitField0_ = (bitField0_ & ~0x00000001);
      frequencyStart_ = 0F;
      onChanged();
      return this;
    }

    private float frequencyEnd_ ;
    /**
     * <code>float frequencyEnd = 2;</code>
     * @return The frequencyEnd.
     */
    @java.lang.Override
    public float getFrequencyEnd() {
      return frequencyEnd_;
    }
    /**
     * <code>float frequencyEnd = 2;</code>
     * @param value The frequencyEnd to set.
     * @return This builder for chaining.
     */
    public Builder setFrequencyEnd(float value) {
      
      frequencyEnd_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>float frequencyEnd = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrequencyEnd() {
      bitField0_ = (bitField0_ & ~0x00000002);
      frequencyEnd_ = 0F;
      onChanged();
      return this;
    }

    private float serifLine_ ;
    /**
     * <code>float serifLine = 3;</code>
     * @return The serifLine.
     */
    @java.lang.Override
    public float getSerifLine() {
      return serifLine_;
    }
    /**
     * <code>float serifLine = 3;</code>
     * @param value The serifLine to set.
     * @return This builder for chaining.
     */
    public Builder setSerifLine(float value) {
      
      serifLine_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>float serifLine = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSerifLine() {
      bitField0_ = (bitField0_ & ~0x00000004);
      serifLine_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MinimalSerifLineProto)
  }

  // @@protoc_insertion_point(class_scope:MinimalSerifLineProto)
  private static final protoModels.MinimalSerifLineProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protoModels.MinimalSerifLineProto();
  }

  public static protoModels.MinimalSerifLineProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MinimalSerifLineProto>
      PARSER = new com.google.protobuf.AbstractParser<MinimalSerifLineProto>() {
    @java.lang.Override
    public MinimalSerifLineProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MinimalSerifLineProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MinimalSerifLineProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protoModels.MinimalSerifLineProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

