// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/web_socket_serif_line.proto

package protoModels;

public interface MinimalSerifLineProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MinimalSerifLineProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float frequencyStart = 1;</code>
   * @return The frequencyStart.
   */
  float getFrequencyStart();

  /**
   * <code>float frequencyEnd = 2;</code>
   * @return The frequencyEnd.
   */
  float getFrequencyEnd();

  /**
   * <code>float serifLine = 3;</code>
   * @return The serifLine.
   */
  float getSerifLine();
}
