// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/web_socket_message.proto

package protoModels;

/**
 * Protobuf enum {@code SerifTypeProto}
 */
public enum SerifTypeProto
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Default value
   * </pre>
   *
   * <code>MANUAL = 0;</code>
   */
  MANUAL(0),
  /**
   * <code>AUTO_3 = 1;</code>
   */
  AUTO_3(1),
  /**
   * <code>AUTO_4 = 2;</code>
   */
  AUTO_4(2),
  /**
   * <code>AUTO_5 = 3;</code>
   */
  AUTO_5(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * Default value
   * </pre>
   *
   * <code>MANUAL = 0;</code>
   */
  public static final int MANUAL_VALUE = 0;
  /**
   * <code>AUTO_3 = 1;</code>
   */
  public static final int AUTO_3_VALUE = 1;
  /**
   * <code>AUTO_4 = 2;</code>
   */
  public static final int AUTO_4_VALUE = 2;
  /**
   * <code>AUTO_5 = 3;</code>
   */
  public static final int AUTO_5_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SerifTypeProto valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static SerifTypeProto forNumber(int value) {
    switch (value) {
      case 0: return MANUAL;
      case 1: return AUTO_3;
      case 2: return AUTO_4;
      case 3: return AUTO_5;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SerifTypeProto>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SerifTypeProto> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SerifTypeProto>() {
          public SerifTypeProto findValueByNumber(int number) {
            return SerifTypeProto.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return protoModels.WebSocketMessage.getDescriptor().getEnumTypes().get(0);
  }

  private static final SerifTypeProto[] VALUES = values();

  public static SerifTypeProto valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SerifTypeProto(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:SerifTypeProto)
}

