// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/serif_gadalka.proto

package protoModels;

public interface SerifGadalkaProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SerifGadalkaProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Азимут
   * </pre>
   *
   * <code>int32 azimuth = 1;</code>
   * @return The azimuth.
   */
  int getAzimuth();

  /**
   * <pre>
   * Диапазон частот
   * </pre>
   *
   * <code>.FrequencyRangeProto frequencyRange = 2;</code>
   * @return Whether the frequencyRange field is set.
   */
  boolean hasFrequencyRange();
  /**
   * <pre>
   * Диапазон частот
   * </pre>
   *
   * <code>.FrequencyRangeProto frequencyRange = 2;</code>
   * @return The frequencyRange.
   */
  protoModels.FrequencyRangeProto getFrequencyRange();
  /**
   * <pre>
   * Диапазон частот
   * </pre>
   *
   * <code>.FrequencyRangeProto frequencyRange = 2;</code>
   */
  protoModels.FrequencyRangeProtoOrBuilder getFrequencyRangeOrBuilder();

  /**
   * <code>float dbm = 3;</code>
   * @return The dbm.
   */
  float getDbm();
}
