// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/serif_gadalka.proto

package protoModels;

/**
 * Protobuf type {@code SerifGadalkaProto}
 */
public final class SerifGadalkaProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SerifGadalkaProto)
    SerifGadalkaProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SerifGadalkaProto.newBuilder() to construct.
  private SerifGadalkaProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SerifGadalkaProto() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SerifGadalkaProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protoModels.SerifGadalka.internal_static_SerifGadalkaProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protoModels.SerifGadalka.internal_static_SerifGadalkaProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protoModels.SerifGadalkaProto.class, protoModels.SerifGadalkaProto.Builder.class);
  }

  public static final int AZIMUTH_FIELD_NUMBER = 1;
  private int azimuth_ = 0;
  /**
   * <pre>
   * Азимут
   * </pre>
   *
   * <code>int32 azimuth = 1;</code>
   * @return The azimuth.
   */
  @java.lang.Override
  public int getAzimuth() {
    return azimuth_;
  }

  public static final int FREQUENCYRANGE_FIELD_NUMBER = 2;
  private protoModels.FrequencyRangeProto frequencyRange_;
  /**
   * <pre>
   * Диапазон частот
   * </pre>
   *
   * <code>.FrequencyRangeProto frequencyRange = 2;</code>
   * @return Whether the frequencyRange field is set.
   */
  @java.lang.Override
  public boolean hasFrequencyRange() {
    return frequencyRange_ != null;
  }
  /**
   * <pre>
   * Диапазон частот
   * </pre>
   *
   * <code>.FrequencyRangeProto frequencyRange = 2;</code>
   * @return The frequencyRange.
   */
  @java.lang.Override
  public protoModels.FrequencyRangeProto getFrequencyRange() {
    return frequencyRange_ == null ? protoModels.FrequencyRangeProto.getDefaultInstance() : frequencyRange_;
  }
  /**
   * <pre>
   * Диапазон частот
   * </pre>
   *
   * <code>.FrequencyRangeProto frequencyRange = 2;</code>
   */
  @java.lang.Override
  public protoModels.FrequencyRangeProtoOrBuilder getFrequencyRangeOrBuilder() {
    return frequencyRange_ == null ? protoModels.FrequencyRangeProto.getDefaultInstance() : frequencyRange_;
  }

  public static final int DBM_FIELD_NUMBER = 3;
  private float dbm_ = 0F;
  /**
   * <code>float dbm = 3;</code>
   * @return The dbm.
   */
  @java.lang.Override
  public float getDbm() {
    return dbm_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (azimuth_ != 0) {
      output.writeInt32(1, azimuth_);
    }
    if (frequencyRange_ != null) {
      output.writeMessage(2, getFrequencyRange());
    }
    if (java.lang.Float.floatToRawIntBits(dbm_) != 0) {
      output.writeFloat(3, dbm_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (azimuth_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, azimuth_);
    }
    if (frequencyRange_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getFrequencyRange());
    }
    if (java.lang.Float.floatToRawIntBits(dbm_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, dbm_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protoModels.SerifGadalkaProto)) {
      return super.equals(obj);
    }
    protoModels.SerifGadalkaProto other = (protoModels.SerifGadalkaProto) obj;

    if (getAzimuth()
        != other.getAzimuth()) return false;
    if (hasFrequencyRange() != other.hasFrequencyRange()) return false;
    if (hasFrequencyRange()) {
      if (!getFrequencyRange()
          .equals(other.getFrequencyRange())) return false;
    }
    if (java.lang.Float.floatToIntBits(getDbm())
        != java.lang.Float.floatToIntBits(
            other.getDbm())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AZIMUTH_FIELD_NUMBER;
    hash = (53 * hash) + getAzimuth();
    if (hasFrequencyRange()) {
      hash = (37 * hash) + FREQUENCYRANGE_FIELD_NUMBER;
      hash = (53 * hash) + getFrequencyRange().hashCode();
    }
    hash = (37 * hash) + DBM_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getDbm());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protoModels.SerifGadalkaProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.SerifGadalkaProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.SerifGadalkaProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.SerifGadalkaProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.SerifGadalkaProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.SerifGadalkaProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.SerifGadalkaProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protoModels.SerifGadalkaProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protoModels.SerifGadalkaProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protoModels.SerifGadalkaProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protoModels.SerifGadalkaProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protoModels.SerifGadalkaProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protoModels.SerifGadalkaProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SerifGadalkaProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SerifGadalkaProto)
      protoModels.SerifGadalkaProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoModels.SerifGadalka.internal_static_SerifGadalkaProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoModels.SerifGadalka.internal_static_SerifGadalkaProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoModels.SerifGadalkaProto.class, protoModels.SerifGadalkaProto.Builder.class);
    }

    // Construct using protoModels.SerifGadalkaProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      azimuth_ = 0;
      frequencyRange_ = null;
      if (frequencyRangeBuilder_ != null) {
        frequencyRangeBuilder_.dispose();
        frequencyRangeBuilder_ = null;
      }
      dbm_ = 0F;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protoModels.SerifGadalka.internal_static_SerifGadalkaProto_descriptor;
    }

    @java.lang.Override
    public protoModels.SerifGadalkaProto getDefaultInstanceForType() {
      return protoModels.SerifGadalkaProto.getDefaultInstance();
    }

    @java.lang.Override
    public protoModels.SerifGadalkaProto build() {
      protoModels.SerifGadalkaProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protoModels.SerifGadalkaProto buildPartial() {
      protoModels.SerifGadalkaProto result = new protoModels.SerifGadalkaProto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(protoModels.SerifGadalkaProto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.azimuth_ = azimuth_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.frequencyRange_ = frequencyRangeBuilder_ == null
            ? frequencyRange_
            : frequencyRangeBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.dbm_ = dbm_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protoModels.SerifGadalkaProto) {
        return mergeFrom((protoModels.SerifGadalkaProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protoModels.SerifGadalkaProto other) {
      if (other == protoModels.SerifGadalkaProto.getDefaultInstance()) return this;
      if (other.getAzimuth() != 0) {
        setAzimuth(other.getAzimuth());
      }
      if (other.hasFrequencyRange()) {
        mergeFrequencyRange(other.getFrequencyRange());
      }
      if (other.getDbm() != 0F) {
        setDbm(other.getDbm());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              azimuth_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getFrequencyRangeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 29: {
              dbm_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int azimuth_ ;
    /**
     * <pre>
     * Азимут
     * </pre>
     *
     * <code>int32 azimuth = 1;</code>
     * @return The azimuth.
     */
    @java.lang.Override
    public int getAzimuth() {
      return azimuth_;
    }
    /**
     * <pre>
     * Азимут
     * </pre>
     *
     * <code>int32 azimuth = 1;</code>
     * @param value The azimuth to set.
     * @return This builder for chaining.
     */
    public Builder setAzimuth(int value) {
      
      azimuth_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Азимут
     * </pre>
     *
     * <code>int32 azimuth = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAzimuth() {
      bitField0_ = (bitField0_ & ~0x00000001);
      azimuth_ = 0;
      onChanged();
      return this;
    }

    private protoModels.FrequencyRangeProto frequencyRange_;
    private com.google.protobuf.SingleFieldBuilderV3<
        protoModels.FrequencyRangeProto, protoModels.FrequencyRangeProto.Builder, protoModels.FrequencyRangeProtoOrBuilder> frequencyRangeBuilder_;
    /**
     * <pre>
     * Диапазон частот
     * </pre>
     *
     * <code>.FrequencyRangeProto frequencyRange = 2;</code>
     * @return Whether the frequencyRange field is set.
     */
    public boolean hasFrequencyRange() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Диапазон частот
     * </pre>
     *
     * <code>.FrequencyRangeProto frequencyRange = 2;</code>
     * @return The frequencyRange.
     */
    public protoModels.FrequencyRangeProto getFrequencyRange() {
      if (frequencyRangeBuilder_ == null) {
        return frequencyRange_ == null ? protoModels.FrequencyRangeProto.getDefaultInstance() : frequencyRange_;
      } else {
        return frequencyRangeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Диапазон частот
     * </pre>
     *
     * <code>.FrequencyRangeProto frequencyRange = 2;</code>
     */
    public Builder setFrequencyRange(protoModels.FrequencyRangeProto value) {
      if (frequencyRangeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        frequencyRange_ = value;
      } else {
        frequencyRangeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Диапазон частот
     * </pre>
     *
     * <code>.FrequencyRangeProto frequencyRange = 2;</code>
     */
    public Builder setFrequencyRange(
        protoModels.FrequencyRangeProto.Builder builderForValue) {
      if (frequencyRangeBuilder_ == null) {
        frequencyRange_ = builderForValue.build();
      } else {
        frequencyRangeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Диапазон частот
     * </pre>
     *
     * <code>.FrequencyRangeProto frequencyRange = 2;</code>
     */
    public Builder mergeFrequencyRange(protoModels.FrequencyRangeProto value) {
      if (frequencyRangeBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          frequencyRange_ != null &&
          frequencyRange_ != protoModels.FrequencyRangeProto.getDefaultInstance()) {
          getFrequencyRangeBuilder().mergeFrom(value);
        } else {
          frequencyRange_ = value;
        }
      } else {
        frequencyRangeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Диапазон частот
     * </pre>
     *
     * <code>.FrequencyRangeProto frequencyRange = 2;</code>
     */
    public Builder clearFrequencyRange() {
      bitField0_ = (bitField0_ & ~0x00000002);
      frequencyRange_ = null;
      if (frequencyRangeBuilder_ != null) {
        frequencyRangeBuilder_.dispose();
        frequencyRangeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Диапазон частот
     * </pre>
     *
     * <code>.FrequencyRangeProto frequencyRange = 2;</code>
     */
    public protoModels.FrequencyRangeProto.Builder getFrequencyRangeBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getFrequencyRangeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Диапазон частот
     * </pre>
     *
     * <code>.FrequencyRangeProto frequencyRange = 2;</code>
     */
    public protoModels.FrequencyRangeProtoOrBuilder getFrequencyRangeOrBuilder() {
      if (frequencyRangeBuilder_ != null) {
        return frequencyRangeBuilder_.getMessageOrBuilder();
      } else {
        return frequencyRange_ == null ?
            protoModels.FrequencyRangeProto.getDefaultInstance() : frequencyRange_;
      }
    }
    /**
     * <pre>
     * Диапазон частот
     * </pre>
     *
     * <code>.FrequencyRangeProto frequencyRange = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        protoModels.FrequencyRangeProto, protoModels.FrequencyRangeProto.Builder, protoModels.FrequencyRangeProtoOrBuilder> 
        getFrequencyRangeFieldBuilder() {
      if (frequencyRangeBuilder_ == null) {
        frequencyRangeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            protoModels.FrequencyRangeProto, protoModels.FrequencyRangeProto.Builder, protoModels.FrequencyRangeProtoOrBuilder>(
                getFrequencyRange(),
                getParentForChildren(),
                isClean());
        frequencyRange_ = null;
      }
      return frequencyRangeBuilder_;
    }

    private float dbm_ ;
    /**
     * <code>float dbm = 3;</code>
     * @return The dbm.
     */
    @java.lang.Override
    public float getDbm() {
      return dbm_;
    }
    /**
     * <code>float dbm = 3;</code>
     * @param value The dbm to set.
     * @return This builder for chaining.
     */
    public Builder setDbm(float value) {
      
      dbm_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>float dbm = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDbm() {
      bitField0_ = (bitField0_ & ~0x00000004);
      dbm_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SerifGadalkaProto)
  }

  // @@protoc_insertion_point(class_scope:SerifGadalkaProto)
  private static final protoModels.SerifGadalkaProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protoModels.SerifGadalkaProto();
  }

  public static protoModels.SerifGadalkaProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SerifGadalkaProto>
      PARSER = new com.google.protobuf.AbstractParser<SerifGadalkaProto>() {
    @java.lang.Override
    public SerifGadalkaProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SerifGadalkaProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SerifGadalkaProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protoModels.SerifGadalkaProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

