// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/serif_gadalka.proto

package protoModels;

public final class SerifGadalka {
  private SerifGadalka() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SerifGadalkaProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SerifGadalkaProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"src-java/proto/serif_gadalka.proto\032$sr" +
      "c-java/proto/frequency_range.proto\"_\n\021Se" +
      "rifGadalkaProto\022\017\n\007azimuth\030\001 \001(\005\022,\n\016freq" +
      "uencyRange\030\002 \001(\0132\024.FrequencyRangeProto\022\013" +
      "\n\003dbm\030\003 \001(\002B\017\n\013protoModelsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protoModels.FrequencyRange.getDescriptor(),
        });
    internal_static_SerifGadalkaProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SerifGadalkaProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SerifGadalkaProto_descriptor,
        new java.lang.String[] { "Azimuth", "FrequencyRange", "Dbm", });
    protoModels.FrequencyRange.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
