// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/web_socket_sub_diapason.proto

package protoModels;

/**
 * Protobuf type {@code SubDiapasonActionProto}
 */
public final class SubDiapasonActionProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SubDiapasonActionProto)
    SubDiapasonActionProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SubDiapasonActionProto.newBuilder() to construct.
  private SubDiapasonActionProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SubDiapasonActionProto() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SubDiapasonActionProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protoModels.WebSocketSubDiapason.internal_static_SubDiapasonActionProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protoModels.WebSocketSubDiapason.internal_static_SubDiapasonActionProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protoModels.SubDiapasonActionProto.class, protoModels.SubDiapasonActionProto.Builder.class);
  }

  private int taskSubDiapasonCase_ = 0;
  private java.lang.Object taskSubDiapason_;
  public enum TaskSubDiapasonCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    CREATE(1),
    DELETE(2),
    DELETEALL(3),
    TASKSUBDIAPASON_NOT_SET(0);
    private final int value;
    private TaskSubDiapasonCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TaskSubDiapasonCase valueOf(int value) {
      return forNumber(value);
    }

    public static TaskSubDiapasonCase forNumber(int value) {
      switch (value) {
        case 1: return CREATE;
        case 2: return DELETE;
        case 3: return DELETEALL;
        case 0: return TASKSUBDIAPASON_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public TaskSubDiapasonCase
  getTaskSubDiapasonCase() {
    return TaskSubDiapasonCase.forNumber(
        taskSubDiapasonCase_);
  }

  public static final int CREATE_FIELD_NUMBER = 1;
  /**
   * <code>.ActionCreateSubDiapasonProto create = 1;</code>
   * @return Whether the create field is set.
   */
  @java.lang.Override
  public boolean hasCreate() {
    return taskSubDiapasonCase_ == 1;
  }
  /**
   * <code>.ActionCreateSubDiapasonProto create = 1;</code>
   * @return The create.
   */
  @java.lang.Override
  public protoModels.ActionCreateSubDiapasonProto getCreate() {
    if (taskSubDiapasonCase_ == 1) {
       return (protoModels.ActionCreateSubDiapasonProto) taskSubDiapason_;
    }
    return protoModels.ActionCreateSubDiapasonProto.getDefaultInstance();
  }
  /**
   * <code>.ActionCreateSubDiapasonProto create = 1;</code>
   */
  @java.lang.Override
  public protoModels.ActionCreateSubDiapasonProtoOrBuilder getCreateOrBuilder() {
    if (taskSubDiapasonCase_ == 1) {
       return (protoModels.ActionCreateSubDiapasonProto) taskSubDiapason_;
    }
    return protoModels.ActionCreateSubDiapasonProto.getDefaultInstance();
  }

  public static final int DELETE_FIELD_NUMBER = 2;
  /**
   * <code>.ActionDeleteSubDiapasonProto delete = 2;</code>
   * @return Whether the delete field is set.
   */
  @java.lang.Override
  public boolean hasDelete() {
    return taskSubDiapasonCase_ == 2;
  }
  /**
   * <code>.ActionDeleteSubDiapasonProto delete = 2;</code>
   * @return The delete.
   */
  @java.lang.Override
  public protoModels.ActionDeleteSubDiapasonProto getDelete() {
    if (taskSubDiapasonCase_ == 2) {
       return (protoModels.ActionDeleteSubDiapasonProto) taskSubDiapason_;
    }
    return protoModels.ActionDeleteSubDiapasonProto.getDefaultInstance();
  }
  /**
   * <code>.ActionDeleteSubDiapasonProto delete = 2;</code>
   */
  @java.lang.Override
  public protoModels.ActionDeleteSubDiapasonProtoOrBuilder getDeleteOrBuilder() {
    if (taskSubDiapasonCase_ == 2) {
       return (protoModels.ActionDeleteSubDiapasonProto) taskSubDiapason_;
    }
    return protoModels.ActionDeleteSubDiapasonProto.getDefaultInstance();
  }

  public static final int DELETEALL_FIELD_NUMBER = 3;
  /**
   * <code>.ActionDeleteAllSubDiapasonProto deleteAll = 3;</code>
   * @return Whether the deleteAll field is set.
   */
  @java.lang.Override
  public boolean hasDeleteAll() {
    return taskSubDiapasonCase_ == 3;
  }
  /**
   * <code>.ActionDeleteAllSubDiapasonProto deleteAll = 3;</code>
   * @return The deleteAll.
   */
  @java.lang.Override
  public protoModels.ActionDeleteAllSubDiapasonProto getDeleteAll() {
    if (taskSubDiapasonCase_ == 3) {
       return (protoModels.ActionDeleteAllSubDiapasonProto) taskSubDiapason_;
    }
    return protoModels.ActionDeleteAllSubDiapasonProto.getDefaultInstance();
  }
  /**
   * <code>.ActionDeleteAllSubDiapasonProto deleteAll = 3;</code>
   */
  @java.lang.Override
  public protoModels.ActionDeleteAllSubDiapasonProtoOrBuilder getDeleteAllOrBuilder() {
    if (taskSubDiapasonCase_ == 3) {
       return (protoModels.ActionDeleteAllSubDiapasonProto) taskSubDiapason_;
    }
    return protoModels.ActionDeleteAllSubDiapasonProto.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (taskSubDiapasonCase_ == 1) {
      output.writeMessage(1, (protoModels.ActionCreateSubDiapasonProto) taskSubDiapason_);
    }
    if (taskSubDiapasonCase_ == 2) {
      output.writeMessage(2, (protoModels.ActionDeleteSubDiapasonProto) taskSubDiapason_);
    }
    if (taskSubDiapasonCase_ == 3) {
      output.writeMessage(3, (protoModels.ActionDeleteAllSubDiapasonProto) taskSubDiapason_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (taskSubDiapasonCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (protoModels.ActionCreateSubDiapasonProto) taskSubDiapason_);
    }
    if (taskSubDiapasonCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (protoModels.ActionDeleteSubDiapasonProto) taskSubDiapason_);
    }
    if (taskSubDiapasonCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (protoModels.ActionDeleteAllSubDiapasonProto) taskSubDiapason_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protoModels.SubDiapasonActionProto)) {
      return super.equals(obj);
    }
    protoModels.SubDiapasonActionProto other = (protoModels.SubDiapasonActionProto) obj;

    if (!getTaskSubDiapasonCase().equals(other.getTaskSubDiapasonCase())) return false;
    switch (taskSubDiapasonCase_) {
      case 1:
        if (!getCreate()
            .equals(other.getCreate())) return false;
        break;
      case 2:
        if (!getDelete()
            .equals(other.getDelete())) return false;
        break;
      case 3:
        if (!getDeleteAll()
            .equals(other.getDeleteAll())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (taskSubDiapasonCase_) {
      case 1:
        hash = (37 * hash) + CREATE_FIELD_NUMBER;
        hash = (53 * hash) + getCreate().hashCode();
        break;
      case 2:
        hash = (37 * hash) + DELETE_FIELD_NUMBER;
        hash = (53 * hash) + getDelete().hashCode();
        break;
      case 3:
        hash = (37 * hash) + DELETEALL_FIELD_NUMBER;
        hash = (53 * hash) + getDeleteAll().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protoModels.SubDiapasonActionProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.SubDiapasonActionProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.SubDiapasonActionProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.SubDiapasonActionProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.SubDiapasonActionProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.SubDiapasonActionProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.SubDiapasonActionProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protoModels.SubDiapasonActionProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protoModels.SubDiapasonActionProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protoModels.SubDiapasonActionProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protoModels.SubDiapasonActionProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protoModels.SubDiapasonActionProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protoModels.SubDiapasonActionProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SubDiapasonActionProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SubDiapasonActionProto)
      protoModels.SubDiapasonActionProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoModels.WebSocketSubDiapason.internal_static_SubDiapasonActionProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoModels.WebSocketSubDiapason.internal_static_SubDiapasonActionProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoModels.SubDiapasonActionProto.class, protoModels.SubDiapasonActionProto.Builder.class);
    }

    // Construct using protoModels.SubDiapasonActionProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (createBuilder_ != null) {
        createBuilder_.clear();
      }
      if (deleteBuilder_ != null) {
        deleteBuilder_.clear();
      }
      if (deleteAllBuilder_ != null) {
        deleteAllBuilder_.clear();
      }
      taskSubDiapasonCase_ = 0;
      taskSubDiapason_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protoModels.WebSocketSubDiapason.internal_static_SubDiapasonActionProto_descriptor;
    }

    @java.lang.Override
    public protoModels.SubDiapasonActionProto getDefaultInstanceForType() {
      return protoModels.SubDiapasonActionProto.getDefaultInstance();
    }

    @java.lang.Override
    public protoModels.SubDiapasonActionProto build() {
      protoModels.SubDiapasonActionProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protoModels.SubDiapasonActionProto buildPartial() {
      protoModels.SubDiapasonActionProto result = new protoModels.SubDiapasonActionProto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(protoModels.SubDiapasonActionProto result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(protoModels.SubDiapasonActionProto result) {
      result.taskSubDiapasonCase_ = taskSubDiapasonCase_;
      result.taskSubDiapason_ = this.taskSubDiapason_;
      if (taskSubDiapasonCase_ == 1 &&
          createBuilder_ != null) {
        result.taskSubDiapason_ = createBuilder_.build();
      }
      if (taskSubDiapasonCase_ == 2 &&
          deleteBuilder_ != null) {
        result.taskSubDiapason_ = deleteBuilder_.build();
      }
      if (taskSubDiapasonCase_ == 3 &&
          deleteAllBuilder_ != null) {
        result.taskSubDiapason_ = deleteAllBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protoModels.SubDiapasonActionProto) {
        return mergeFrom((protoModels.SubDiapasonActionProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protoModels.SubDiapasonActionProto other) {
      if (other == protoModels.SubDiapasonActionProto.getDefaultInstance()) return this;
      switch (other.getTaskSubDiapasonCase()) {
        case CREATE: {
          mergeCreate(other.getCreate());
          break;
        }
        case DELETE: {
          mergeDelete(other.getDelete());
          break;
        }
        case DELETEALL: {
          mergeDeleteAll(other.getDeleteAll());
          break;
        }
        case TASKSUBDIAPASON_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getCreateFieldBuilder().getBuilder(),
                  extensionRegistry);
              taskSubDiapasonCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getDeleteFieldBuilder().getBuilder(),
                  extensionRegistry);
              taskSubDiapasonCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getDeleteAllFieldBuilder().getBuilder(),
                  extensionRegistry);
              taskSubDiapasonCase_ = 3;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int taskSubDiapasonCase_ = 0;
    private java.lang.Object taskSubDiapason_;
    public TaskSubDiapasonCase
        getTaskSubDiapasonCase() {
      return TaskSubDiapasonCase.forNumber(
          taskSubDiapasonCase_);
    }

    public Builder clearTaskSubDiapason() {
      taskSubDiapasonCase_ = 0;
      taskSubDiapason_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        protoModels.ActionCreateSubDiapasonProto, protoModels.ActionCreateSubDiapasonProto.Builder, protoModels.ActionCreateSubDiapasonProtoOrBuilder> createBuilder_;
    /**
     * <code>.ActionCreateSubDiapasonProto create = 1;</code>
     * @return Whether the create field is set.
     */
    @java.lang.Override
    public boolean hasCreate() {
      return taskSubDiapasonCase_ == 1;
    }
    /**
     * <code>.ActionCreateSubDiapasonProto create = 1;</code>
     * @return The create.
     */
    @java.lang.Override
    public protoModels.ActionCreateSubDiapasonProto getCreate() {
      if (createBuilder_ == null) {
        if (taskSubDiapasonCase_ == 1) {
          return (protoModels.ActionCreateSubDiapasonProto) taskSubDiapason_;
        }
        return protoModels.ActionCreateSubDiapasonProto.getDefaultInstance();
      } else {
        if (taskSubDiapasonCase_ == 1) {
          return createBuilder_.getMessage();
        }
        return protoModels.ActionCreateSubDiapasonProto.getDefaultInstance();
      }
    }
    /**
     * <code>.ActionCreateSubDiapasonProto create = 1;</code>
     */
    public Builder setCreate(protoModels.ActionCreateSubDiapasonProto value) {
      if (createBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        taskSubDiapason_ = value;
        onChanged();
      } else {
        createBuilder_.setMessage(value);
      }
      taskSubDiapasonCase_ = 1;
      return this;
    }
    /**
     * <code>.ActionCreateSubDiapasonProto create = 1;</code>
     */
    public Builder setCreate(
        protoModels.ActionCreateSubDiapasonProto.Builder builderForValue) {
      if (createBuilder_ == null) {
        taskSubDiapason_ = builderForValue.build();
        onChanged();
      } else {
        createBuilder_.setMessage(builderForValue.build());
      }
      taskSubDiapasonCase_ = 1;
      return this;
    }
    /**
     * <code>.ActionCreateSubDiapasonProto create = 1;</code>
     */
    public Builder mergeCreate(protoModels.ActionCreateSubDiapasonProto value) {
      if (createBuilder_ == null) {
        if (taskSubDiapasonCase_ == 1 &&
            taskSubDiapason_ != protoModels.ActionCreateSubDiapasonProto.getDefaultInstance()) {
          taskSubDiapason_ = protoModels.ActionCreateSubDiapasonProto.newBuilder((protoModels.ActionCreateSubDiapasonProto) taskSubDiapason_)
              .mergeFrom(value).buildPartial();
        } else {
          taskSubDiapason_ = value;
        }
        onChanged();
      } else {
        if (taskSubDiapasonCase_ == 1) {
          createBuilder_.mergeFrom(value);
        } else {
          createBuilder_.setMessage(value);
        }
      }
      taskSubDiapasonCase_ = 1;
      return this;
    }
    /**
     * <code>.ActionCreateSubDiapasonProto create = 1;</code>
     */
    public Builder clearCreate() {
      if (createBuilder_ == null) {
        if (taskSubDiapasonCase_ == 1) {
          taskSubDiapasonCase_ = 0;
          taskSubDiapason_ = null;
          onChanged();
        }
      } else {
        if (taskSubDiapasonCase_ == 1) {
          taskSubDiapasonCase_ = 0;
          taskSubDiapason_ = null;
        }
        createBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ActionCreateSubDiapasonProto create = 1;</code>
     */
    public protoModels.ActionCreateSubDiapasonProto.Builder getCreateBuilder() {
      return getCreateFieldBuilder().getBuilder();
    }
    /**
     * <code>.ActionCreateSubDiapasonProto create = 1;</code>
     */
    @java.lang.Override
    public protoModels.ActionCreateSubDiapasonProtoOrBuilder getCreateOrBuilder() {
      if ((taskSubDiapasonCase_ == 1) && (createBuilder_ != null)) {
        return createBuilder_.getMessageOrBuilder();
      } else {
        if (taskSubDiapasonCase_ == 1) {
          return (protoModels.ActionCreateSubDiapasonProto) taskSubDiapason_;
        }
        return protoModels.ActionCreateSubDiapasonProto.getDefaultInstance();
      }
    }
    /**
     * <code>.ActionCreateSubDiapasonProto create = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        protoModels.ActionCreateSubDiapasonProto, protoModels.ActionCreateSubDiapasonProto.Builder, protoModels.ActionCreateSubDiapasonProtoOrBuilder> 
        getCreateFieldBuilder() {
      if (createBuilder_ == null) {
        if (!(taskSubDiapasonCase_ == 1)) {
          taskSubDiapason_ = protoModels.ActionCreateSubDiapasonProto.getDefaultInstance();
        }
        createBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            protoModels.ActionCreateSubDiapasonProto, protoModels.ActionCreateSubDiapasonProto.Builder, protoModels.ActionCreateSubDiapasonProtoOrBuilder>(
                (protoModels.ActionCreateSubDiapasonProto) taskSubDiapason_,
                getParentForChildren(),
                isClean());
        taskSubDiapason_ = null;
      }
      taskSubDiapasonCase_ = 1;
      onChanged();
      return createBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        protoModels.ActionDeleteSubDiapasonProto, protoModels.ActionDeleteSubDiapasonProto.Builder, protoModels.ActionDeleteSubDiapasonProtoOrBuilder> deleteBuilder_;
    /**
     * <code>.ActionDeleteSubDiapasonProto delete = 2;</code>
     * @return Whether the delete field is set.
     */
    @java.lang.Override
    public boolean hasDelete() {
      return taskSubDiapasonCase_ == 2;
    }
    /**
     * <code>.ActionDeleteSubDiapasonProto delete = 2;</code>
     * @return The delete.
     */
    @java.lang.Override
    public protoModels.ActionDeleteSubDiapasonProto getDelete() {
      if (deleteBuilder_ == null) {
        if (taskSubDiapasonCase_ == 2) {
          return (protoModels.ActionDeleteSubDiapasonProto) taskSubDiapason_;
        }
        return protoModels.ActionDeleteSubDiapasonProto.getDefaultInstance();
      } else {
        if (taskSubDiapasonCase_ == 2) {
          return deleteBuilder_.getMessage();
        }
        return protoModels.ActionDeleteSubDiapasonProto.getDefaultInstance();
      }
    }
    /**
     * <code>.ActionDeleteSubDiapasonProto delete = 2;</code>
     */
    public Builder setDelete(protoModels.ActionDeleteSubDiapasonProto value) {
      if (deleteBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        taskSubDiapason_ = value;
        onChanged();
      } else {
        deleteBuilder_.setMessage(value);
      }
      taskSubDiapasonCase_ = 2;
      return this;
    }
    /**
     * <code>.ActionDeleteSubDiapasonProto delete = 2;</code>
     */
    public Builder setDelete(
        protoModels.ActionDeleteSubDiapasonProto.Builder builderForValue) {
      if (deleteBuilder_ == null) {
        taskSubDiapason_ = builderForValue.build();
        onChanged();
      } else {
        deleteBuilder_.setMessage(builderForValue.build());
      }
      taskSubDiapasonCase_ = 2;
      return this;
    }
    /**
     * <code>.ActionDeleteSubDiapasonProto delete = 2;</code>
     */
    public Builder mergeDelete(protoModels.ActionDeleteSubDiapasonProto value) {
      if (deleteBuilder_ == null) {
        if (taskSubDiapasonCase_ == 2 &&
            taskSubDiapason_ != protoModels.ActionDeleteSubDiapasonProto.getDefaultInstance()) {
          taskSubDiapason_ = protoModels.ActionDeleteSubDiapasonProto.newBuilder((protoModels.ActionDeleteSubDiapasonProto) taskSubDiapason_)
              .mergeFrom(value).buildPartial();
        } else {
          taskSubDiapason_ = value;
        }
        onChanged();
      } else {
        if (taskSubDiapasonCase_ == 2) {
          deleteBuilder_.mergeFrom(value);
        } else {
          deleteBuilder_.setMessage(value);
        }
      }
      taskSubDiapasonCase_ = 2;
      return this;
    }
    /**
     * <code>.ActionDeleteSubDiapasonProto delete = 2;</code>
     */
    public Builder clearDelete() {
      if (deleteBuilder_ == null) {
        if (taskSubDiapasonCase_ == 2) {
          taskSubDiapasonCase_ = 0;
          taskSubDiapason_ = null;
          onChanged();
        }
      } else {
        if (taskSubDiapasonCase_ == 2) {
          taskSubDiapasonCase_ = 0;
          taskSubDiapason_ = null;
        }
        deleteBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ActionDeleteSubDiapasonProto delete = 2;</code>
     */
    public protoModels.ActionDeleteSubDiapasonProto.Builder getDeleteBuilder() {
      return getDeleteFieldBuilder().getBuilder();
    }
    /**
     * <code>.ActionDeleteSubDiapasonProto delete = 2;</code>
     */
    @java.lang.Override
    public protoModels.ActionDeleteSubDiapasonProtoOrBuilder getDeleteOrBuilder() {
      if ((taskSubDiapasonCase_ == 2) && (deleteBuilder_ != null)) {
        return deleteBuilder_.getMessageOrBuilder();
      } else {
        if (taskSubDiapasonCase_ == 2) {
          return (protoModels.ActionDeleteSubDiapasonProto) taskSubDiapason_;
        }
        return protoModels.ActionDeleteSubDiapasonProto.getDefaultInstance();
      }
    }
    /**
     * <code>.ActionDeleteSubDiapasonProto delete = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        protoModels.ActionDeleteSubDiapasonProto, protoModels.ActionDeleteSubDiapasonProto.Builder, protoModels.ActionDeleteSubDiapasonProtoOrBuilder> 
        getDeleteFieldBuilder() {
      if (deleteBuilder_ == null) {
        if (!(taskSubDiapasonCase_ == 2)) {
          taskSubDiapason_ = protoModels.ActionDeleteSubDiapasonProto.getDefaultInstance();
        }
        deleteBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            protoModels.ActionDeleteSubDiapasonProto, protoModels.ActionDeleteSubDiapasonProto.Builder, protoModels.ActionDeleteSubDiapasonProtoOrBuilder>(
                (protoModels.ActionDeleteSubDiapasonProto) taskSubDiapason_,
                getParentForChildren(),
                isClean());
        taskSubDiapason_ = null;
      }
      taskSubDiapasonCase_ = 2;
      onChanged();
      return deleteBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        protoModels.ActionDeleteAllSubDiapasonProto, protoModels.ActionDeleteAllSubDiapasonProto.Builder, protoModels.ActionDeleteAllSubDiapasonProtoOrBuilder> deleteAllBuilder_;
    /**
     * <code>.ActionDeleteAllSubDiapasonProto deleteAll = 3;</code>
     * @return Whether the deleteAll field is set.
     */
    @java.lang.Override
    public boolean hasDeleteAll() {
      return taskSubDiapasonCase_ == 3;
    }
    /**
     * <code>.ActionDeleteAllSubDiapasonProto deleteAll = 3;</code>
     * @return The deleteAll.
     */
    @java.lang.Override
    public protoModels.ActionDeleteAllSubDiapasonProto getDeleteAll() {
      if (deleteAllBuilder_ == null) {
        if (taskSubDiapasonCase_ == 3) {
          return (protoModels.ActionDeleteAllSubDiapasonProto) taskSubDiapason_;
        }
        return protoModels.ActionDeleteAllSubDiapasonProto.getDefaultInstance();
      } else {
        if (taskSubDiapasonCase_ == 3) {
          return deleteAllBuilder_.getMessage();
        }
        return protoModels.ActionDeleteAllSubDiapasonProto.getDefaultInstance();
      }
    }
    /**
     * <code>.ActionDeleteAllSubDiapasonProto deleteAll = 3;</code>
     */
    public Builder setDeleteAll(protoModels.ActionDeleteAllSubDiapasonProto value) {
      if (deleteAllBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        taskSubDiapason_ = value;
        onChanged();
      } else {
        deleteAllBuilder_.setMessage(value);
      }
      taskSubDiapasonCase_ = 3;
      return this;
    }
    /**
     * <code>.ActionDeleteAllSubDiapasonProto deleteAll = 3;</code>
     */
    public Builder setDeleteAll(
        protoModels.ActionDeleteAllSubDiapasonProto.Builder builderForValue) {
      if (deleteAllBuilder_ == null) {
        taskSubDiapason_ = builderForValue.build();
        onChanged();
      } else {
        deleteAllBuilder_.setMessage(builderForValue.build());
      }
      taskSubDiapasonCase_ = 3;
      return this;
    }
    /**
     * <code>.ActionDeleteAllSubDiapasonProto deleteAll = 3;</code>
     */
    public Builder mergeDeleteAll(protoModels.ActionDeleteAllSubDiapasonProto value) {
      if (deleteAllBuilder_ == null) {
        if (taskSubDiapasonCase_ == 3 &&
            taskSubDiapason_ != protoModels.ActionDeleteAllSubDiapasonProto.getDefaultInstance()) {
          taskSubDiapason_ = protoModels.ActionDeleteAllSubDiapasonProto.newBuilder((protoModels.ActionDeleteAllSubDiapasonProto) taskSubDiapason_)
              .mergeFrom(value).buildPartial();
        } else {
          taskSubDiapason_ = value;
        }
        onChanged();
      } else {
        if (taskSubDiapasonCase_ == 3) {
          deleteAllBuilder_.mergeFrom(value);
        } else {
          deleteAllBuilder_.setMessage(value);
        }
      }
      taskSubDiapasonCase_ = 3;
      return this;
    }
    /**
     * <code>.ActionDeleteAllSubDiapasonProto deleteAll = 3;</code>
     */
    public Builder clearDeleteAll() {
      if (deleteAllBuilder_ == null) {
        if (taskSubDiapasonCase_ == 3) {
          taskSubDiapasonCase_ = 0;
          taskSubDiapason_ = null;
          onChanged();
        }
      } else {
        if (taskSubDiapasonCase_ == 3) {
          taskSubDiapasonCase_ = 0;
          taskSubDiapason_ = null;
        }
        deleteAllBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ActionDeleteAllSubDiapasonProto deleteAll = 3;</code>
     */
    public protoModels.ActionDeleteAllSubDiapasonProto.Builder getDeleteAllBuilder() {
      return getDeleteAllFieldBuilder().getBuilder();
    }
    /**
     * <code>.ActionDeleteAllSubDiapasonProto deleteAll = 3;</code>
     */
    @java.lang.Override
    public protoModels.ActionDeleteAllSubDiapasonProtoOrBuilder getDeleteAllOrBuilder() {
      if ((taskSubDiapasonCase_ == 3) && (deleteAllBuilder_ != null)) {
        return deleteAllBuilder_.getMessageOrBuilder();
      } else {
        if (taskSubDiapasonCase_ == 3) {
          return (protoModels.ActionDeleteAllSubDiapasonProto) taskSubDiapason_;
        }
        return protoModels.ActionDeleteAllSubDiapasonProto.getDefaultInstance();
      }
    }
    /**
     * <code>.ActionDeleteAllSubDiapasonProto deleteAll = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        protoModels.ActionDeleteAllSubDiapasonProto, protoModels.ActionDeleteAllSubDiapasonProto.Builder, protoModels.ActionDeleteAllSubDiapasonProtoOrBuilder> 
        getDeleteAllFieldBuilder() {
      if (deleteAllBuilder_ == null) {
        if (!(taskSubDiapasonCase_ == 3)) {
          taskSubDiapason_ = protoModels.ActionDeleteAllSubDiapasonProto.getDefaultInstance();
        }
        deleteAllBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            protoModels.ActionDeleteAllSubDiapasonProto, protoModels.ActionDeleteAllSubDiapasonProto.Builder, protoModels.ActionDeleteAllSubDiapasonProtoOrBuilder>(
                (protoModels.ActionDeleteAllSubDiapasonProto) taskSubDiapason_,
                getParentForChildren(),
                isClean());
        taskSubDiapason_ = null;
      }
      taskSubDiapasonCase_ = 3;
      onChanged();
      return deleteAllBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SubDiapasonActionProto)
  }

  // @@protoc_insertion_point(class_scope:SubDiapasonActionProto)
  private static final protoModels.SubDiapasonActionProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protoModels.SubDiapasonActionProto();
  }

  public static protoModels.SubDiapasonActionProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubDiapasonActionProto>
      PARSER = new com.google.protobuf.AbstractParser<SubDiapasonActionProto>() {
    @java.lang.Override
    public SubDiapasonActionProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SubDiapasonActionProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SubDiapasonActionProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protoModels.SubDiapasonActionProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

