// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/web_socket_sub_diapason.proto

package protoModels;

public interface SubDiapasonActionProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SubDiapasonActionProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ActionCreateSubDiapasonProto create = 1;</code>
   * @return Whether the create field is set.
   */
  boolean hasCreate();
  /**
   * <code>.ActionCreateSubDiapasonProto create = 1;</code>
   * @return The create.
   */
  protoModels.ActionCreateSubDiapasonProto getCreate();
  /**
   * <code>.ActionCreateSubDiapasonProto create = 1;</code>
   */
  protoModels.ActionCreateSubDiapasonProtoOrBuilder getCreateOrBuilder();

  /**
   * <code>.ActionDeleteSubDiapasonProto delete = 2;</code>
   * @return Whether the delete field is set.
   */
  boolean hasDelete();
  /**
   * <code>.ActionDeleteSubDiapasonProto delete = 2;</code>
   * @return The delete.
   */
  protoModels.ActionDeleteSubDiapasonProto getDelete();
  /**
   * <code>.ActionDeleteSubDiapasonProto delete = 2;</code>
   */
  protoModels.ActionDeleteSubDiapasonProtoOrBuilder getDeleteOrBuilder();

  /**
   * <code>.ActionDeleteAllSubDiapasonProto deleteAll = 3;</code>
   * @return Whether the deleteAll field is set.
   */
  boolean hasDeleteAll();
  /**
   * <code>.ActionDeleteAllSubDiapasonProto deleteAll = 3;</code>
   * @return The deleteAll.
   */
  protoModels.ActionDeleteAllSubDiapasonProto getDeleteAll();
  /**
   * <code>.ActionDeleteAllSubDiapasonProto deleteAll = 3;</code>
   */
  protoModels.ActionDeleteAllSubDiapasonProtoOrBuilder getDeleteAllOrBuilder();

  public protoModels.SubDiapasonActionProto.TaskSubDiapasonCase getTaskSubDiapasonCase();
}
