// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/web_socket_sub_diapason.proto

package protoModels;

/**
 * Protobuf enum {@code TypeSubDiapasonProto}
 */
public enum TypeSubDiapasonProto
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>FIND = 0;</code>
   */
  FIND(0),
  /**
   * <code>CUT = 1;</code>
   */
  CUT(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>FIND = 0;</code>
   */
  public static final int FIND_VALUE = 0;
  /**
   * <code>CUT = 1;</code>
   */
  public static final int CUT_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TypeSubDiapasonProto valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TypeSubDiapasonProto forNumber(int value) {
    switch (value) {
      case 0: return FIND;
      case 1: return CUT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TypeSubDiapasonProto>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TypeSubDiapasonProto> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TypeSubDiapasonProto>() {
          public TypeSubDiapasonProto findValueByNumber(int number) {
            return TypeSubDiapasonProto.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return protoModels.WebSocketSubDiapason.getDescriptor().getEnumTypes().get(0);
  }

  private static final TypeSubDiapasonProto[] VALUES = values();

  public static TypeSubDiapasonProto valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TypeSubDiapasonProto(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:TypeSubDiapasonProto)
}

