// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/analizator_api.proto

package protoModels;

public interface WebSocketResponseProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WebSocketResponseProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuidTask = 1;</code>
   * @return The uuidTask.
   */
  java.lang.String getUuidTask();
  /**
   * <code>string uuidTask = 1;</code>
   * @return The bytes for uuidTask.
   */
  com.google.protobuf.ByteString
      getUuidTaskBytes();

  /**
   * <code>.WebSocketStatusMessageProto status = 2;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.WebSocketStatusMessageProto status = 2;</code>
   * @return The status.
   */
  protoModels.WebSocketStatusMessageProto getStatus();
}
