// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/web_socket_serif_line.proto

package protoModels;

public final class WebSocketSerifLine {
  private WebSocketSerifLine() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListMinimalSerifLineProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListMinimalSerifLineProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MinimalSerifLineProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MinimalSerifLineProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*src-java/proto/web_socket_serif_line.p" +
      "roto\"M\n\031ListMinimalSerifLineProto\0220\n\020min" +
      "imalSerifList\030\001 \003(\0132\026.MinimalSerifLinePr" +
      "oto\"X\n\025MinimalSerifLineProto\022\026\n\016frequenc" +
      "yStart\030\001 \001(\002\022\024\n\014frequencyEnd\030\002 \001(\002\022\021\n\tse" +
      "rifLine\030\003 \001(\002B\017\n\013protoModelsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ListMinimalSerifLineProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ListMinimalSerifLineProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListMinimalSerifLineProto_descriptor,
        new java.lang.String[] { "MinimalSerifList", });
    internal_static_MinimalSerifLineProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MinimalSerifLineProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MinimalSerifLineProto_descriptor,
        new java.lang.String[] { "FrequencyStart", "FrequencyEnd", "SerifLine", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
