// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/analizator_api.proto

package protoModels;

public interface WebSocketGetAllInfoProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WebSocketGetAllInfoProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuidTask = 1;</code>
   * @return The uuidTask.
   */
  java.lang.String getUuidTask();
  /**
   * <code>string uuidTask = 1;</code>
   * @return The bytes for uuidTask.
   */
  com.google.protobuf.ByteString
      getUuidTaskBytes();
}
