// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/analizator_api.proto

package protoModels;

/**
 * Protobuf enum {@code WebSocketStatusMessageProto}
 */
public enum WebSocketStatusMessageProto
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ACCEPTED = 0;</code>
   */
  ACCEPTED(0),
  /**
   * <code>NOT_ACCEPTED = 1;</code>
   */
  NOT_ACCEPTED(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ACCEPTED = 0;</code>
   */
  public static final int ACCEPTED_VALUE = 0;
  /**
   * <code>NOT_ACCEPTED = 1;</code>
   */
  public static final int NOT_ACCEPTED_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static WebSocketStatusMessageProto valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static WebSocketStatusMessageProto forNumber(int value) {
    switch (value) {
      case 0: return ACCEPTED;
      case 1: return NOT_ACCEPTED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<WebSocketStatusMessageProto>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      WebSocketStatusMessageProto> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<WebSocketStatusMessageProto>() {
          public WebSocketStatusMessageProto findValueByNumber(int number) {
            return WebSocketStatusMessageProto.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return protoModels.AnalizatorApi.getDescriptor().getEnumTypes().get(0);
  }

  private static final WebSocketStatusMessageProto[] VALUES = values();

  public static WebSocketStatusMessageProto valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private WebSocketStatusMessageProto(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:WebSocketStatusMessageProto)
}

