// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/analizator_api.proto

package protoModels;

public interface WebSocketSpectrumProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WebSocketSpectrumProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes data = 1;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>int32 azimuth = 2;</code>
   * @return The azimuth.
   */
  int getAzimuth();
}
