// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/web_socket_message.proto

package protoModels;

public interface WebSocketMessageTaskProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WebSocketMessageTaskProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.InfoGadalkaProto infoGadalka = 1;</code>
   * @return Whether the infoGadalka field is set.
   */
  boolean hasInfoGadalka();
  /**
   * <code>.InfoGadalkaProto infoGadalka = 1;</code>
   * @return The infoGadalka.
   */
  protoModels.InfoGadalkaProto getInfoGadalka();
  /**
   * <code>.InfoGadalkaProto infoGadalka = 1;</code>
   */
  protoModels.InfoGadalkaProtoOrBuilder getInfoGadalkaOrBuilder();

  /**
   * <code>.SerifTypeProto serifTypeAlgorithm = 2;</code>
   * @return Whether the serifTypeAlgorithm field is set.
   */
  boolean hasSerifTypeAlgorithm();
  /**
   * <code>.SerifTypeProto serifTypeAlgorithm = 2;</code>
   * @return The enum numeric value on the wire for serifTypeAlgorithm.
   */
  int getSerifTypeAlgorithmValue();
  /**
   * <code>.SerifTypeProto serifTypeAlgorithm = 2;</code>
   * @return The serifTypeAlgorithm.
   */
  protoModels.SerifTypeProto getSerifTypeAlgorithm();

  /**
   * <code>.SubDiapasonActionProto subAction = 3;</code>
   * @return Whether the subAction field is set.
   */
  boolean hasSubAction();
  /**
   * <code>.SubDiapasonActionProto subAction = 3;</code>
   * @return The subAction.
   */
  protoModels.SubDiapasonActionProto getSubAction();
  /**
   * <code>.SubDiapasonActionProto subAction = 3;</code>
   */
  protoModels.SubDiapasonActionProtoOrBuilder getSubActionOrBuilder();

  /**
   * <code>bytes minimalSerifLine = 4;</code>
   * @return Whether the minimalSerifLine field is set.
   */
  boolean hasMinimalSerifLine();
  /**
   * <code>bytes minimalSerifLine = 4;</code>
   * @return The minimalSerifLine.
   */
  com.google.protobuf.ByteString getMinimalSerifLine();

  /**
   * <code>.FullInfoApiMessageProto fullInfo = 5;</code>
   * @return Whether the fullInfo field is set.
   */
  boolean hasFullInfo();
  /**
   * <code>.FullInfoApiMessageProto fullInfo = 5;</code>
   * @return The fullInfo.
   */
  protoModels.FullInfoApiMessageProto getFullInfo();
  /**
   * <code>.FullInfoApiMessageProto fullInfo = 5;</code>
   */
  protoModels.FullInfoApiMessageProtoOrBuilder getFullInfoOrBuilder();

  /**
   * <code>.HideWaterfallMessageProto hideWaterfall = 6;</code>
   * @return Whether the hideWaterfall field is set.
   */
  boolean hasHideWaterfall();
  /**
   * <code>.HideWaterfallMessageProto hideWaterfall = 6;</code>
   * @return The hideWaterfall.
   */
  protoModels.HideWaterfallMessageProto getHideWaterfall();
  /**
   * <code>.HideWaterfallMessageProto hideWaterfall = 6;</code>
   */
  protoModels.HideWaterfallMessageProtoOrBuilder getHideWaterfallOrBuilder();

  public protoModels.WebSocketMessageTaskProto.MessageCase getMessageCase();
}
