// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/web_socket_message.proto

package protoModels;

public final class WebSocketMessage {
  private WebSocketMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WebSocketMessageTaskProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WebSocketMessageTaskProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InfoGadalkaProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InfoGadalkaProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FullInfoApiMessageProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FullInfoApiMessageProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HideWaterfallMessageProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HideWaterfallMessageProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'src-java/proto/web_socket_message.prot" +
      "o\032,src-java/proto/web_socket_sub_diapaso" +
      "n.proto\032$src-java/proto/frequency_range." +
      "proto\"\254\002\n\031WebSocketMessageTaskProto\022(\n\013i" +
      "nfoGadalka\030\001 \001(\0132\021.InfoGadalkaProtoH\000\022-\n" +
      "\022serifTypeAlgorithm\030\002 \001(\0162\017.SerifTypePro" +
      "toH\000\022,\n\tsubAction\030\003 \001(\0132\027.SubDiapasonAct" +
      "ionProtoH\000\022\032\n\020minimalSerifLine\030\004 \001(\014H\000\022," +
      "\n\010fullInfo\030\005 \001(\0132\030.FullInfoApiMessagePro" +
      "toH\000\0223\n\rhideWaterfall\030\006 \001(\0132\032.HideWaterf" +
      "allMessageProtoH\000B\t\n\007message\"\233\002\n\020InfoGad" +
      "alkaProto\022/\n\021frequencySpectrum\030\001 \001(\0132\024.F" +
      "requencyRangeProto\022\017\n\007gainLNA\030\002 \001(\005\022\017\n\007g" +
      "ainVGA\030\003 \001(\005\022\022\n\nantennaLNA\030\004 \001(\010\022\034\n\024spec" +
      "trumPaletteStart\030\005 \001(\005\022\033\n\023spectrumPalett" +
      "eSize\030\006 \001(\005\022\020\n\010ffTBinHz\030\007 \001(\005\022\017\n\007samples" +
      "\030\010 \001(\005\022\025\n\rcounterSignal\030\t \001(\005\022\023\n\013counter" +
      "Lose\030\n \001(\005\022\026\n\016subRangeRemote\030\013 \001(\005\"\346\001\n\027F" +
      "ullInfoApiMessageProto\022&\n\013infoGadalka\030\001 " +
      "\001(\0132\021.InfoGadalkaProto\022+\n\022serifTypeAlgor" +
      "ithm\030\002 \001(\0162\017.SerifTypeProto\022\035\n\020minimalSe" +
      "rifLine\030\003 \001(\014H\000\210\001\001\022%\n\030listSelectionSubDi" +
      "apason\030\004 \001(\014H\001\210\001\001B\023\n\021_minimalSerifLineB\033" +
      "\n\031_listSelectionSubDiapason\",\n\031HideWater" +
      "fallMessageProto\022\017\n\007visible\030\001 \001(\010*@\n\016Ser" +
      "ifTypeProto\022\n\n\006MANUAL\020\000\022\n\n\006AUTO_3\020\001\022\n\n\006A" +
      "UTO_4\020\002\022\n\n\006AUTO_5\020\003B\017\n\013protoModelsP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protoModels.WebSocketSubDiapason.getDescriptor(),
          protoModels.FrequencyRange.getDescriptor(),
        });
    internal_static_WebSocketMessageTaskProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WebSocketMessageTaskProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WebSocketMessageTaskProto_descriptor,
        new java.lang.String[] { "InfoGadalka", "SerifTypeAlgorithm", "SubAction", "MinimalSerifLine", "FullInfo", "HideWaterfall", "Message", });
    internal_static_InfoGadalkaProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_InfoGadalkaProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InfoGadalkaProto_descriptor,
        new java.lang.String[] { "FrequencySpectrum", "GainLNA", "GainVGA", "AntennaLNA", "SpectrumPaletteStart", "SpectrumPaletteSize", "FfTBinHz", "Samples", "CounterSignal", "CounterLose", "SubRangeRemote", });
    internal_static_FullInfoApiMessageProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_FullInfoApiMessageProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FullInfoApiMessageProto_descriptor,
        new java.lang.String[] { "InfoGadalka", "SerifTypeAlgorithm", "MinimalSerifLine", "ListSelectionSubDiapason", "MinimalSerifLine", "ListSelectionSubDiapason", });
    internal_static_HideWaterfallMessageProto_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_HideWaterfallMessageProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HideWaterfallMessageProto_descriptor,
        new java.lang.String[] { "Visible", });
    protoModels.WebSocketSubDiapason.getDescriptor();
    protoModels.FrequencyRange.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
