// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/analizator_api.proto

package protoModels;

public interface WebSocketTaskProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WebSocketTaskProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuidTask = 1;</code>
   * @return The uuidTask.
   */
  java.lang.String getUuidTask();
  /**
   * <code>string uuidTask = 1;</code>
   * @return The bytes for uuidTask.
   */
  com.google.protobuf.ByteString
      getUuidTaskBytes();

  /**
   * <code>.WebSocketMessageTaskProto message = 2;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>.WebSocketMessageTaskProto message = 2;</code>
   * @return The message.
   */
  protoModels.WebSocketMessageTaskProto getMessage();
  /**
   * <code>.WebSocketMessageTaskProto message = 2;</code>
   */
  protoModels.WebSocketMessageTaskProtoOrBuilder getMessageOrBuilder();
}
