// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/web_socket_message.proto

package protoModels;

/**
 * Protobuf type {@code WebSocketMessageTaskProto}
 */
public final class WebSocketMessageTaskProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WebSocketMessageTaskProto)
    WebSocketMessageTaskProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WebSocketMessageTaskProto.newBuilder() to construct.
  private WebSocketMessageTaskProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WebSocketMessageTaskProto() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WebSocketMessageTaskProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protoModels.WebSocketMessage.internal_static_WebSocketMessageTaskProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protoModels.WebSocketMessage.internal_static_WebSocketMessageTaskProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protoModels.WebSocketMessageTaskProto.class, protoModels.WebSocketMessageTaskProto.Builder.class);
  }

  private int messageCase_ = 0;
  private java.lang.Object message_;
  public enum MessageCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    INFOGADALKA(1),
    SERIFTYPEALGORITHM(2),
    SUBACTION(3),
    MINIMALSERIFLINE(4),
    FULLINFO(5),
    HIDEWATERFALL(6),
    MESSAGE_NOT_SET(0);
    private final int value;
    private MessageCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageCase valueOf(int value) {
      return forNumber(value);
    }

    public static MessageCase forNumber(int value) {
      switch (value) {
        case 1: return INFOGADALKA;
        case 2: return SERIFTYPEALGORITHM;
        case 3: return SUBACTION;
        case 4: return MINIMALSERIFLINE;
        case 5: return FULLINFO;
        case 6: return HIDEWATERFALL;
        case 0: return MESSAGE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MessageCase
  getMessageCase() {
    return MessageCase.forNumber(
        messageCase_);
  }

  public static final int INFOGADALKA_FIELD_NUMBER = 1;
  /**
   * <code>.InfoGadalkaProto infoGadalka = 1;</code>
   * @return Whether the infoGadalka field is set.
   */
  @java.lang.Override
  public boolean hasInfoGadalka() {
    return messageCase_ == 1;
  }
  /**
   * <code>.InfoGadalkaProto infoGadalka = 1;</code>
   * @return The infoGadalka.
   */
  @java.lang.Override
  public protoModels.InfoGadalkaProto getInfoGadalka() {
    if (messageCase_ == 1) {
       return (protoModels.InfoGadalkaProto) message_;
    }
    return protoModels.InfoGadalkaProto.getDefaultInstance();
  }
  /**
   * <code>.InfoGadalkaProto infoGadalka = 1;</code>
   */
  @java.lang.Override
  public protoModels.InfoGadalkaProtoOrBuilder getInfoGadalkaOrBuilder() {
    if (messageCase_ == 1) {
       return (protoModels.InfoGadalkaProto) message_;
    }
    return protoModels.InfoGadalkaProto.getDefaultInstance();
  }

  public static final int SERIFTYPEALGORITHM_FIELD_NUMBER = 2;
  /**
   * <code>.SerifTypeProto serifTypeAlgorithm = 2;</code>
   * @return Whether the serifTypeAlgorithm field is set.
   */
  public boolean hasSerifTypeAlgorithm() {
    return messageCase_ == 2;
  }
  /**
   * <code>.SerifTypeProto serifTypeAlgorithm = 2;</code>
   * @return The enum numeric value on the wire for serifTypeAlgorithm.
   */
  public int getSerifTypeAlgorithmValue() {
    if (messageCase_ == 2) {
      return (java.lang.Integer) message_;
    }
    return 0;
  }
  /**
   * <code>.SerifTypeProto serifTypeAlgorithm = 2;</code>
   * @return The serifTypeAlgorithm.
   */
  public protoModels.SerifTypeProto getSerifTypeAlgorithm() {
    if (messageCase_ == 2) {
      protoModels.SerifTypeProto result = protoModels.SerifTypeProto.forNumber(
          (java.lang.Integer) message_);
      return result == null ? protoModels.SerifTypeProto.UNRECOGNIZED : result;
    }
    return protoModels.SerifTypeProto.MANUAL;
  }

  public static final int SUBACTION_FIELD_NUMBER = 3;
  /**
   * <code>.SubDiapasonActionProto subAction = 3;</code>
   * @return Whether the subAction field is set.
   */
  @java.lang.Override
  public boolean hasSubAction() {
    return messageCase_ == 3;
  }
  /**
   * <code>.SubDiapasonActionProto subAction = 3;</code>
   * @return The subAction.
   */
  @java.lang.Override
  public protoModels.SubDiapasonActionProto getSubAction() {
    if (messageCase_ == 3) {
       return (protoModels.SubDiapasonActionProto) message_;
    }
    return protoModels.SubDiapasonActionProto.getDefaultInstance();
  }
  /**
   * <code>.SubDiapasonActionProto subAction = 3;</code>
   */
  @java.lang.Override
  public protoModels.SubDiapasonActionProtoOrBuilder getSubActionOrBuilder() {
    if (messageCase_ == 3) {
       return (protoModels.SubDiapasonActionProto) message_;
    }
    return protoModels.SubDiapasonActionProto.getDefaultInstance();
  }

  public static final int MINIMALSERIFLINE_FIELD_NUMBER = 4;
  /**
   * <code>bytes minimalSerifLine = 4;</code>
   * @return Whether the minimalSerifLine field is set.
   */
  @java.lang.Override
  public boolean hasMinimalSerifLine() {
    return messageCase_ == 4;
  }
  /**
   * <code>bytes minimalSerifLine = 4;</code>
   * @return The minimalSerifLine.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getMinimalSerifLine() {
    if (messageCase_ == 4) {
      return (com.google.protobuf.ByteString) message_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }

  public static final int FULLINFO_FIELD_NUMBER = 5;
  /**
   * <code>.FullInfoApiMessageProto fullInfo = 5;</code>
   * @return Whether the fullInfo field is set.
   */
  @java.lang.Override
  public boolean hasFullInfo() {
    return messageCase_ == 5;
  }
  /**
   * <code>.FullInfoApiMessageProto fullInfo = 5;</code>
   * @return The fullInfo.
   */
  @java.lang.Override
  public protoModels.FullInfoApiMessageProto getFullInfo() {
    if (messageCase_ == 5) {
       return (protoModels.FullInfoApiMessageProto) message_;
    }
    return protoModels.FullInfoApiMessageProto.getDefaultInstance();
  }
  /**
   * <code>.FullInfoApiMessageProto fullInfo = 5;</code>
   */
  @java.lang.Override
  public protoModels.FullInfoApiMessageProtoOrBuilder getFullInfoOrBuilder() {
    if (messageCase_ == 5) {
       return (protoModels.FullInfoApiMessageProto) message_;
    }
    return protoModels.FullInfoApiMessageProto.getDefaultInstance();
  }

  public static final int HIDEWATERFALL_FIELD_NUMBER = 6;
  /**
   * <code>.HideWaterfallMessageProto hideWaterfall = 6;</code>
   * @return Whether the hideWaterfall field is set.
   */
  @java.lang.Override
  public boolean hasHideWaterfall() {
    return messageCase_ == 6;
  }
  /**
   * <code>.HideWaterfallMessageProto hideWaterfall = 6;</code>
   * @return The hideWaterfall.
   */
  @java.lang.Override
  public protoModels.HideWaterfallMessageProto getHideWaterfall() {
    if (messageCase_ == 6) {
       return (protoModels.HideWaterfallMessageProto) message_;
    }
    return protoModels.HideWaterfallMessageProto.getDefaultInstance();
  }
  /**
   * <code>.HideWaterfallMessageProto hideWaterfall = 6;</code>
   */
  @java.lang.Override
  public protoModels.HideWaterfallMessageProtoOrBuilder getHideWaterfallOrBuilder() {
    if (messageCase_ == 6) {
       return (protoModels.HideWaterfallMessageProto) message_;
    }
    return protoModels.HideWaterfallMessageProto.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageCase_ == 1) {
      output.writeMessage(1, (protoModels.InfoGadalkaProto) message_);
    }
    if (messageCase_ == 2) {
      output.writeEnum(2, ((java.lang.Integer) message_));
    }
    if (messageCase_ == 3) {
      output.writeMessage(3, (protoModels.SubDiapasonActionProto) message_);
    }
    if (messageCase_ == 4) {
      output.writeBytes(
          4, (com.google.protobuf.ByteString) message_);
    }
    if (messageCase_ == 5) {
      output.writeMessage(5, (protoModels.FullInfoApiMessageProto) message_);
    }
    if (messageCase_ == 6) {
      output.writeMessage(6, (protoModels.HideWaterfallMessageProto) message_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (messageCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (protoModels.InfoGadalkaProto) message_);
    }
    if (messageCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, ((java.lang.Integer) message_));
    }
    if (messageCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (protoModels.SubDiapasonActionProto) message_);
    }
    if (messageCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            4, (com.google.protobuf.ByteString) message_);
    }
    if (messageCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (protoModels.FullInfoApiMessageProto) message_);
    }
    if (messageCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (protoModels.HideWaterfallMessageProto) message_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protoModels.WebSocketMessageTaskProto)) {
      return super.equals(obj);
    }
    protoModels.WebSocketMessageTaskProto other = (protoModels.WebSocketMessageTaskProto) obj;

    if (!getMessageCase().equals(other.getMessageCase())) return false;
    switch (messageCase_) {
      case 1:
        if (!getInfoGadalka()
            .equals(other.getInfoGadalka())) return false;
        break;
      case 2:
        if (getSerifTypeAlgorithmValue()
            != other.getSerifTypeAlgorithmValue()) return false;
        break;
      case 3:
        if (!getSubAction()
            .equals(other.getSubAction())) return false;
        break;
      case 4:
        if (!getMinimalSerifLine()
            .equals(other.getMinimalSerifLine())) return false;
        break;
      case 5:
        if (!getFullInfo()
            .equals(other.getFullInfo())) return false;
        break;
      case 6:
        if (!getHideWaterfall()
            .equals(other.getHideWaterfall())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (messageCase_) {
      case 1:
        hash = (37 * hash) + INFOGADALKA_FIELD_NUMBER;
        hash = (53 * hash) + getInfoGadalka().hashCode();
        break;
      case 2:
        hash = (37 * hash) + SERIFTYPEALGORITHM_FIELD_NUMBER;
        hash = (53 * hash) + getSerifTypeAlgorithmValue();
        break;
      case 3:
        hash = (37 * hash) + SUBACTION_FIELD_NUMBER;
        hash = (53 * hash) + getSubAction().hashCode();
        break;
      case 4:
        hash = (37 * hash) + MINIMALSERIFLINE_FIELD_NUMBER;
        hash = (53 * hash) + getMinimalSerifLine().hashCode();
        break;
      case 5:
        hash = (37 * hash) + FULLINFO_FIELD_NUMBER;
        hash = (53 * hash) + getFullInfo().hashCode();
        break;
      case 6:
        hash = (37 * hash) + HIDEWATERFALL_FIELD_NUMBER;
        hash = (53 * hash) + getHideWaterfall().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protoModels.WebSocketMessageTaskProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.WebSocketMessageTaskProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.WebSocketMessageTaskProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.WebSocketMessageTaskProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.WebSocketMessageTaskProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.WebSocketMessageTaskProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.WebSocketMessageTaskProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protoModels.WebSocketMessageTaskProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protoModels.WebSocketMessageTaskProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protoModels.WebSocketMessageTaskProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protoModels.WebSocketMessageTaskProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protoModels.WebSocketMessageTaskProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protoModels.WebSocketMessageTaskProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WebSocketMessageTaskProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WebSocketMessageTaskProto)
      protoModels.WebSocketMessageTaskProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoModels.WebSocketMessage.internal_static_WebSocketMessageTaskProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoModels.WebSocketMessage.internal_static_WebSocketMessageTaskProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoModels.WebSocketMessageTaskProto.class, protoModels.WebSocketMessageTaskProto.Builder.class);
    }

    // Construct using protoModels.WebSocketMessageTaskProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (infoGadalkaBuilder_ != null) {
        infoGadalkaBuilder_.clear();
      }
      if (subActionBuilder_ != null) {
        subActionBuilder_.clear();
      }
      if (fullInfoBuilder_ != null) {
        fullInfoBuilder_.clear();
      }
      if (hideWaterfallBuilder_ != null) {
        hideWaterfallBuilder_.clear();
      }
      messageCase_ = 0;
      message_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protoModels.WebSocketMessage.internal_static_WebSocketMessageTaskProto_descriptor;
    }

    @java.lang.Override
    public protoModels.WebSocketMessageTaskProto getDefaultInstanceForType() {
      return protoModels.WebSocketMessageTaskProto.getDefaultInstance();
    }

    @java.lang.Override
    public protoModels.WebSocketMessageTaskProto build() {
      protoModels.WebSocketMessageTaskProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protoModels.WebSocketMessageTaskProto buildPartial() {
      protoModels.WebSocketMessageTaskProto result = new protoModels.WebSocketMessageTaskProto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(protoModels.WebSocketMessageTaskProto result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(protoModels.WebSocketMessageTaskProto result) {
      result.messageCase_ = messageCase_;
      result.message_ = this.message_;
      if (messageCase_ == 1 &&
          infoGadalkaBuilder_ != null) {
        result.message_ = infoGadalkaBuilder_.build();
      }
      if (messageCase_ == 3 &&
          subActionBuilder_ != null) {
        result.message_ = subActionBuilder_.build();
      }
      if (messageCase_ == 5 &&
          fullInfoBuilder_ != null) {
        result.message_ = fullInfoBuilder_.build();
      }
      if (messageCase_ == 6 &&
          hideWaterfallBuilder_ != null) {
        result.message_ = hideWaterfallBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protoModels.WebSocketMessageTaskProto) {
        return mergeFrom((protoModels.WebSocketMessageTaskProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protoModels.WebSocketMessageTaskProto other) {
      if (other == protoModels.WebSocketMessageTaskProto.getDefaultInstance()) return this;
      switch (other.getMessageCase()) {
        case INFOGADALKA: {
          mergeInfoGadalka(other.getInfoGadalka());
          break;
        }
        case SERIFTYPEALGORITHM: {
          setSerifTypeAlgorithmValue(other.getSerifTypeAlgorithmValue());
          break;
        }
        case SUBACTION: {
          mergeSubAction(other.getSubAction());
          break;
        }
        case MINIMALSERIFLINE: {
          setMinimalSerifLine(other.getMinimalSerifLine());
          break;
        }
        case FULLINFO: {
          mergeFullInfo(other.getFullInfo());
          break;
        }
        case HIDEWATERFALL: {
          mergeHideWaterfall(other.getHideWaterfall());
          break;
        }
        case MESSAGE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getInfoGadalkaFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 1;
              break;
            } // case 10
            case 16: {
              int rawValue = input.readEnum();
              messageCase_ = 2;
              message_ = rawValue;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getSubActionFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 3;
              break;
            } // case 26
            case 34: {
              message_ = input.readBytes();
              messageCase_ = 4;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getFullInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 5;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getHideWaterfallFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageCase_ = 6;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int messageCase_ = 0;
    private java.lang.Object message_;
    public MessageCase
        getMessageCase() {
      return MessageCase.forNumber(
          messageCase_);
    }

    public Builder clearMessage() {
      messageCase_ = 0;
      message_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        protoModels.InfoGadalkaProto, protoModels.InfoGadalkaProto.Builder, protoModels.InfoGadalkaProtoOrBuilder> infoGadalkaBuilder_;
    /**
     * <code>.InfoGadalkaProto infoGadalka = 1;</code>
     * @return Whether the infoGadalka field is set.
     */
    @java.lang.Override
    public boolean hasInfoGadalka() {
      return messageCase_ == 1;
    }
    /**
     * <code>.InfoGadalkaProto infoGadalka = 1;</code>
     * @return The infoGadalka.
     */
    @java.lang.Override
    public protoModels.InfoGadalkaProto getInfoGadalka() {
      if (infoGadalkaBuilder_ == null) {
        if (messageCase_ == 1) {
          return (protoModels.InfoGadalkaProto) message_;
        }
        return protoModels.InfoGadalkaProto.getDefaultInstance();
      } else {
        if (messageCase_ == 1) {
          return infoGadalkaBuilder_.getMessage();
        }
        return protoModels.InfoGadalkaProto.getDefaultInstance();
      }
    }
    /**
     * <code>.InfoGadalkaProto infoGadalka = 1;</code>
     */
    public Builder setInfoGadalka(protoModels.InfoGadalkaProto value) {
      if (infoGadalkaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        infoGadalkaBuilder_.setMessage(value);
      }
      messageCase_ = 1;
      return this;
    }
    /**
     * <code>.InfoGadalkaProto infoGadalka = 1;</code>
     */
    public Builder setInfoGadalka(
        protoModels.InfoGadalkaProto.Builder builderForValue) {
      if (infoGadalkaBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        infoGadalkaBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 1;
      return this;
    }
    /**
     * <code>.InfoGadalkaProto infoGadalka = 1;</code>
     */
    public Builder mergeInfoGadalka(protoModels.InfoGadalkaProto value) {
      if (infoGadalkaBuilder_ == null) {
        if (messageCase_ == 1 &&
            message_ != protoModels.InfoGadalkaProto.getDefaultInstance()) {
          message_ = protoModels.InfoGadalkaProto.newBuilder((protoModels.InfoGadalkaProto) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 1) {
          infoGadalkaBuilder_.mergeFrom(value);
        } else {
          infoGadalkaBuilder_.setMessage(value);
        }
      }
      messageCase_ = 1;
      return this;
    }
    /**
     * <code>.InfoGadalkaProto infoGadalka = 1;</code>
     */
    public Builder clearInfoGadalka() {
      if (infoGadalkaBuilder_ == null) {
        if (messageCase_ == 1) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 1) {
          messageCase_ = 0;
          message_ = null;
        }
        infoGadalkaBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.InfoGadalkaProto infoGadalka = 1;</code>
     */
    public protoModels.InfoGadalkaProto.Builder getInfoGadalkaBuilder() {
      return getInfoGadalkaFieldBuilder().getBuilder();
    }
    /**
     * <code>.InfoGadalkaProto infoGadalka = 1;</code>
     */
    @java.lang.Override
    public protoModels.InfoGadalkaProtoOrBuilder getInfoGadalkaOrBuilder() {
      if ((messageCase_ == 1) && (infoGadalkaBuilder_ != null)) {
        return infoGadalkaBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 1) {
          return (protoModels.InfoGadalkaProto) message_;
        }
        return protoModels.InfoGadalkaProto.getDefaultInstance();
      }
    }
    /**
     * <code>.InfoGadalkaProto infoGadalka = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        protoModels.InfoGadalkaProto, protoModels.InfoGadalkaProto.Builder, protoModels.InfoGadalkaProtoOrBuilder> 
        getInfoGadalkaFieldBuilder() {
      if (infoGadalkaBuilder_ == null) {
        if (!(messageCase_ == 1)) {
          message_ = protoModels.InfoGadalkaProto.getDefaultInstance();
        }
        infoGadalkaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            protoModels.InfoGadalkaProto, protoModels.InfoGadalkaProto.Builder, protoModels.InfoGadalkaProtoOrBuilder>(
                (protoModels.InfoGadalkaProto) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 1;
      onChanged();
      return infoGadalkaBuilder_;
    }

    /**
     * <code>.SerifTypeProto serifTypeAlgorithm = 2;</code>
     * @return Whether the serifTypeAlgorithm field is set.
     */
    @java.lang.Override
    public boolean hasSerifTypeAlgorithm() {
      return messageCase_ == 2;
    }
    /**
     * <code>.SerifTypeProto serifTypeAlgorithm = 2;</code>
     * @return The enum numeric value on the wire for serifTypeAlgorithm.
     */
    @java.lang.Override
    public int getSerifTypeAlgorithmValue() {
      if (messageCase_ == 2) {
        return ((java.lang.Integer) message_).intValue();
      }
      return 0;
    }
    /**
     * <code>.SerifTypeProto serifTypeAlgorithm = 2;</code>
     * @param value The enum numeric value on the wire for serifTypeAlgorithm to set.
     * @return This builder for chaining.
     */
    public Builder setSerifTypeAlgorithmValue(int value) {
      messageCase_ = 2;
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.SerifTypeProto serifTypeAlgorithm = 2;</code>
     * @return The serifTypeAlgorithm.
     */
    @java.lang.Override
    public protoModels.SerifTypeProto getSerifTypeAlgorithm() {
      if (messageCase_ == 2) {
        protoModels.SerifTypeProto result = protoModels.SerifTypeProto.forNumber(
            (java.lang.Integer) message_);
        return result == null ? protoModels.SerifTypeProto.UNRECOGNIZED : result;
      }
      return protoModels.SerifTypeProto.MANUAL;
    }
    /**
     * <code>.SerifTypeProto serifTypeAlgorithm = 2;</code>
     * @param value The serifTypeAlgorithm to set.
     * @return This builder for chaining.
     */
    public Builder setSerifTypeAlgorithm(protoModels.SerifTypeProto value) {
      if (value == null) {
        throw new NullPointerException();
      }
      messageCase_ = 2;
      message_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.SerifTypeProto serifTypeAlgorithm = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSerifTypeAlgorithm() {
      if (messageCase_ == 2) {
        messageCase_ = 0;
        message_ = null;
        onChanged();
      }
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        protoModels.SubDiapasonActionProto, protoModels.SubDiapasonActionProto.Builder, protoModels.SubDiapasonActionProtoOrBuilder> subActionBuilder_;
    /**
     * <code>.SubDiapasonActionProto subAction = 3;</code>
     * @return Whether the subAction field is set.
     */
    @java.lang.Override
    public boolean hasSubAction() {
      return messageCase_ == 3;
    }
    /**
     * <code>.SubDiapasonActionProto subAction = 3;</code>
     * @return The subAction.
     */
    @java.lang.Override
    public protoModels.SubDiapasonActionProto getSubAction() {
      if (subActionBuilder_ == null) {
        if (messageCase_ == 3) {
          return (protoModels.SubDiapasonActionProto) message_;
        }
        return protoModels.SubDiapasonActionProto.getDefaultInstance();
      } else {
        if (messageCase_ == 3) {
          return subActionBuilder_.getMessage();
        }
        return protoModels.SubDiapasonActionProto.getDefaultInstance();
      }
    }
    /**
     * <code>.SubDiapasonActionProto subAction = 3;</code>
     */
    public Builder setSubAction(protoModels.SubDiapasonActionProto value) {
      if (subActionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        subActionBuilder_.setMessage(value);
      }
      messageCase_ = 3;
      return this;
    }
    /**
     * <code>.SubDiapasonActionProto subAction = 3;</code>
     */
    public Builder setSubAction(
        protoModels.SubDiapasonActionProto.Builder builderForValue) {
      if (subActionBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        subActionBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 3;
      return this;
    }
    /**
     * <code>.SubDiapasonActionProto subAction = 3;</code>
     */
    public Builder mergeSubAction(protoModels.SubDiapasonActionProto value) {
      if (subActionBuilder_ == null) {
        if (messageCase_ == 3 &&
            message_ != protoModels.SubDiapasonActionProto.getDefaultInstance()) {
          message_ = protoModels.SubDiapasonActionProto.newBuilder((protoModels.SubDiapasonActionProto) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 3) {
          subActionBuilder_.mergeFrom(value);
        } else {
          subActionBuilder_.setMessage(value);
        }
      }
      messageCase_ = 3;
      return this;
    }
    /**
     * <code>.SubDiapasonActionProto subAction = 3;</code>
     */
    public Builder clearSubAction() {
      if (subActionBuilder_ == null) {
        if (messageCase_ == 3) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 3) {
          messageCase_ = 0;
          message_ = null;
        }
        subActionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.SubDiapasonActionProto subAction = 3;</code>
     */
    public protoModels.SubDiapasonActionProto.Builder getSubActionBuilder() {
      return getSubActionFieldBuilder().getBuilder();
    }
    /**
     * <code>.SubDiapasonActionProto subAction = 3;</code>
     */
    @java.lang.Override
    public protoModels.SubDiapasonActionProtoOrBuilder getSubActionOrBuilder() {
      if ((messageCase_ == 3) && (subActionBuilder_ != null)) {
        return subActionBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 3) {
          return (protoModels.SubDiapasonActionProto) message_;
        }
        return protoModels.SubDiapasonActionProto.getDefaultInstance();
      }
    }
    /**
     * <code>.SubDiapasonActionProto subAction = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        protoModels.SubDiapasonActionProto, protoModels.SubDiapasonActionProto.Builder, protoModels.SubDiapasonActionProtoOrBuilder> 
        getSubActionFieldBuilder() {
      if (subActionBuilder_ == null) {
        if (!(messageCase_ == 3)) {
          message_ = protoModels.SubDiapasonActionProto.getDefaultInstance();
        }
        subActionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            protoModels.SubDiapasonActionProto, protoModels.SubDiapasonActionProto.Builder, protoModels.SubDiapasonActionProtoOrBuilder>(
                (protoModels.SubDiapasonActionProto) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 3;
      onChanged();
      return subActionBuilder_;
    }

    /**
     * <code>bytes minimalSerifLine = 4;</code>
     * @return Whether the minimalSerifLine field is set.
     */
    public boolean hasMinimalSerifLine() {
      return messageCase_ == 4;
    }
    /**
     * <code>bytes minimalSerifLine = 4;</code>
     * @return The minimalSerifLine.
     */
    public com.google.protobuf.ByteString getMinimalSerifLine() {
      if (messageCase_ == 4) {
        return (com.google.protobuf.ByteString) message_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <code>bytes minimalSerifLine = 4;</code>
     * @param value The minimalSerifLine to set.
     * @return This builder for chaining.
     */
    public Builder setMinimalSerifLine(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      messageCase_ = 4;
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes minimalSerifLine = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinimalSerifLine() {
      if (messageCase_ == 4) {
        messageCase_ = 0;
        message_ = null;
        onChanged();
      }
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        protoModels.FullInfoApiMessageProto, protoModels.FullInfoApiMessageProto.Builder, protoModels.FullInfoApiMessageProtoOrBuilder> fullInfoBuilder_;
    /**
     * <code>.FullInfoApiMessageProto fullInfo = 5;</code>
     * @return Whether the fullInfo field is set.
     */
    @java.lang.Override
    public boolean hasFullInfo() {
      return messageCase_ == 5;
    }
    /**
     * <code>.FullInfoApiMessageProto fullInfo = 5;</code>
     * @return The fullInfo.
     */
    @java.lang.Override
    public protoModels.FullInfoApiMessageProto getFullInfo() {
      if (fullInfoBuilder_ == null) {
        if (messageCase_ == 5) {
          return (protoModels.FullInfoApiMessageProto) message_;
        }
        return protoModels.FullInfoApiMessageProto.getDefaultInstance();
      } else {
        if (messageCase_ == 5) {
          return fullInfoBuilder_.getMessage();
        }
        return protoModels.FullInfoApiMessageProto.getDefaultInstance();
      }
    }
    /**
     * <code>.FullInfoApiMessageProto fullInfo = 5;</code>
     */
    public Builder setFullInfo(protoModels.FullInfoApiMessageProto value) {
      if (fullInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        fullInfoBuilder_.setMessage(value);
      }
      messageCase_ = 5;
      return this;
    }
    /**
     * <code>.FullInfoApiMessageProto fullInfo = 5;</code>
     */
    public Builder setFullInfo(
        protoModels.FullInfoApiMessageProto.Builder builderForValue) {
      if (fullInfoBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        fullInfoBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 5;
      return this;
    }
    /**
     * <code>.FullInfoApiMessageProto fullInfo = 5;</code>
     */
    public Builder mergeFullInfo(protoModels.FullInfoApiMessageProto value) {
      if (fullInfoBuilder_ == null) {
        if (messageCase_ == 5 &&
            message_ != protoModels.FullInfoApiMessageProto.getDefaultInstance()) {
          message_ = protoModels.FullInfoApiMessageProto.newBuilder((protoModels.FullInfoApiMessageProto) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 5) {
          fullInfoBuilder_.mergeFrom(value);
        } else {
          fullInfoBuilder_.setMessage(value);
        }
      }
      messageCase_ = 5;
      return this;
    }
    /**
     * <code>.FullInfoApiMessageProto fullInfo = 5;</code>
     */
    public Builder clearFullInfo() {
      if (fullInfoBuilder_ == null) {
        if (messageCase_ == 5) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 5) {
          messageCase_ = 0;
          message_ = null;
        }
        fullInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.FullInfoApiMessageProto fullInfo = 5;</code>
     */
    public protoModels.FullInfoApiMessageProto.Builder getFullInfoBuilder() {
      return getFullInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.FullInfoApiMessageProto fullInfo = 5;</code>
     */
    @java.lang.Override
    public protoModels.FullInfoApiMessageProtoOrBuilder getFullInfoOrBuilder() {
      if ((messageCase_ == 5) && (fullInfoBuilder_ != null)) {
        return fullInfoBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 5) {
          return (protoModels.FullInfoApiMessageProto) message_;
        }
        return protoModels.FullInfoApiMessageProto.getDefaultInstance();
      }
    }
    /**
     * <code>.FullInfoApiMessageProto fullInfo = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        protoModels.FullInfoApiMessageProto, protoModels.FullInfoApiMessageProto.Builder, protoModels.FullInfoApiMessageProtoOrBuilder> 
        getFullInfoFieldBuilder() {
      if (fullInfoBuilder_ == null) {
        if (!(messageCase_ == 5)) {
          message_ = protoModels.FullInfoApiMessageProto.getDefaultInstance();
        }
        fullInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            protoModels.FullInfoApiMessageProto, protoModels.FullInfoApiMessageProto.Builder, protoModels.FullInfoApiMessageProtoOrBuilder>(
                (protoModels.FullInfoApiMessageProto) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 5;
      onChanged();
      return fullInfoBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        protoModels.HideWaterfallMessageProto, protoModels.HideWaterfallMessageProto.Builder, protoModels.HideWaterfallMessageProtoOrBuilder> hideWaterfallBuilder_;
    /**
     * <code>.HideWaterfallMessageProto hideWaterfall = 6;</code>
     * @return Whether the hideWaterfall field is set.
     */
    @java.lang.Override
    public boolean hasHideWaterfall() {
      return messageCase_ == 6;
    }
    /**
     * <code>.HideWaterfallMessageProto hideWaterfall = 6;</code>
     * @return The hideWaterfall.
     */
    @java.lang.Override
    public protoModels.HideWaterfallMessageProto getHideWaterfall() {
      if (hideWaterfallBuilder_ == null) {
        if (messageCase_ == 6) {
          return (protoModels.HideWaterfallMessageProto) message_;
        }
        return protoModels.HideWaterfallMessageProto.getDefaultInstance();
      } else {
        if (messageCase_ == 6) {
          return hideWaterfallBuilder_.getMessage();
        }
        return protoModels.HideWaterfallMessageProto.getDefaultInstance();
      }
    }
    /**
     * <code>.HideWaterfallMessageProto hideWaterfall = 6;</code>
     */
    public Builder setHideWaterfall(protoModels.HideWaterfallMessageProto value) {
      if (hideWaterfallBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
        onChanged();
      } else {
        hideWaterfallBuilder_.setMessage(value);
      }
      messageCase_ = 6;
      return this;
    }
    /**
     * <code>.HideWaterfallMessageProto hideWaterfall = 6;</code>
     */
    public Builder setHideWaterfall(
        protoModels.HideWaterfallMessageProto.Builder builderForValue) {
      if (hideWaterfallBuilder_ == null) {
        message_ = builderForValue.build();
        onChanged();
      } else {
        hideWaterfallBuilder_.setMessage(builderForValue.build());
      }
      messageCase_ = 6;
      return this;
    }
    /**
     * <code>.HideWaterfallMessageProto hideWaterfall = 6;</code>
     */
    public Builder mergeHideWaterfall(protoModels.HideWaterfallMessageProto value) {
      if (hideWaterfallBuilder_ == null) {
        if (messageCase_ == 6 &&
            message_ != protoModels.HideWaterfallMessageProto.getDefaultInstance()) {
          message_ = protoModels.HideWaterfallMessageProto.newBuilder((protoModels.HideWaterfallMessageProto) message_)
              .mergeFrom(value).buildPartial();
        } else {
          message_ = value;
        }
        onChanged();
      } else {
        if (messageCase_ == 6) {
          hideWaterfallBuilder_.mergeFrom(value);
        } else {
          hideWaterfallBuilder_.setMessage(value);
        }
      }
      messageCase_ = 6;
      return this;
    }
    /**
     * <code>.HideWaterfallMessageProto hideWaterfall = 6;</code>
     */
    public Builder clearHideWaterfall() {
      if (hideWaterfallBuilder_ == null) {
        if (messageCase_ == 6) {
          messageCase_ = 0;
          message_ = null;
          onChanged();
        }
      } else {
        if (messageCase_ == 6) {
          messageCase_ = 0;
          message_ = null;
        }
        hideWaterfallBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.HideWaterfallMessageProto hideWaterfall = 6;</code>
     */
    public protoModels.HideWaterfallMessageProto.Builder getHideWaterfallBuilder() {
      return getHideWaterfallFieldBuilder().getBuilder();
    }
    /**
     * <code>.HideWaterfallMessageProto hideWaterfall = 6;</code>
     */
    @java.lang.Override
    public protoModels.HideWaterfallMessageProtoOrBuilder getHideWaterfallOrBuilder() {
      if ((messageCase_ == 6) && (hideWaterfallBuilder_ != null)) {
        return hideWaterfallBuilder_.getMessageOrBuilder();
      } else {
        if (messageCase_ == 6) {
          return (protoModels.HideWaterfallMessageProto) message_;
        }
        return protoModels.HideWaterfallMessageProto.getDefaultInstance();
      }
    }
    /**
     * <code>.HideWaterfallMessageProto hideWaterfall = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        protoModels.HideWaterfallMessageProto, protoModels.HideWaterfallMessageProto.Builder, protoModels.HideWaterfallMessageProtoOrBuilder> 
        getHideWaterfallFieldBuilder() {
      if (hideWaterfallBuilder_ == null) {
        if (!(messageCase_ == 6)) {
          message_ = protoModels.HideWaterfallMessageProto.getDefaultInstance();
        }
        hideWaterfallBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            protoModels.HideWaterfallMessageProto, protoModels.HideWaterfallMessageProto.Builder, protoModels.HideWaterfallMessageProtoOrBuilder>(
                (protoModels.HideWaterfallMessageProto) message_,
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      messageCase_ = 6;
      onChanged();
      return hideWaterfallBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WebSocketMessageTaskProto)
  }

  // @@protoc_insertion_point(class_scope:WebSocketMessageTaskProto)
  private static final protoModels.WebSocketMessageTaskProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protoModels.WebSocketMessageTaskProto();
  }

  public static protoModels.WebSocketMessageTaskProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WebSocketMessageTaskProto>
      PARSER = new com.google.protobuf.AbstractParser<WebSocketMessageTaskProto>() {
    @java.lang.Override
    public WebSocketMessageTaskProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WebSocketMessageTaskProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WebSocketMessageTaskProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protoModels.WebSocketMessageTaskProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

