// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/web_socket_sub_diapason.proto

package protoModels;

public final class WebSocketSubDiapason {
  private WebSocketSubDiapason() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubDiapasonActionProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SubDiapasonActionProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListSelectionSubDiapasonProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListSelectionSubDiapasonProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ActionCreateSubDiapasonProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ActionCreateSubDiapasonProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ActionDeleteSubDiapasonProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ActionDeleteSubDiapasonProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ActionDeleteAllSubDiapasonProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ActionDeleteAllSubDiapasonProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,src-java/proto/web_socket_sub_diapason" +
      ".proto\"\304\001\n\026SubDiapasonActionProto\022/\n\006cre" +
      "ate\030\001 \001(\0132\035.ActionCreateSubDiapasonProto" +
      "H\000\022/\n\006delete\030\002 \001(\0132\035.ActionDeleteSubDiap" +
      "asonProtoH\000\0225\n\tdeleteAll\030\003 \001(\0132 .ActionD" +
      "eleteAllSubDiapasonProtoH\000B\021\n\017taskSubDia" +
      "pason\"]\n\035ListSelectionSubDiapasonProto\022<" +
      "\n\025listSelectionDiapason\030\001 \003(\0132\035.ActionCr" +
      "eateSubDiapasonProto\"q\n\034ActionCreateSubD" +
      "iapasonProto\022#\n\004type\030\001 \001(\0162\025.TypeSubDiap" +
      "asonProto\022\026\n\016startFrequency\030\002 \001(\002\022\024\n\014end" +
      "Frequency\030\003 \001(\002\"1\n\034ActionDeleteSubDiapas" +
      "onProto\022\021\n\tfrequency\030\001 \001(\002\"!\n\037ActionDele" +
      "teAllSubDiapasonProto*)\n\024TypeSubDiapason" +
      "Proto\022\010\n\004FIND\020\000\022\007\n\003CUT\020\001B\017\n\013protoModelsP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SubDiapasonActionProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SubDiapasonActionProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SubDiapasonActionProto_descriptor,
        new java.lang.String[] { "Create", "Delete", "DeleteAll", "TaskSubDiapason", });
    internal_static_ListSelectionSubDiapasonProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ListSelectionSubDiapasonProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListSelectionSubDiapasonProto_descriptor,
        new java.lang.String[] { "ListSelectionDiapason", });
    internal_static_ActionCreateSubDiapasonProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ActionCreateSubDiapasonProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ActionCreateSubDiapasonProto_descriptor,
        new java.lang.String[] { "Type", "StartFrequency", "EndFrequency", });
    internal_static_ActionDeleteSubDiapasonProto_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ActionDeleteSubDiapasonProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ActionDeleteSubDiapasonProto_descriptor,
        new java.lang.String[] { "Frequency", });
    internal_static_ActionDeleteAllSubDiapasonProto_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ActionDeleteAllSubDiapasonProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ActionDeleteAllSubDiapasonProto_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
