// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src-java/proto/analizator_api.proto

package protoModels;

/**
 * Protobuf type {@code WebSocketTaskProto}
 */
public final class WebSocketTaskProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WebSocketTaskProto)
    WebSocketTaskProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WebSocketTaskProto.newBuilder() to construct.
  private WebSocketTaskProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WebSocketTaskProto() {
    uuidTask_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WebSocketTaskProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return protoModels.AnalizatorApi.internal_static_WebSocketTaskProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return protoModels.AnalizatorApi.internal_static_WebSocketTaskProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            protoModels.WebSocketTaskProto.class, protoModels.WebSocketTaskProto.Builder.class);
  }

  public static final int UUIDTASK_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object uuidTask_ = "";
  /**
   * <code>string uuidTask = 1;</code>
   * @return The uuidTask.
   */
  @java.lang.Override
  public java.lang.String getUuidTask() {
    java.lang.Object ref = uuidTask_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uuidTask_ = s;
      return s;
    }
  }
  /**
   * <code>string uuidTask = 1;</code>
   * @return The bytes for uuidTask.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUuidTaskBytes() {
    java.lang.Object ref = uuidTask_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uuidTask_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private protoModels.WebSocketMessageTaskProto message_;
  /**
   * <code>.WebSocketMessageTaskProto message = 2;</code>
   * @return Whether the message field is set.
   */
  @java.lang.Override
  public boolean hasMessage() {
    return message_ != null;
  }
  /**
   * <code>.WebSocketMessageTaskProto message = 2;</code>
   * @return The message.
   */
  @java.lang.Override
  public protoModels.WebSocketMessageTaskProto getMessage() {
    return message_ == null ? protoModels.WebSocketMessageTaskProto.getDefaultInstance() : message_;
  }
  /**
   * <code>.WebSocketMessageTaskProto message = 2;</code>
   */
  @java.lang.Override
  public protoModels.WebSocketMessageTaskProtoOrBuilder getMessageOrBuilder() {
    return message_ == null ? protoModels.WebSocketMessageTaskProto.getDefaultInstance() : message_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uuidTask_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuidTask_);
    }
    if (message_ != null) {
      output.writeMessage(2, getMessage());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(uuidTask_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuidTask_);
    }
    if (message_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMessage());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof protoModels.WebSocketTaskProto)) {
      return super.equals(obj);
    }
    protoModels.WebSocketTaskProto other = (protoModels.WebSocketTaskProto) obj;

    if (!getUuidTask()
        .equals(other.getUuidTask())) return false;
    if (hasMessage() != other.hasMessage()) return false;
    if (hasMessage()) {
      if (!getMessage()
          .equals(other.getMessage())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UUIDTASK_FIELD_NUMBER;
    hash = (53 * hash) + getUuidTask().hashCode();
    if (hasMessage()) {
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static protoModels.WebSocketTaskProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.WebSocketTaskProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.WebSocketTaskProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.WebSocketTaskProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.WebSocketTaskProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static protoModels.WebSocketTaskProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static protoModels.WebSocketTaskProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protoModels.WebSocketTaskProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static protoModels.WebSocketTaskProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static protoModels.WebSocketTaskProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static protoModels.WebSocketTaskProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static protoModels.WebSocketTaskProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(protoModels.WebSocketTaskProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WebSocketTaskProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WebSocketTaskProto)
      protoModels.WebSocketTaskProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoModels.AnalizatorApi.internal_static_WebSocketTaskProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoModels.AnalizatorApi.internal_static_WebSocketTaskProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoModels.WebSocketTaskProto.class, protoModels.WebSocketTaskProto.Builder.class);
    }

    // Construct using protoModels.WebSocketTaskProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      uuidTask_ = "";
      message_ = null;
      if (messageBuilder_ != null) {
        messageBuilder_.dispose();
        messageBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return protoModels.AnalizatorApi.internal_static_WebSocketTaskProto_descriptor;
    }

    @java.lang.Override
    public protoModels.WebSocketTaskProto getDefaultInstanceForType() {
      return protoModels.WebSocketTaskProto.getDefaultInstance();
    }

    @java.lang.Override
    public protoModels.WebSocketTaskProto build() {
      protoModels.WebSocketTaskProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public protoModels.WebSocketTaskProto buildPartial() {
      protoModels.WebSocketTaskProto result = new protoModels.WebSocketTaskProto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(protoModels.WebSocketTaskProto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.uuidTask_ = uuidTask_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.message_ = messageBuilder_ == null
            ? message_
            : messageBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof protoModels.WebSocketTaskProto) {
        return mergeFrom((protoModels.WebSocketTaskProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(protoModels.WebSocketTaskProto other) {
      if (other == protoModels.WebSocketTaskProto.getDefaultInstance()) return this;
      if (!other.getUuidTask().isEmpty()) {
        uuidTask_ = other.uuidTask_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasMessage()) {
        mergeMessage(other.getMessage());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              uuidTask_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getMessageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object uuidTask_ = "";
    /**
     * <code>string uuidTask = 1;</code>
     * @return The uuidTask.
     */
    public java.lang.String getUuidTask() {
      java.lang.Object ref = uuidTask_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuidTask_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string uuidTask = 1;</code>
     * @return The bytes for uuidTask.
     */
    public com.google.protobuf.ByteString
        getUuidTaskBytes() {
      java.lang.Object ref = uuidTask_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuidTask_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string uuidTask = 1;</code>
     * @param value The uuidTask to set.
     * @return This builder for chaining.
     */
    public Builder setUuidTask(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      uuidTask_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string uuidTask = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUuidTask() {
      uuidTask_ = getDefaultInstance().getUuidTask();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string uuidTask = 1;</code>
     * @param value The bytes for uuidTask to set.
     * @return This builder for chaining.
     */
    public Builder setUuidTaskBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      uuidTask_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private protoModels.WebSocketMessageTaskProto message_;
    private com.google.protobuf.SingleFieldBuilderV3<
        protoModels.WebSocketMessageTaskProto, protoModels.WebSocketMessageTaskProto.Builder, protoModels.WebSocketMessageTaskProtoOrBuilder> messageBuilder_;
    /**
     * <code>.WebSocketMessageTaskProto message = 2;</code>
     * @return Whether the message field is set.
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.WebSocketMessageTaskProto message = 2;</code>
     * @return The message.
     */
    public protoModels.WebSocketMessageTaskProto getMessage() {
      if (messageBuilder_ == null) {
        return message_ == null ? protoModels.WebSocketMessageTaskProto.getDefaultInstance() : message_;
      } else {
        return messageBuilder_.getMessage();
      }
    }
    /**
     * <code>.WebSocketMessageTaskProto message = 2;</code>
     */
    public Builder setMessage(protoModels.WebSocketMessageTaskProto value) {
      if (messageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
      } else {
        messageBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.WebSocketMessageTaskProto message = 2;</code>
     */
    public Builder setMessage(
        protoModels.WebSocketMessageTaskProto.Builder builderForValue) {
      if (messageBuilder_ == null) {
        message_ = builderForValue.build();
      } else {
        messageBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.WebSocketMessageTaskProto message = 2;</code>
     */
    public Builder mergeMessage(protoModels.WebSocketMessageTaskProto value) {
      if (messageBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          message_ != null &&
          message_ != protoModels.WebSocketMessageTaskProto.getDefaultInstance()) {
          getMessageBuilder().mergeFrom(value);
        } else {
          message_ = value;
        }
      } else {
        messageBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.WebSocketMessageTaskProto message = 2;</code>
     */
    public Builder clearMessage() {
      bitField0_ = (bitField0_ & ~0x00000002);
      message_ = null;
      if (messageBuilder_ != null) {
        messageBuilder_.dispose();
        messageBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.WebSocketMessageTaskProto message = 2;</code>
     */
    public protoModels.WebSocketMessageTaskProto.Builder getMessageBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.WebSocketMessageTaskProto message = 2;</code>
     */
    public protoModels.WebSocketMessageTaskProtoOrBuilder getMessageOrBuilder() {
      if (messageBuilder_ != null) {
        return messageBuilder_.getMessageOrBuilder();
      } else {
        return message_ == null ?
            protoModels.WebSocketMessageTaskProto.getDefaultInstance() : message_;
      }
    }
    /**
     * <code>.WebSocketMessageTaskProto message = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        protoModels.WebSocketMessageTaskProto, protoModels.WebSocketMessageTaskProto.Builder, protoModels.WebSocketMessageTaskProtoOrBuilder> 
        getMessageFieldBuilder() {
      if (messageBuilder_ == null) {
        messageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            protoModels.WebSocketMessageTaskProto, protoModels.WebSocketMessageTaskProto.Builder, protoModels.WebSocketMessageTaskProtoOrBuilder>(
                getMessage(),
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      return messageBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WebSocketTaskProto)
  }

  // @@protoc_insertion_point(class_scope:WebSocketTaskProto)
  private static final protoModels.WebSocketTaskProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new protoModels.WebSocketTaskProto();
  }

  public static protoModels.WebSocketTaskProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WebSocketTaskProto>
      PARSER = new com.google.protobuf.AbstractParser<WebSocketTaskProto>() {
    @java.lang.Override
    public WebSocketTaskProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WebSocketTaskProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WebSocketTaskProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public protoModels.WebSocketTaskProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

